
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Prayer NFT
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                            //
//                                                                                                            //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:-............-mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNN               hNNNNNNNNNNNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMM/---------------------------               .--------------------------:NMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMm                                                                       dMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMm                                                                       dMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMm                                                                       dMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMm                                                                       dMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMN`                                                                     `mMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMmdddd`              ydddddddddddddddddddddddddddddddddddddddddddddddddmMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMM`              mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMM`              +oooooooooooooooooooooooooooooooooooooooooooooosmMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMM`                                                              +MMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMM`                                                              /MMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMM`                                                              /MMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMM`                                                              /MMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMM`                                                              /MMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMM`              ossssssssssssssssssssssssssssssss:              /MMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMM`              mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo              /MMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMM`              mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo              /MMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMM`              mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo              /MMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMM`              mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo              /MMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMM`              mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo              /MMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMM`              mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo              /MMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMM`              mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo              /MMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMM`              mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo              /MMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMM`              mMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo              /MMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMdyyyy`              dMMMMMMMMMMMMMMMMMMNyyyyyyyyyyyyy/              /MMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMN                    dMMMMMMMMMMMMMMMMMM/                            /MMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMm                    mMMMMMMMMMMMMMMMMMM/                            /MMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMm                   `NMMMMMMMMMMMMMMMMMMh                            +MMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMm                   sMMMMMMMMMMMMMMMMMMMM`                          .NMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMm                 -hMMMMMMMMMMMMMMMMMMMMM+                        `+NMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMM+:::://////////odNMMMMMMMMMMMMMMMMMMMMMMN+/////////////////////+ymMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                            //
//                                                                                                            //
//                                                                                                            //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract PRAY is ERC721Creator {
    constructor() ERC721Creator("Prayer NFT", "PRAY") {}
}
