
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Salisby Dalisby 7/26
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        //
//    SalisbyDalisbyBooksArt,SalisbyscammedintoaArangatanBodyandputonhisfirstorbthatwasheavilycontaminatedandpoidonedwitheightdifferentsourcesofradioactivematerials,Salisbyattheageoffiveyearsofage,waschasedaroundinhishousewithhismotherpresentmostofthetime,momIambeingchadedbyfivedarkmonsters(deadmen),momtheyaretryingtohurtme,Icsnseetwoofthedarkmencarringbigdoctorssyringesandtheyaretryingtopoketheneedlesintome,allthatSalisbysmotherfoesistogivebabySalisbyanewteddybeartocalmhimdown,afterSalisbyhadbeendruggedbyoneofthedarkdoctors,Salisbywasnumbedtosleep,thedarkmen(monsters)werefinallyabletosubdueSalisbyandproceededtoinjectalargeamountofdarkmetalicfluidwithconciencetechnologyintoSalisby’shead,henceSalisbybecameaholymanforthefirsttimeasaresultofalargenewholeinthecenterofhisheadwiththenewadfitionofthdarkmonstertechnologycalled”ConcienceTechnology”,fromthatmomentthedarklordstormentedSalisbynightanddaywithallkindsofnightmares,SalisbyDalisbyJournalStorycontinues.    //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract VFotm is ERC721Creator {
    constructor() ERC721Creator("Salisby Dalisby 7/26", "VFotm") {}
}
