
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Witchhaven.eth
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                            //
//                                                                                                            //
//    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKXXKKXXXXXKKXXXKKKKXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKKKKK0kxdolcllodkOKXXKKKKKXXKKXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKKKKK000Okxo:'....;lx0KXXKKKKXKKXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKXKKKKXKKKKK0kdl,......'cx0KKKKXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKXKKKKXXKKKKKKKKKKKKKKKX0ko:,'............;dk0KXKKXXXXXXKKKKKKKXKKKXXKKKKXXXKKKXXKKXKKKKKKKKKK    //
//    KKKKXXKXXKKKXXKKKKKKKKKKKKXK0d:'.';;,..      .....':xOkxxdooodk0KXXKKKKKXXXKKKKXXXXXXXXKKKKKKXKKKKKK    //
//    KKKKKXXXXXXXKKKXXXXXXKKKKKKxc:codl:,..           ....'....    ..;lx0XXKKKKXXKKKXXXXXXXXKXXXXXXXKKKKK    //
//    KKKKKOkdolccc::ccclodxk0K0xoxOxl'.                   ..           .'lkKXKXKK0Oxdolc:::::::cloxO0KKKK    //
//    KKKKK0Okxdol:,...  ....';:cxx:.                      ......  ..     ..:xkdl:,'.... ...,;clodxkO0KKKK    //
//    KKKKKKKKKXXXK0Oxoc,............             .....   ........ ....    ............,coxO0KXXXKKKKXXKKK    //
//    KKKKKKKKKKKXKKKXXXKko:'........ ....       ....''''''........  ..... ........,cokKXXKKXXKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKK0Okkxdo:'.. ........   ........;ooddoo;........ ............';lxxkkO00KKXKKKKKKKKKKKK    //
//    XXKKXXKKKKXXK0koc::;;,'..  .........''''.''.';cdoododl;'.''.,,,,.............';:loddxOKKXKKKKXXKKKKK    //
//    KXKKXXXXKK0xl;.. ..................:l,::.;,'::ldoddodl::',;.::,l:.................',;coxOKKKKXXKKKKK    //
//    KKXKKXXKkl;',;,...................cdc:kxcxolkxO000000Oxkloxlxk:cd:'.....'............:llcodOKXKKXKKK    //
//    XKKKXKklclxOOo..................'cOOoxNX0K0OXKXNXXXXXXKKO0K0XNxlOOc,'.''''...........'o00kxddOKKKKKK    //
//    KKKK0xdkKKXOc.........',;'.....,lONOoOXXXXXXXXNXXXXXXXXXXXXXXXOoONOl;''',,,;,'.........c0XXKOkk0KKKK    //
//    XKK0O0KKKKO:.......;ccoxxc'...,cd0XkdKK0OOKXXXNNNNNNXXXXXKOO0KKdkX0dl:,,,;lxxocc;'......:OXKXX0OKKKK    //
//    KKKKKKKXXOc.....;oOKOdo:,;,...cdkKXkxd;...'lOXXNNNNNXXX0l'...;dxkXKkol;,;:;,:odOKOo;.....c0XKKKKKKKK    //
//    XKKXXKKXKo....,d0XKXKk:':o:'.;oxOXXOl.      cKXXXXXXXXK:      .cOXKOdoc;:lo:':kKKKK0d;...,dKXXKXXKKK    //
//    KKKXKKKXO;...l0KKXKXXx:clol;'cdx0XXO:   ..  ,0NXXXXXXN0,  ..   :OXX0xdl:coolc:xKKKKKX0o,''cOXKKKKKKK    //
//    KKKKKKKXx'.'dKKKKKKXOlxkoloc;lxkKXX0:  .lc. ,0NXXXXXXN0, .:l.  c0XXKkdoclolokxlOXKKKKXKx;':kKKKKXKKK    //
//    KKKKKKKKd'.oKXXXKKKKddKKkoolcoxOXXXKc   ..  ,0NXXXXXXN0,  ..   cKXXKOxdllookKKddKKXKKKXKx;:kKKXKKKKK    //
//    KKKKKKKXx,c0XKKKKKXOdOXXKkdoldxOXXXXl       ;0NXXXXXXN0,      .oXXXXOxxoodkKKXOdOXKKKKKX0ockXKKKKKKK    //
//    KKKKKKKXkcdKKKKKKKXkxKXKXKOxddxOXNXN0:.    'xXNNXKKXNNXx'    .:0XXXXOxxdxOKKKXKxkXKXKKXKKxlOXKKKKKKK    //
//    KKKKKKKX0dkXKKKKKXKkkKXXKKKKOOOOXNXXXXOoloxKNXXk;..;xXXN0xlloOXNNXXKOOOOKKKKKXKkkKXKXKKXXOxKXKKKKKKK    //
//    KKKKKKKXK00KKKKKKXKkOXXKKKKXKXK00XXXXXNNNNNXXN0,    ,0NXNNNNNNXXXXX00KXXXKKKKKXOkKXXXKKKK00KKKXKKKKK    //
//    KKKKKKKKKKKKKKKXKXKO0XKKKKKXKKXKO0XXXXXXXXXXXXXOddddOKXXXXXXXXXXXX00KKXKKKKXXKX0OKXXXKKKKKKXKXXKKKKK    //
//    KKKKKKKXKKXKKKKXXXK00KKKXXKKKKKXKOKNXK0KXXXXXXXXXXXXXXXXXXXXK0KXNK0KKKKKXKKXKKX00KXKXKKKKKKKKXKKXKKK    //
//    KKKKKKKKKKKKKKKKXKK00XXKKKKKKKKKKKXNKkdkKX0OKNNKOkxOXNNKO0XKkdkKXXKXXKXXKKKXKKK00KKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKXKKKXKKKKKKKKKXKKXX0xdxkOxxKNXKxddkKNXKxxOkddx0XKKKKKKKKKKXKKXKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKXKKKKKKKKKXKKK0kxdddx0XXKxddxKXX0xddddk0KKKKKKKKKKKXKKXKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKXKKKKKKKXKKKKXXK0OxddxOOxddddxOkxddxk0KXKKKXKKKKKKKXKKXKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXK0kdoooooooooodk0KKKKKXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXKKX0dooollooloodOXKKKXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXKOdoooooooooodOXKXXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKXXKKKKXXKKXXKKKK00kdoooooooooodk00KKKKKXKXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKXXKKKKKKKKKXKK00OOOOkkxxxxxxxxxxkkkOOO00KXXXKKKKXKKKKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKKKXKKKKKKK00OOOOOOOOOkkkOOOOOOOOOOOOOO00KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKKK0000000OOOOOOOOOOOOOOOOkkkOOOOOOOOOOOOO000000KKKKKKKXXKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKXKKKXKK00OOOOOOOOOOOOOOOOOOOOOkkkkkkkkOOOOOOOOOOOOOOOOOOO00KKXKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKXKKKXK00OOkkkOOOOOOOOOOOOOOOOkkOOkkkkkkkOOOOOkkkOOOOOOOkkOOOO0KKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKXK0OOOkkkkOOOkkkkkkOkkkkkkkkkkkkkkkkkkkkkkkkkkOkkOOOkkkkkkO0KXKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKXKKXK0OOOkkkkkOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOkkkkkOOOKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKXKKXK0OkkkkkkkkOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOkkkkkOkO0KKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKXXKOOkkkkkkOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOkkkkkkOO0KKKKXKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKK0OkOkkkkkOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOkkkkkkOO0KKKKXKKKKKKKKKKKKKK    //
//                                                                                                            //
//                                                                                                            //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract WITCHZ is ERC721Creator {
    constructor() ERC721Creator("Witchhaven.eth", "WITCHZ") {}
}
