// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

interface IPolls {
  function getDocumentProposalCount()
    external
    view
      returns (uint256 count);
  function hasVotedOnDocumentPoll(uint8 _galaxy, bytes32 _proposal)
    external
    view
      returns (bool result);

    function getUpgradeProposalCount()
    external
    view
      returns (uint256 count);
  function hasVotedOnUpgradePoll(uint8 _galaxy, address _proposal)
    external
    view
      returns (bool result);

  // getters autogenerated by Solidity 0.4.24

  function documentProposals(uint)
        external
        view
        returns (bytes32 proposal);
  function documentPolls(bytes32 proposal) view external returns
      (uint256 start,
       // bool[256] voted -- omitted by solidity
       uint16 yesVotes,
       uint16 noVotes,
       uint256 duration,
       uint256 cooldown);
  function upgradeProposals(uint)
        external
        view
        returns (address proposal);
  function upgradePolls(address proposal) view external returns
      (uint256 start,
       // bool[256] voted -- omitted by solidity
       uint16 yesVotes,
       uint16 noVotes,
       uint256 duration,
       uint256 cooldown);
}

