
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: I Must Draw
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                //
//                                                                                                                                //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNXK00kxddkXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0xl:,''.... ....';oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0xl;.  .',,,,,',,;:;'...c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOl,..         ..:c;;;,,,'..'cd0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0l,.     ............',,'....'.'cxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo,.   .,cloooc:;,'''''....... . .:coXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO;..   ,kNMMMMMWNXOkxlc:;.    .    ...cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,  ...oXMMMMMMMMMMMMMMWNKOxoc,..       lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl   .'lNMMMMMMMMMMMMMMMMMMMMMMWX0d,  .  .oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.   .cXMMMMMMMMMMMMMMMMMMMMMMMMMMMNd.    'kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;   ,xNMWXXKXNWWMMMMMMMMMMMMMWWWMMMMWo    .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx. .lXMMN0dolc::cdONMMMMMMN0dlllccoOWWd.  ..lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc'.:XMMMMNXK0Okxo;.,kWMMMWOlok00OOOKWMk.  ..:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNockcdWMMWOc;'...,o0x.,0MMMMNOoc;,;:l0WMXc  ..'kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc:x:dMMMWKO0OooddkXWd'dWMMMXxodc,:dxKMMWK: .'.dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl'c:xMMMMMMMMMMMMMMM0;lXNMMMMMMWNWMMMMMMWd. .,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO,.,xWMMMMMMMMMMMMMMK;:0NMMMMMMMMMMMMMMMWd  .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0o;lXMMMMMMMMMMMMMM0,,dONMMMMMMMMMMMMMMX:  cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0:dNMMMMMMMMMMMMMNkddkKWMMMMMMMMMMMMMO. cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk;dNMMMMMMMMMMMMMWNWWWMMMMMMMMMMMMMX: ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx,lKMMMMMMMMMNkl,',,;cdKWMMMMMMMMXc.:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO;;kNMMMMMMM0;.      ;OWMMMMMMNx,.cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl';kNMMMMMMN0kxdddONMMMMMWXx;.,kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk'.:KWMMMMMMMMMMMMMMMMWKo'.,kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk. 'ld0NMMMMMMMMMWN0d:. .dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl ,ooccoxO000Oxo:,,;,..kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk..kWNKkdc:;;;;;lkKWk.,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK, dWMMMMWNNNNWWMMMWx.;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX;.xMMMMMMMMMMMMMMMWd.;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX;.OMMMMMMMMMMMMMMMMx..OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO''0MMMMMMMMMMMMMMMMk. ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo. :XMMMMMMMMMMMMMMMMO.  ;OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0Od'  ,dk00KXXNNNXXK0kdl,  .,:dXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxdO0o:dl'  ...........  .. .clcdocdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkdlcoxc;kWWo'cxd;.;c,...:,,xKxcxKkclc':OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkxddkKWNOd::dOx;oNMMx:0MOc;dWKldNWk:oOxoxOxlokXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkxddxOXWMMMMMMWXOxllxkkkc;dOdl:lkkolkOkxkKNWMMMN0dod0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMWKkxxk0NWMMMMMMMMMMMMMMWWXK0OOkkOOOOkO0XNWWWMMMMMMMMMMMNOooxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWXkdxOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxloONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMXkolxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOolxKWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMW0dllkNMMMMMMMMWX000KXNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0dlokXMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMW0lcdKWMMMMMMWKdlodxdo:,lxdodkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOold0NMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMNOl:dXMMMMMMW0o;';oKWXkoodkOO0OolxKWMMMMMMMMMMMMMMWXNXOKWKKNXk0OkNMMMMMMMMMMWXK0kl;cxXWMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMW0lckXMMMMMWKxlcld0NMWXOkOO0KNWKO0KKOONMMMMMWNNWMNKNXodd'cKOxkx::clXMMMMMMMMWKxooxdkkc,;lkXWMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMXkc,dNMMMMMN0o;lKWMMMMMWWN0OKWMWXKXWMMN0OXWMMMXxlkXOxOOko,..d0xxOlodkNKxlkWMMMNoo0kxdxol::dolo0NMMMMMMMMMMMMMM    //
//    MMMMMMMWKo' 'xNMMMMN0x:;kNWXXWMMWNNWNWWWMWMMMMW0olOK0OKWXOxl;:d0xdOl..lKkkkdxdxdl;;OX0kkxdkOl'',cdkdkWXklldKWMMMMMMMMMMM    //
//    MMMMMMNx'.,o0WMMMMKxkOokWXd:;okdc:ck0OodKNWMNkooxO0OKK0O0O00xc,kKld0: ,0Oddko,;:dxxdoc''cxkOo,:kK0dckWMMW0l;oXMMMMMMMMMM    //
//    MMMMMXl.'xNMMMMMWOx0WklOkcc:;:::ol:lo:',lclxllOWNOkXWMMNKkx0XKd:xklxk..xOlxx'.:odo:;;:loc:cocokollco00KKOKNk;;OWMMMMMMMM    //
//    MMMMK:.cKMMMMMMWOdKMWo':ldclookOl:c:':xkc',lONMMWWMMMMMMMNOddkX0lodcoc.co:d:.:::c:,',cdkxdl::dx::kxO00KOdooxOc'oXMMMMMMM    //
//    MMMX:.oNMMMMMMMKoOMMWk'lkcokkOo'.'.'ddc;cx0kxXMMMMMMWWXXXXOl;oOKKococ:'',::..',;,.'coolc::c::xOO00kkxxdoxOd,;oc.oNMMMMMM    //
//    MMWx.lNMMMMMMMWkoXMMXc'dc;dOk,   .;c:cxKNNOoxNWWN0xdooooodo:.;dOOkc',...;;.  ';:cloddoodoc'..xKkxO0x:cddlokOo,:c;xWMMMMM    //
//    MMNc,0MMMMMMMMKx0WMWO'.:,.lo;. . .:lxkocldo:::;clodkKNWWWWWKOl,cl:'..',''....':lllllolc,.,:cdxxkOdlco0NkxkcxN0c;;;OWMMMM    //
//    MMK;:XMMMMMMMNkkWMW0d,... .,;....,clc::cllc,..;xKWMWX0kxddodkOxl,...,;,.   ...',';cldxxxdkOdoddo:cldxldccko:OMK:'':KMMMM    //
//    MWx,dWMMMMMMMKdKMXxd0o.  ..:oc....''''..  ...'':OXkdoodxO0KNNWXl....''.    .,.   .,;cok0KKK0doxc,c:oOkkxc:o;cxx:.:,oWMMM    //
//    MK;:XMMMMMMMWkxNNkxXNc..c:'':d0d'.,..........,:xXNNNWMMMMMMWNNNo.,,''...,,.;ol,....,;::,'':clOk,,dxOKNKocl;.;oo:oKo'xWMM    //
//    Xc.dWMMMMMMMNkOWKKWWd.'lc'..  ;Ox;;;,;;;:::;;cc:oKWKOOO00OOOOOxl;;:l;';coc;;'';,.   .;odl,..;k;.lkkkd0Xc...cxd,:XMX:'oXM    //
//    d. ,ok0NNWMMXxKMWWMWo.c0dcl:...oNo,::ccccccc:::lkNNOkO0KXNNWMMNxlc:lc:coc;,'.'dxc'.......:;..;,.cxclxkxc'.cOWk'lNMWk;.oW    //
//    '.'',odcokkkolKMMMMMK;'k0dl:'..oXl.;cclllc:;,,;ldONMMNXKKKK00KXOclOxol,,,..o0l;kN0o;;c:...;:c:;;d0dlccoo,:k00:;OKkkxo;:0    //
//     .xOokNklOXO:,OMMMMMMk'.::'..:dkl..;::::;;;;,..'c0WWKkdodddddx0o,xOx0o'ccl,'OXl'l0N0l::'.  .....,o0Odokk,;oc;:xkOOO0xdok    //
//    'llkOOKOOXMW0:oNMMMW0cld:,. .;c''cdxxxddol:;'...lXMWNNWWMMMMMWk;oOdOO;cxlxo.:KXl':d0Kl,c;...oc.'.'kOdol:;;,:ollk0x0WKx0W    //
//    dN0l;d0Okxod0k:kWMXxoxNMWX0xdxl..,c:'...'clllodOXWN0kxxddxkOOxldkoco:.lOcdO:;oKKc:dlc:':c,',;;:c,::lddxoocl00ococlx0KoxN    //
//    0XXo,xN0xxx0N0,'kXOONMMMMMMWNOkxkKNKOkdc,cOXWWXOkkkOKXKK0ko,..oXxkKkc;lxddOloo:kd':c'.'':,::',,,:clclxo:;oo:col;'::oxo0W    //
//    X0kdoK0kOOkxxddc'cKMMMMMMNOodkKWMMWNKO0NKkkO0OkKXKOkxxxdol;;l:dOx0NxdXN0dc:;c:..,::;.,c;:,,;.':;:::;:oc;dk:.';,..',coxKN    //
//    0OdcoK0Kkc;'':xo'.,dXMMMWOdONMMMNOkO00NMMMMWWNOk00O0XOl::,.;ddoodOxlKWNOc;;....:ol;:::Oxl:....:oc,'.oNNd:loxkO0KOdc:;:kW    //
//    '.;::0Ox0NXo;c::xo;',cdkKNWMMMMWKkKWMWWNXKK0kxdlc:,'';dOkOc.'clcoc:OXkc:o0Xo,cc:llokdcclclol..:oo;c:l0Ok0NWWWWMMMWx,:kKK    //
//    ..dxdXOcdKWXl.:kddKXOd;.,;:clodxdxOkdc;;'.,:;,;ll:ldookKOol,.;l:coxdclxXWWWK:.:c..;lo;..lkOl..,kKo;:lOXWWKkoxKOXMMKdxOOK    //
//    kXWOcON00NWk;:d::xKWWXOoccc'..',.,:,.;dc':xo;cxO0OOOOkxdocdo,;xOddlcx0Oxoood;...''lxd:,,:loo;..;c;;:xKNWXl..,:o0NWW0l;:x    //
//    NWW0:oNMMM0:co';kdlOkdxxoodo:;kKdkKolOd;;;ll;lkkkOOkdl::lloxoxxllxldkdodk0XO,..';,:cokoxk:::..'::,,;dOXWNk;''.,;dNMKdldO    //
//    xkOOkkOO00dod' ,ooON0oooc::oxdxOOxddkOxolo00ld0Oxxxoc:,;oxdc;clcoo';oddddddo''l,,',:coll:;c;''....:'.,cONNxlok0KXWNkc:lO    //
//    WWWWMMWX0llk: .lll0XOdoddddxxdokxloooxOKkdO0lcOK0kxoodo::oooxxc;kOc:clx0KXXXO;'co;cd;ckl;cc,':c.,o:.;:,,d0O0NWWNKkdllld0    //
//    MMMMMMMXc'do..xN0:d0dc:;:oO0ddkd::;,cdx00ddkodXNNX0OO0Oxdxo,..:ll;..';cld0NWO;,dl:o:'l;'c;...;c.,lc:c;'lOx:;oxoo::cdddOK    //
//    MMMMMMMk'lx'.colcckx:;c;:lxkxOKdcoo';kkoloodkxoOK0Oxddxdxx:'''',::;,,,:lc::o:l0k::l'.:l'..,'.,'.,kkc:okkxxc.lxl0Oc;:xOdd    //
//    MMMMMMWdcx: .;:.,oOKo';coddxkO0Oxodclxlol:cok0ddkkkkOOkoxolo;cl;:dolooc:x0k:.,l:,lo''lo,:dc';c:,dNX0K0xd0d.'OOoKWx;l0Koc    //
//    MMMMMMKcod';cdKl.,0Kc;xxllox00kkokk:oOxolloddxxoxXN0kxx0xl0k;cOx,ldlookKXX0kxoo;.',..,;':dolO0o;dXWMXxkNWklkX0xONXOXW0ON    //
//    MMMMMMk;o:'OKkxc..,coxxooddllOW0d00ox0Oko::lkkxddkkxOXWKlxWk;l0Nd:dddkoxkkOKkloo::;:;'.:kO00kkkddkxdoxNMMMMWK0KOxO00kkXW    //
//    MMMMMMklx:cXMWXKO:.lNNX0dxx,:K0OXXXOdkoxXKo',oxllxkOOOOoc0Wk:oKMXxk0ocdxdkNWKol:',;;co:'cdkxO000NWKlodOWMMWKxkKKxl;;xNMM    //
//                                                                                                                                //
//                                                                                                                                //
//                                                                                                                                //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract DRAW is ERC721Creator {
    constructor() ERC721Creator("I Must Draw", "DRAW") {}
}
