
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Pemi
/// @author: manifold.xyz

import "./ERC721Creator.sol";

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                              //
//                                                                                                                                                              //
//    ░░░███░░░░░░░░████░░▄▄▄▄░░░░░░░░░░░░░░░░░░░░▐█░░░░░                                                                                                       //
//    ░░██░████░█████░░░░▐█████░░░░░░░░░░░░░░░░░░░░▀░░░░░                                                                                                       //
//    ░░█░░░░░███░░██░░░░▐█░░██▌░░░░░░░░░░░░░░░░░░░▄░░░░░                                                                                                       //
//    ░░██░█░░░█░░░██░░░░▐█░░░█▌░░▄▄░░░░███▄░███░░░█▌░░░░                                                                                                       //
//    ░░░██░░░░░░░██░░░░░▐█████▌▐████▌░░████████▌░░█▌░░░░                                                                                                       //
//    ░░░░██░░░░░░█░░░░░░▐█▀▀▀░░██████░░█▌░███░██░░█▌░░░░                                                                                                       //
//    ░░░░░██░░░░█░░░░░░░▐█░░░░▐██████░░█▌░▐█▌░██░░██░░░░                                                                                                       //
//    ░░░░░░█░░░█░░░░░░░░▐█░░░░░███░░░░░█▌░▐█░░▐█░░██░░░░                                                                                                       //
//    ░░░░░░██░█░░░░░░░░░▐█░░░░░░██████░█▌░░▀░░▐█░░▐█░░░░                                                                                                       //
//    ░░░░░░░███░░░░░░░░░░░░░░░░░░▀▀▀▀▀░░░░░░░░░░░░░▀░░░░                                                                                                       //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXK0000KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOkO0OOOkkkO0000O0KWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOkkOKWMMMMMMMMMMWNK0Okk0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOxONMMMMMMMMMMMMMMMMMMMWKkxONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0xONMMMMMMMMMMMMMMMMMMMMMMMMN0kxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKxxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMXOxOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0dOWMMMMMMMMMWXNMMMMMMMMMMMMMMMMMMMXxOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOdKMMMMMMMMMMMKOKWMMWWWWWMMWXNWWWMMMMXk0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0dKMMMMMMMMMWWM0lxOk0Okddxd00llk0xdk0kkkkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKd0MMMMMMMMWNXWKo;oxokxxddddO0kxk0kkkkoccl0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWxkWMMMMMMMWXXXOx0XXNWMWWMMMMMMMMMMMMMWMXkokNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0dKMMMN000XX0OkONMMMMWXOxddddONMMMN0xoldOOxx0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWxkWMMXkxxlok0XWMMMMMMN0kxdol::OMMM0c:ldkOkKxkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKd0MMMXk0KOkXMMMMMMMMNOddddookXMMWWXo:llooxNkxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOxWMMMW0OKXNXNMMMMMMMMXxcccoxkKMMN00xdxxOkxKOdXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNxOMMMMMWKdx0OKWMWNXWMMMMMWNWWMMMMW00MMMMMNx0Xx0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKxKMMMMMMMKxkKKKNMWK0KWMMMMMMMMMMMMX0XMMMMKxKWkxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOxNMMMMMMMMXOkkoxNMMWK0XMMMMMMWWWMMMK0NMMWkOWMKxKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWkkMMMMMMMMMMNOOOlxWMMMXXWMMMMMWK0KKKKKWMW0kNMMNxOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNxOMMMMMMMMMMW000lcKMMMMMMMMMMMMWNK0OOXWXOOXMMMMkxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXdOMMMMMMMMMWWNXNkok0NMMMMMMMMWKxl;,,'lKOxKMMMMM0xKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKd0WWMMMMMMMXNWXXkONOkONMMMMMMXd,...,;lk0NWMMMMMNxOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKdKXXWMMMMMWKXWNKxOMMNOkOKWMMMMMN0kdkOxOWMMMMMMMMkxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMKkOOOOOOOO0OOKWMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0dK00K0WMMMXOKMM0dKMMMMWKOOOKNMMMMMWKxONMMMMMMMMMOxNMMMMMMMMMMMMMMMMMMMMMMMMMMMM0xKNNNNXXXNX0KWMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOdX00kl0MMM0o0MNdxWMMMMMMMNK000OkkOOkKK0NMMMMMMMMKd0MMMMMMMMMMMMMMMMMMMMMMMMMMMMKk0NNNXXNNNKOXMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOdXOOkl0MWXdoXXodNMMMMMMMMMMMMWXOcxWNOOOkOKWXNMMMNdkMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOOKXXKKKXK00NMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMxd0kkooKWKOxxdlkNMMMMMMMMMMMMMMMKllOKKOkkxxkkOKNWMkdWMMMMMMMMMMMMMMMMMMMMMMMMMMMWOlccc:::;:l0WMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWkdkodokNKxo:. .;cdkKNMMMMMMMMMMM0dd,.,ldxOOOkkxdkKOd0MMMMMMMMMMMMMMMMMMMMMMMMMMMM0l,...'..;oKMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOxxdoc:;.  .'..    .';codxkkkxdl;.  ..  ....',;;;lkxkWMMMMMMMMMMMMMMMMMMMMMMMMMMMXd;'.....;oXMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0ko:,'.         ...''..                .             .'c0MMMMMMMMMMMMMMMMMMMMMMMMMMMNx:'....',dWMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMW0o:'.                   ..''.............                   .xWMMMMMMMMMMMMMMMMMMMMMMMMMW0l;'''',c0MMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMWOc.                                                          . .dWMMMMMMMMMMMMMMMMMMMMMMMMMW0olooooOWMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMXl.   ...                                                     ;,  .kMMMMMMMMMMMMMMMMMMMMMMN0kkkxkKKxlxWMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMNc      .''.                                                  ';.   ;KMMMMMMMMMMMMMMMMMMWXkxk0XX0dkOxxxKMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMk.        .,.                                                 ,'     oWMMMMMMMMMMMMMMMW0xxOXNXkc:lc:xKdkWMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMWl           ',.                                              .,.     '0MMMMMMMMMMMMMNOxkKNK0OkkOKOc:oxkx0MMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMN:            .,.                                         .    ..      cNMMMMMMMMMMMNxdXMMMMMWKOkkdkxlkkd0MMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMX;             .'.                                        ',. ..       .OMMMMMMMMMMWkxNMMMMMXxxOKNNKxlclxKMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMK;              ..                                         .,..:.       dMMMMMMMMMM0xKMMMMWKdOWWNNXK0kOOKWMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMX;                                                           ..;;       :NMMMMMMMMNxOMMMMNOxKWKOO000O0K0kONMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMX;     .                      .'..                             'c.      .kMMMMMMMNkkNMMMMXKXK0kod0KKKKXXXNMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMX;     ,.          ..      .','.                               .:,       cNMMMNOkodNMMMMMKOOOO0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMX;    .;.          ,;     ',.                                   ,:       .OMMMXocoxOKNMW0dKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMN:    ,;           ,:.  .;.                                     .:.       lWMWOoONX0kOXOdKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMWc ...:.           ':. .,.                                       ;,    .. .OWOdKMMMWKkdokKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMN:.,';,            ':........                                    ,, ...'. 'OkdKMMMMMMXdd0KWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMX; .;'             .,. .'..                                      ;;  .  .:ooxXMMMMMMMkxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMk. ''                   ....                                    .:.  .,o0XdoXMMMMMMMKd0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWl                  ..                                          ':;;lx0NMNkxNMMMMMMMWkkWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMX;                  ;'                                        .,'oNWMMMMWkxNMMMMMMMMKxKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMM0'      .......     ;'      .....'...                         .  cWMMMMMKxKMMMMMMMMNxOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMK;        ......   .;.           ....                            cWMMMMWOOWMMMMMMMMOxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMXko:cc:,''....'',',.                                            dMMMMMW0KMMMMMMMMXx0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMXOXMMWWNNNNNNWWOo.                                           .xMMMMMWNWMMMMMMMNxkWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMN0XMMMMMMMMMMMWOx;                                           .oNMMMMMMMMMMMMMWOxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMN0KMMMMMMMMMMMMOkc                                           .ckNMMMMMMMMMMMMKxKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMW0KMMMMMMMMMMMMOOo                                           .xdxWMMMMMMMMMMXxOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWKKMMMMMMMMMMMM00x.                                          .OXdxXMMMMMMMMXxOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMKKMMMMMMMMMMMM0Ok.                                          .OMNOxkKNMMWXOkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMK0MMMMMMMMMMMMOkk'                                          .kMMMN0kO000O0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMM00WMMMMMMMMMMM0kk'                                          .xMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMM0OWMMMMMMMMMMM0Ox.                                           dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                                                                              //
//                                                                                                                                                              //
//                                                                                                                                                              //
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract Pemi is ERC721Creator {
    constructor() ERC721Creator("Pemi", "Pemi") {}
}
