
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Cypher City All-Stars
/// @author: manifold.xyz

import "./ERC721Creator.sol";

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                      //
//                                                                                                                      //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXKWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl;d0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx. .cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0,   .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc     ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk.      cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;  ,;.  .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo  .dkd;  ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.  :0K0d.  lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;  'kKKK0c  .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo  .o0KKKKk,  ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.  :OKKKKK0o.  oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:  'kKKKKKKKO:  .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd. .o0KKKKKKKKk,  ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO'  :OKKKKKKKKK0o. .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:  'kKKKKKKKKKKKO:  'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd. .l0KKKKKKKKKKKKk'  :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO'  ;OKKKKKKKKKKKKK0o. .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:  'xKKKKKKKKKKKKKKKO;  'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    NKOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOl. .l0KKKKKKKKKKKKKKKKx'  ;kOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0XW    //
//    NOc'.                                       :OKKKKKKKKKKKKKKKKK0l.                                       .:xXW    //
//    MMWKd;.    .,::::::::::::::::::::::::::::::ckKKKKKKKKKKKKKKKKKKKOo::::::::::::::::::::::::::::::;.     'lONMMM    //
//    MMMMMN0o'   'cx0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK00OkkkkkkkkkkkO0KKKKKKKKKKKKKKKKKKKKKKKKKKK0kl,.  .ckNMMMMMM    //
//    MMMMMMMMNOl'  .,lk0KKKKKKKKKKKKKKKKKKKKKKKKKKKKOdc,.............,xKKKKKKKKKKKKKKKKKKKKKKKK0Oo;.  .;xXWMMMMMMMM    //
//    MMMMMMMMMMWXx:.  .;ok0KKKKKKKKKKKKKKKKKKKKKK0kc'                'xKKKKKKKKKKKKKKKKKKKKK0Od:.  .,dKWMMMMMMMMMMM    //
//    MMMMMMMMMMMMMWKd;.  .:dO0KKKKKKKKKKKKKKKKKKOl.      'lddddddddddx0KK00KKKKKKKKKKKKKKK0xc'   'lONMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMW0o'   .cxOKKKKKKKKKKKK0KKOc.      ,kKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0kl,.  .ckNMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMNOl.   'lk0KKKKKKKKKKK0o.      .o0KKKKKKKKKKKKKKKKKKKKKKKKKK0Oo;.  .:xXWMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMWXkc.  .,ok0KKKKKKKKO;       .dKKKKKKKKKKKKKKKKKKKKKKKKKOd:.  .,dKWMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMWKd;.  .;dOKKKKKKO;       .dKKKKKKKKKKKKKKKKKKKKKK0xc'   'l0NMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMW0o,.  .cx0KKK0c       .dKKKKKKKKKKKKKKKKKKK0kl,.  .ckNMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOc.  .o0KKKk'       c0KKKKKKKKKKKKKKKKKKk,   ;xXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK,  'kKKKK0x,      .oO00000000000KKKK0K0c  .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo  .o0KKKKKKOc.      .',,,,,,,,,ckKKKKKKk,  ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO'  :OKKKKKKKK0kl,.              .xKKKKKK0o.  oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX:  ,kKKKKKKKKKKKK0Oxoc:::::::::::lOKKKKKKK0:  .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd. .o0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0Kk,  :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMO'  :OKKKKKKKKKKKKKKK00xc:coO0KKKKKKKKKKKKKKK0o. .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMX:  'xKKKKKKKKKKKKKK0kl'.    .:dOKKKKKKKKKKKKKKO:  'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMWd. .l0KKKKKKKKKKK0ko,.  .:c:'   'cx0KKKKKKKKKKKKx'  :XMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMO'  ;OKKKKKKKKK0Od:.  .;dKWMWNkc.  .,lk0KK0KKKKKK0o. .dWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMNc  'xKKKKKKK00xc.  .,o0WMMMMMMMWXx:.  .;oO0KKKKKKKO:  'OMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMWx. .l0KKKKK0xc'   'lONMMMMMMMMMMMMMWKd;.  .:dOKKKKKKx'  cXMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMM0,  ;OKKK0ko,.  .:kXMMMMMMMMMMMMMMMMMMMW0l'   'cx0KKK0l. .xWMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMNc  .dK0Od;.  .;xXWMMMMMMMMMMMMMMMMMMMMMMMWNOc.  .,lk0KO:  ,0MMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMWx. .cOx:.  .,o0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXx:.  .;oOx.  cNMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMM0,  .;'   'lONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd;.  .;'  .xWMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMNl      .:kXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0o'      ,0MMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMk.   .;xKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkc.    cNMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMK; .,o0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXx:. .kMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWd;lONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKd;lXMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWXXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKNMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                                      //
//                                                                                                                      //
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract STARS is ERC721Creator {
    constructor() ERC721Creator("Cypher City All-Stars", "STARS") {}
}
