
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Dylon Thomas Burns
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                            //
//                                                                                                            //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0koc;'.................';cdOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOo:'..';ldxOOO0KKXXXXKK00Oxoc;...;dKWMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkc'..;okKNWMMMMMMMMMMMMMMMMMMMMMWXOo,..lKMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd'..ckXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk; .xWMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx'.,xXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo..xWMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMK: .dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl 'OMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMX: ,OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0' oWMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMWl .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX; .ccclloxk0NMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMM0' lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo,;:::;;'...':xXMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMk..xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMWXKkl'.'kWMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMk..xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl..xMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMM0' lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX; :NMMMMM    //
//    MMMMMMMMMMMMMMMMMWNK0Okxxdxo' '0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX; :NMMMMM    //
//    MMMMMMMMMMMMMWKxc,.............lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXK0Okl. dWMMMMM    //
//    MMMMMMMMMMMMXl..,ldk0KXXNNNNNXKKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXK0Okxolc:;,'......'lXMMMMMM    //
//    MMMMMMMMMMMNc 'kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXK0Oxdolc:;,'......';:clodxkO0KXNWMMMMMMM    //
//    MMMMMMMMMMM0' oWMMMMMMMMMMMMMMMMMMMMMMMMMMWNXK0Okxddolc:,'......',;:clodxO0KXNWWMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMK, cNMMMMMMMMMMMMWWNXK0Okxolc:;,'......'',;:cldxkO0KXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMWd..dNMMMMMMMMMMMO;.......';:clodxkO0KXNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMNx..,okO0Odo0MMMo .lO0KXNWWMMMMMMMMMMMMMMMMMMKodXMMMMMMMMMMMMMMMNKNMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMWKd:'.....;kWMMo '0MMMMN0XWMMMMMMMMMMMMMMMMMx..kMMMMMMMMMMWN0dc'.oNMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMWNK00KXWMMMWl ,KMMMWd..;ldk0XWMMMMMMMMMMMd..kMMMMWNKOxl;...,lkXWMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMWc ,KMMMMXOdc;....,;clooddxkkk: .:olc:,'...,cokKWMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMNc ;XMMMMMMMMWNKOxol:;,''......  .,;:cldk0XWMMXOKWMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMN: ;XMMMMMMMW0dOWMMMMMWWWNXXXXo .kWWMMMKlcOWMWo.;KMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMX: :NMMXdoKMWc ;KMMMMMMMMMMMMMd..kMMMMMK: .dNWl ,KMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMX; :NMMK; .dKc ;KMMMMMMMMMMMMMd..OMMMMMMNx. ;kc ,0MMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMN0d. cWMMMNx'.'. ;KMMMMMMMMMMMMMx..kMMMMMMMMKl... '0MMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMWKd:'..':kWMMMMMXd'  '0MMMMMMMMMMMMMx..OMMMMMMMMMWKo.  ,ldkOOkONMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMXd;..,lkKNMMMMMMMMMMK;  .lONMMMMMMMMMMx..OMMMMMMMMMMMWo       ..;0MMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMXo..,o0WMMMMMMMMMMMMMMWc .;..'cxO0KXWMMMx..OMMMMMMMNKOxl.  ..,cdkKNWMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMWk' ,kNMMMMMMMMMMMMMMMMMWc ;KKo'   ...xWMMx..OMMMMMMXx;.    .oXWMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMWd..lXMMMMMMMMMMMMMMMMMMMN: .;,...,:clxKMMMx..OMMMMMMMWKkl;.  .;clodxxxxxk0XWMMMMMMMMM    //
//    MMMMMMMMMMMMMMk. oNMMMMMMMMMMMMMMMMWKkl,. .,lxOXWMMMMMMMMx..OMMMMMMMMMMMWo .;'    .';cdkKNWMMMMMMMMM    //
//    MMMMMMMMMMMMMNc ,KMMMMMMMMMMMMMMMXx;..':. ,KMMMMMMMMMMMMMx..OMMMMMMMMMMMMd  ...;okKNMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMX; :XMMMMMMMMMMMMMMM0;,oONWc ;KMMMMMMMMMMMMMx..OMMMMMMMMMMXd'  ;xXWMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMWx. ;xKWMMMMMMMMMMMMMNNMMMWc ;KMMMMMMMMMMMMMx..OMMMMMMMMXo... .kMWMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMWKo,..,;cccc:xWMMMMMMMMMMWOlkNMMMMMMMMMMMMMx..OMMMMMMMNd.,xo..cddxxxxxxkkkKMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMN0xocc:'  oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMx..OMMMMMMMMNKNMO;''''....... .dWMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMd..kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx..OMMMMMMMMMMMMWWNNNNNNNXXK: ,0MMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMo '0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMx..OMMMMMMMMMMMMMMMMMMMMMMMO. oWMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMd .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd..OMMMMMMMMMMMMMMMMMMMMMMNc ,KMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMx..kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx..kMMMMMMMMMMMMMMMMMMMMMWx..xWMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMM0' oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMKodXMMMMMMMMMMMMMMMMMMMMMK, cNMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMNc ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc '0MMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMk..dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd..xWMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMNl 'OMMMMMMMMMMMMMMMMMMMMMMMNKNMMMMMWNNMMMMMMMMMMMMMMMWx. oNMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMK; ;KMMMMMMMMMMMMMMMMMMMMNx,.,xKKko:'cKMMMMMMMMMMMMMWO. cNMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMM0' :XMMMMMMMMMMMMMMMMNxl, .:,....';. cNMMMMMMMMMMMMO' :XMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMWO' ;KMMMMMMMMMMMMMWO,  .cOK0oclx0Kl .dWMMMMMMMMMWk. :XMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMM0; 'OWMMMMMMMMMMMWo   ......'.....  .kMMMMMMMMWx. cXMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc..oXMMMMMMMMMMMK;  .okkkkkkkkkkkkkKMMMMMMMXl..oNMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk' ,kWMMMMMMMMMM0'  ;KMMMMMMMMNkkXMMMMMMW0; 'kWMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl..:OWMMMMMMMMM0d; .o0XNX0xl'.,OMMMMMXo..:KMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c..:ONMMMMMMMMMNx;...'...'ckXMMMMNk, 'xNMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c..;xXMMMMMMMMMWKkxdxkKNMMMMMNk;..oXMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo'..lONMMMMMMMMMMMMMMMMMWKd,..oKMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk:..,oONMMMMMMMMMMMWKx:..,dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKx:..':lkXWMMNKko;..'lONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXxc;...;c:'...:oONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXd,  .,lkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                            //
//                                                                                                            //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract MrBurns is ERC721Creator {
    constructor() ERC721Creator("Dylon Thomas Burns", "MrBurns") {}
}
