
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: JanusSpans
/// @author: manifold.xyz

import "./ERC721Creator.sol";

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                              //
//                                                                                                                              //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0kkxocckWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNWMMMMMMMMMMMMMMMMMMN0XMNo,.lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMNOO0kxOXXKXWMMMMMMMMMMMMMMXx0M0' .oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMNK00k:l0xl0NK0OokXNMMMMMMMMMMM0xXMK:  cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMXdd0OdcokkldXKko;dXKKXWMMMMMMMWklKW0,  cNWWWWMMMMMMWNXKOk00kx0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMKkkoxNMWWMNkc'lKXo:0X0KKOkO00OOkd,,0M0;  ,oxkOOOOkk000OOkc;dx:cONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMWkckNWMMWMMMWkc;;c;;0NkxKk:lk0XX0o.;KMXc..,oddddxddloO0XNkckXd'cxdkKK00XXNWMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWkodkOOKWMMMWWNOxl'cKNOd:lXXXNOlc:;lkO;  .oxdl:;;,,lxkkd..''. ,lcccdxcxxcdO0NMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMWxckKNWMMWNWMMMMW0ocd0k';0W0xolOKc..l:..:KXklldKk;:ddc'.  .;cccdooXNdclcd:;0WMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMWOox0WWN0xOWW0ONMMWK:..,:x0ooKWN0kl'.  .odllxKWMO;co;.;do:;';dKNx:ONo,;:c:ld0MMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMNOddo;:x00d;oXMMW0Od'.xNOlONXKKNXx...:dddlo0XO;.',.'l0XKx:kMWKc'dx';l;,:olxWMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMKxd,.'.':cododddKXc.'xkcxWWKkk0KOl::okooxxddo,.;;cdOdl;'kXx' .:,..,c;.':0MMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMW0ONX0O:'::.. .o0KN0;..:':KK0Xk0MM0do0KxxO0X0doxOc;xkxOl .'.,lO0KOdc.  ;KWMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMXx0MMNNNOxo'   ...;ol:cdkOXo;ocxN0kkkkkkKN0xo:xNXxoxoll'..;ONMMMMMMXl  oWMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMOdXMKONMMMWO:......'',:,;lxlcxdoooOK0ol0Ol;ckl,xXd,;' .:lkNMMMMMMMMMO..xWMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMXloNXodNWMMMMW0xxddd:.    ...;OWKl,lOxloddkl',..x0:  .:OWMMMMMMMMMMWW0;.dWMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMXoc0Wx..':x0KNNWMMMWMKoc'  ...;okko' ...,dOKd;,,kWk..:kNMMWWNNNNXOlc:c0d.lNMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMNolKW0l.    ...,;coxxx0NWx..,.,0N0c.     'coOOl;lko,:0WMMNx:cc;...     c0c:KMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWxoKXkkKk;   ... . .lkkkk0k,.'.cXMWd.     ,olodl:OKodXMMMNo.  .         ,0k,oNMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMKdOW0kNMMXo..;xk:...';o0Xxooc.,0WMKc'.    ,xdx00OkxxKMMMMX:  ...ol..'cl,cKNc'kWMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMWOkNMXXMMMMO,;xO0OOOOkdcoKKkko':OOKKc.      ,oO0K0o:kWMMMMWXdck0xddl;c0WNNMMO,:XMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMKkXMMMMMMMM0d0WWXKK0KKXX0KXkdodOOdx0o.       'dOoc:;dNMMMMMMWOkKKo,,ckNWWWMMWd,xWMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMKkKMMMMWKOXMMMMMMWWMMMMMMMMM0::dKW0dl:;.   ...:0M0oOdlXMMMMMMMWXKOkOKN0ooOKWMMXllXMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMXxONOolldd:;oKWMMMMMMMMMMMMMXd:;;dXOkOkl,     .cxxk0NKoxWMMMMMMMMMMMWWk;lKNXXNWM0lkMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMXo::....:kOd:;c0NNMMMMMMMMWNkoko,lkKNKo,...   'l,,oKN0okWXXMMMMMW0xxOkl,o0d,.'ldl':XMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMN000XkcOWMMNo.,dKWMMMMMMWKodkookKK0KXKko:;. ,kXXOxOOodNNkOMMMMXo.cKNNXOl;.    ...:KMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMKdc:oONXx:,cKMMMMWNK0c.:oONNWWKOKkxkxc.,0MMXkKNxokxkXMX00c.cKXddOkxxd;. ;OXXNWMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMXc'::dNMWOldNMX0OO0xc;:okNN00NKc..,;;'..:llo0NO:.:KMMXo;:kKkoox00Od;.  'OMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMW0;lNNXWWNNNO0W0d0Xko0OxKXXxo0Ko.  .,dx.   ,xO0OxdolkXWNxo0XdlONMXkc. .cONMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMXxlxKMWNX0kKKOKNKOKXkO00XXKOdkNXl   .:kO'  ....;kOkdooo0WWKkXWKkXWd.  .xWMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWNk;:kNMN0000WWNNNWMWNOOxldkdloll;.. .xNWXx;.   .,ldxxONk:kKkKWMMWMM0l:;,kMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMKdoxOXWMWWWNNWMNKXNNWWKxdkKNXl,:c';kk0NMMMMXl. . .'.:0KKxo0XldNWX00KkdKOcdNWMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMKokWMMMMX0X00WWOxkxoxkO0kOOol;....xWMMMMMMMWXOl. .  ;xldKWXOOKWWNXd;lxOKOxdoKMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWOlll::ldOOc:oookOdccooc::.  ....dXMMMMMMMMMMWk,..   ..:lkOdkKN0x0Oxkxx0xlcoKMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMNk:..,;......''.......       ,OMMMMMMMMMMMMMXo. ..     .ol:kNKOOl,..;,. ,0MMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMNKx,.   .....        ... .oKWMMMMMMMMMMMMMMXl,,.. ...    .,cxk'       ;0MMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMWKkkd,..       ''...:kOKWWXXWMMMMMMMMMNNWMKd:..  .         .     .cOXWMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0o;.     ';. ;0MMWNXXWMMMMMMMMMMNKXWMXc..        .  ....,:lONMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx,.   ',:kXWNKKNWMMMMMMMMMMMMMWXKKXx:...     ;kOOKXKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNO:':oOXMMMWNWMMMMMMMMMMMMMMMMMNXKkc:c.     oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx:kXNXXKK00KXNMWNK00000OkxdkOkkOkool...  ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx:d0KKKKXKXXNWMMWNNWWWWWNK0KK0Okkxdl;,,,.:OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkxxxkKNWMMMMMMWNK0kxxdddddxxdddxOKXNNWNNNNNKklo0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOcdKNMWWNKkolc::,'..''''''',;:::;,',;:loddkO0XWK:lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKkkOkoc:;,',;cloodkKXNNNNNNNWWMWWNXKKXXKOxoodxkkx0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0xxxOKXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMWx::kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNOl:;,,;cOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMM0, .dWMX0kkkk0XWMMN0OKXKkk0NMMWKO0NMMX00XMMNKOkkk0XWX0l  ;odolckWMN0OKX0kkKWMMWXOkkkk0NMMMN0OKX0kkKWMMWX0kkkOKNM    //
//    MMMMMWd. ,0MNd;::,..,kWMk. .;;. .lNMO' ;KMXc .xWO;.';;,,xW0o, .;dk0NWMMWx. .;;. .lXMXo;::,..;0MWd. .:,. .dWNd..,:;,:0M    //
//    MMMMMX:  lNMXxollc.  oWNc  ;OXl  ;XWl  lNMO. '0Wo  ,ldx0NMWXk:'.. .'xNMNc  :0Nk. .kWKdool:. .xMK; .cKK:  lNK, .:oxkKWM    //
//    MMMMMO. .kWO,..co:. .kMO' '0MNc  oWK, .kMXc  lNMXd:,.  ;KWNXNWNKO:  ,KMO. .OMWk. 'Ox'.'lo;  '0Mx. ;KMK; .xMWOl;'. .oNM    //
//    MMMMWl  :XWo  'od;  ;XWo  cNM0' 'OM0'  ;l;. .kWkcldd:. ;KO;.,:ll:. .dNWo  .;l:. ,OX:  ,do,  lNNc  oWMk. ;KXdcool, .oNM    //
//    MMNKd. .xWMXdc:lxdllOWWklo0MMKolkNMWOl:cdxocxNWOoc::clxXWXxolc::clxKWMK; .ldc:lxXMWKocclxdlo0MNxcdKMW0llOWXxcc::coOWMM    //
//    MXl...;kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk. ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MN0k0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKxd0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                                              //
//                                                                                                                              //
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract JANUS is ERC721Creator {
    constructor() ERC721Creator("JanusSpans", "JANUS") {}
}
