
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Treeple Dreamers AI
/// @author: manifold.xyz

import "./ERC721Creator.sol";

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             //
//    [size=9px][font=monospace][color=#70695e]▒[/color][color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒[/color]                                                                                                                                                                                                                                                                                                                                                                                 //
//    [color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒[/color]                                                                                                                                                                                                                                                                                                                                                                                                                                  //
//    [color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒[/color]                                                                                                                                                                                                                                                                                                                                                                                                                                  //
//    [color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒╨╜╙``   ,,,,,,,,,,   `"╙╜╨▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒[/color]                                                                                                                                                                                                                                                                                                                                                                                                                                  //
//    [color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒, `"╜╜╨╨╨▒▒▒▒░░▒░▒▒╨╨╜╜╜"  ╓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒[/color]                                                                                                                                                                                                                                                                                                                                                                                                                                  //
//    [color=#70695e]▒▒▒▒░▒▒▒Å▒▒▒▒▒▒░▒▒▒▄░▒▒▒░░░▒▒▒▒▒▒▄N╥▄m▄▄╥╖╖╖╖▄╥╖ggA▄M▒▓▀▒[/color][color=#6d5426]▓[/color][color=#645337]▓[/color][color=#6e675c]░[/color][color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒[/color]                                                                                                                                                                                                                                                                                                                                      //
//    [color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▐[/color][color=#624f30]▌░▒▄[/color][color=#553f47]▓▓▓▓▓[/color][color=#70695e]▒[/color][color=#70695e]▒▒[/color][color=#4b413a]▓[/color][color=#695125]▓▀[/color][color=#6b6459]░▀[/color][color=#655e53]▒[/color][color=#493f39]▌░[/color][color=#624019]▓█▓▓▓▀▓█▓▓░▓▓░▓░░▓▓▓▓░[/color][color=#70695e]▒[/color][color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒[/color]                                                                                                                                              //
//    [color=#70695e]▒▒▒▒▒▒▒▒▒▒░▒▒▒▒▒▒▒░░▒░░[/color][color=#422031]█[/color][color=#721941]▌▒▓▓[/color][color=#554551]▀▓▄█▀[/color][color=#6d5f48]░░▒▒█▒▒▓▓▓▀▒▒█▒░░▐▒▓▓░▓▓▄▄▓░╢░▓▀▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒[/color]                                                                                                                                                                                                                                                                                                                                      //
//    [color=#70695e]▒▒▒Å▒▒▒▒▒░▒▒▒▒▒▒▒▒▒▒░▒░▓[/color][color=#3e2b34]█[/color][color=#2e282e]█▓█[/color][color=#635a53]░▐[/color][color=#695d45]▒▀▓▒▓▄[/color][color=#595527]▓[/color][color=#4f4216]█▒Å▓▀[/color][color=#5a734f]▒▓[/color][color=#526346]▒▒▒▒▒▒▄[/color][color=#574d1f]▓▒▓Ö▀░░▓▓▓▓▓▌▒▒░▒▒▒▒▒▒▒▒▒▒▒▒▒[/color]                                                                                                                                                                                                                   //
//    [color=#70695e]▒[/color][color=#70695e]▒▒▒▒░▒░▒▒▒▒▒▒▒▒▒▒▒░[/color][color=#664c1e]▓▄▌▒[/color][color=#6e5019]▓▓▀Ñ▌▀[/color][color=#5a734f]▒[/color][color=#576e4e]▒▒[/color][color=#4f4a28]▓[/color][color=#423f2b]█▒▌▓[/color][color=#5f7a54]▒[/color][color=#5f7a54]▒▒▓[/color][color=#554d1f]▓[/color][color=#6f4e0b]▓▓▓▓█▓▓[/color][color=#516449]╫[/color][color=#5b6f49]▒▒▒▒▒▀▓[/color][color=#4a391e]█▓▒[/color][color=#9f1852]▒[/color][color=#b4195a]▒▓▓▀[/color][color=#6d6455]░[/color][color=#6f685d]▒▒▒▒▒▒▒▒▒▒▒▒▒[/color]    //
//    [color=#70695e]▒▒▒▒░▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░[/color][color=#5b4d37]▓[/color][color=#554836]▓Ä▀▓▓▀█▒▒▒▐▌▒▒▒▒▒▒▒▒▓▓▓█▓[/color][color=#d81d6b]▒▓▓▓▒▓▓▀▒▒▒▓██▓▓▓▓▀▓▀[/color][color=#6e675d]░[/color][color=#70695e]▒▒▒▒▒▒▒▒▒▒▒[/color]                                                                                                                                                                                                                                                                                                               //
//    [color=#70695e]▒▒▒▒▒▒▒▒░▒▒▒▒▒▒▒▒▒░▒▀░▒░░[/color][color=#6d572e]▀▀▒▒▒▒▒▒▒▒╢▒▄[/color][color=#765f1b]▓▓▒▒▀▄▀██▓▀▓▒▒▀▌▒▒▒▓▓█▓▓b░▒[/color][color=#6e675c]▒[/color][color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒▒▒[/color]                                                                                                                                                                                                                                                                                                                                      //
//    [color=#70695e]▒▒▒▒░▒▒░░▒░▒▒▒▒▒▐▓[/color][color=#681f40]▓[/color][color=#452837]█[/color][color=#61545b]▒▌[/color][color=#70695e]▒▄▀▌▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░▄[/color][color=#3a2019]█▀▀▀▒▒▒▒▒[/color][color=#493f2d]██[/color][color=#4b593e]▒▄▓▓▓[/color][color=#6a6255]░▓░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒[/color]                                                                                                                                                                                                                                          //
//    [color=#70695e]▒▒▒▒░▒▒▒▒▒░▒░▒▒░[/color][color=#53213b]▓[/color][color=#c71c64]▒▒▓█▌▀[/color][color=#6d665c]░[/color][color=#70695e]▒▐▒▒▒▒▒▒▒▒▒▒▒▒▒╢▒▒▒▒▀░▒▒▒▒▒▒▒[/color][color=#523a15]█[/color][color=#56552b]▄▓[/color][color=#516848]▒▒▓▓▄▒[/color][color=#696258]░Ñ▒▓▌░▒▒▒▒▒▒▒▒▒▒▒▒[/color]                                                                                                                                                                                                                                          //
//    [color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒░▒▒░▀[/color][color=#432f3b]▓[/color][color=#54354b]▓██[/color][color=#6f685d]▒[/color][color=#70695e]▒▒▒▐[/color][color=#321a10]█[/color][color=#633b25]▓[/color][color=#526948]▒[/color][color=#5a734f]▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒[/color][color=#755813]▓[/color][color=#654304]█▌▀▓[/color][color=#5c744f]░[/color][color=#5f7a54]▒▄[/color][color=#724f09]▓[/color][color=#473d2e]▓▓▓[/color][color=#605441]▌[/color][color=#686157]░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒[/color]                                                  //
//    [color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░▒▒▒▒▒▒▒▄╥╫▒▒▒▒▓[/color][color=#692716]█[/color][color=#181911]█▓▓[/color][color=#58714e]▒[/color][color=#5f7a54]▒▒▒▒▒▒▒▒▒▒▒▓[/color][color=#5f511c]▓[/color][color=#475334]▓▌[/color][color=#546c4a]▒▓▓▒▓▓▓▓▓▓░[/color][color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒[/color]                                                                                                                                                                                                                                          //
//    [color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒░▒▒▒▒▒▒▒░▒▒░▒▒▒▒▒║▒▒Ñ╥║",,╣▒▒▒▒▒▒║▒║▒▒▒[/color][color=#3c4c33]▓▒▒▒[/color][color=#48401a]██▀▒▌▌▀[/color][color=#bd1a5e]▒▓▓[/color][color=#5e5551]W[/color][color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒▒▒[/color]                                                                                                                                                                                                                                                                                                               //
//    [color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒░▒▒▒▒▒▒▒░▒▒▐▒▒▒╢║▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒║╜▒▒▒▐▐[/color][color=#3d3a23]█[/color][color=#66541a]▓▀▓▀██▓▓▓▀[/color][color=#70695e]▒[/color][color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒▒[/color]                                                                                                                                                                                                                                                                                                                                      //
//    [color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░▒▒▒▒▒▒▐▒▒▒▒▒▒▒▒▒▒▒▒▒▒░[/color][color=#403534]▓[/color][color=#5d4637]▌[/color][color=#7e6447]▒▒░▒▒▒▒▒▒[/color][color=#687c5c]║▒[/color][color=#37452e]▓░[/color][color=#465538]▐▓▓▓▀▓▄▓▒[/color][color=#5b5151]░▒[/color][color=#6e675c]░▒▒▒▒▒▒▒▒▒▒▒▒▒▒[/color]                                                                                                                                                                                                                                          //
//    [color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓[/color][color=#5f4b35]▀[/color][color=#644b36]▀▓▓▓▓▌▒▒▒▒▒▒▒▒[/color][color=#687c5d]║░▄▓▓▓▒▓▐▓▓▌░▒░[/color][color=#6e675c]▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒[/color]                                                                                                                                                                                                                                                                                                                                      //
//    [color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▀▒▒▒[/color][color=#49432f]▓╬▒[/color][color=#5f523a]▓▓▓▓▓▓▌[/color][color=#5f7a54]▒▒▒▒▒▒▒▓▓▓▓██▓▀▓▌▄▒▓░░░▒░▒[/color][color=#70695e]▒▒▒▒▒▒▒▒▒▒▒[/color]                                                                                                                                                                                                                                                                                                                                      //
//    [color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░▒▒▒▒▒▒▒▒▒▒▒▒░▒▒[/color][color=#37412e]▓[/color][color=#38252c]███[/color][color=#5a734f]▒[/color][color=#5f7a54]▒▒▒▒[/color][color=#413929]▀[/color][color=#423325]▀███▓▓▓▌█▓▒▒▓▓[/color][color=#6c655b]░[/color][color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒[/color]                                                                                                                                                                                                                                          //
//    [color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒║║║║▒▒▒▒░▒▒▒▒▒▒[/color][color=#4b4f3c]▀[/color][color=#504339]▌▒▒▒▒▓▒▒▒▒▒▓▓▀███▓▓▓▌░░[/color][color=#6d665c]▒[/color][color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒▒▒[/color]                                                                                                                                                                                                                                                                                                                                      //
//    [color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░▒▒▒▒▒▒▒▒▒▒▒[/color][color=#7a4232]▓[/color][color=#7c3e30]▓▒▒▒▒▒▒▒▒▓▒▒▒▒▒▒▓▓█▓▀▀█▀▓▓▓m[/color][color=#70695e]▒[/color][color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒[/color]                                                                                                                                                                                                                                                                                                                                      //
//    [color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒[/color][color=#755712]▓[/color][color=#7d6024]▓▓█▓▓[/color][color=#695e4c]░[/color][color=#70695e]▒░░▀▀▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒[/color]                                                                                                                                                                                                                                                                                                                                      //
//    [color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒[/color][color=#91600c]▓[/color][color=#815506]▓╢▓▓▓▓▌[/color][color=#695e4d]░[/color][color=#6e675c]▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒[/color]                                                                                                                                                                                                                                                                                                                                      //
//    [color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░▄▄M▀▀▒[/color][color=#786024]▓[/color][color=#976211]╣▓▓▓▄▄▒▒[/color][color=#5f7a54]▒▒[/color][color=#5f7a54]▒▒▒▒▒▒▒▓▒▒▓▓▒▓[/color][color=#815705]▓[/color][color=#965f0e]╣█▓▓█▓▓▓▓╢▓[/color][color=#68563d]▄[/color][color=#665f55]░▒▒▒▒▒▒▒▒▒▒▒▒▒▒[/color]                                                                                                                                                                                                                                          //
//    [color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░▐▒▒▒▒▓▓[/color][color=#8b621c]▓[/color][color=#ac6d11]▓▓▓▓▌▓▀[/color][color=#5f7a54]▒▒[/color][color=#607752]▒▒▒▒▒▒▒▒▒▒▒▒▒▒▓[/color][color=#60531f]▓▒[/color][color=#855613]▓▓▓╢▓▓▓╢▓█▓▓▓▓[/color][color=#696050]░[/color][color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒[/color]                                                                                                                                                                                                                                          //
//    [color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒[/color][color=#655133]▓[/color][color=#605734]▓▒╫▓▒▒▒▓▓▓╢▓▓▓█▒▒▒▒▒▒▒▓▒▒▒▒▓▒▓▓▓▀▒▒▓▒▒▓╢▓▓▓▓╫█@▓▓▓╣▓▄[/color][color=#70695e]▒[/color][color=#70695e]▒▒▒▒▒▒▒▒▒[/color]                                                                                                                                                                                                                                                                                                                                      //
//    [color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒[/color][color=#604927]▓[/color][color=#72542a]▓▓[/color][color=#627450]▒▒▒▒▒[/color][color=#5f7a54]▒▒▒▒▒▓[/color][color=#723b1c]▌▒[/color][color=#6c500e]▓▌[/color][color=#5f7a54]▒[/color][color=#62734f]▒▒▒▒▒▒▓[/color][color=#88511d]▓▓▓▓▒░╫▓▒▓▒▒[/color][color=#5d3429]▓▓▓▓▓▓▓▓█▓▓▓▓╢▓▓▓▌[/color][color=#6e685d]░[/color][color=#70695e]▒▒▒▒▒▒▒▒[/color]                                                                                                                                              //
//    [color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒▒▒[/color][color=#5c4b31]▓[/color][color=#6e502b]▓▓[/color][color=#5f7a54]▒▒▒▒▒[/color][color=#5f7a54]▒▒▒▒▓[/color][color=#443930]▓[/color][color=#422e2c]█▒▒▒▀▓▓▄▒▄▓▓▀▓[/color][color=#5f7953]▒[/color][color=#5f7a54]▒▒▒▄▓[/color][color=#613d29]▓[/color][color=#354746]▓▀[/color][color=#5d744e]▒▒▓▓▓▓▓▓▓█▓▓▓▓▓▓▓▓╣▓▓[/color][color=#70695e]▒▒▒▒▒▒▒▒[/color]                                                                                                                                              //
//    [color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒▒▄[/color][color=#4a3d1d]█▒▒▒▒▒▒▓▒▒▒[/color][color=#424a39]▓▓[/color][color=#a39029]▒▒▌▒▒▒▓▓▓▓▒[/color][color=#5f7a54]▒▒▒▒▒▒▓▒[/color][color=#453828]▓▀▒▓▓▒▒▒▒[/color][color=#6b4a2e]▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓╢█[/color][color=#6f685e]▒[/color][color=#70695e]▒▒▒▒▒▒▒[/color]                                                                                                                                                                                                                                          //
//    [color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒▒[/color][color=#654a1f]▓[/color][color=#4e4726]▌▓[/color][color=#686849]▒[/color][color=#5f7a54]▒▓▒▒▒▒▓▒▌▒▓[/color][color=#333426]█▒▒▒[/color][color=#8b6404]▓[/color][color=#b17c00]╫▓╣▓[/color][color=#546747]▒▓▓▓▒▒▓▓▓[/color][color=#556545]▒▒▒▒▒▒▒▒▒▒▒▓▓[/color][color=#ac6d11]▓▓▓▓▓▓▓▓▓▓▓▓[/color][color=#76480b]█[/color][color=#686157]░[/color][color=#70695e]▒▒▒▒▒▒▒[/color]                                                                                                                       //
//    [color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒▒[/color][color=#615035]▐[/color][color=#85540d]▓▓╜▒▒▒▒▒▓▓▒░▒▒▓▒▒▒▓▓▓▓▀▒▒▒▓▀▒▒▒█▒▒▒▒▓▒▒▒▒▒╫▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░[/color][color=#70695e]▒[/color][color=#70695e]▒▒▒▒▒▒[/color]                                                                                                                                                                                                                                                                                                                                      //
//    [color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒▒░[/color][color=#905d11]▌[/color][color=#ac6d11]▓█▓▓▓[/color][color=#5f7a54]▒[/color][color=#617551]▒▒▒▓▓▒▓[/color][color=#743e27]▓[/color][color=#5f412d]▌[/color][color=#617551]▒[/color][color=#607953]▒▒▓▓░▄▓[/color][color=#37403a]▓▒▒▒▒▒▒[/color][color=#503f32]▌▒[/color][color=#63724f]▒▒▒▒▒▒▄▓▓▓▓▓▓▓▓▓▓▓▓▓▓╣▓▓▓[/color][color=#6b655a]░▒▒▒▒▒▒▒[/color]                                                                                                                                              //
//    [color=#70695e]▒▒▒▒▒▒▒▒▒▒▒▒▒▒░[/color][color=#925e13]▓[/color][color=#7a4c0c]▓▓[/color][color=#63724f]▒[/color][color=#646f4d]▒▒▒▒[/color][color=#513529]▓▒▒▒▒▓[/color][color=#313d3a]▌[/color][color=#526e4f]▒[/color][color=#656e4c]▒▒▒▒[/color][color=#603924]▓▓▒▒▒▒▒▒▓▒[/color][color=#414531]▓▒[/color][color=#696648]▒[/color][color=#5f7a54]▒▒▒▒▓▓▓▓▓▓▓▓▓▓▓▓▓▓[/color][color=#7a4e0e]▓[/color][color=#5f5022]▀▓╢╣█[/color][color=#655f55]░[/color][color=#70695e]▒▒▒▒▒▒▒[/color]                                                  //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             //
//    [/font][/size]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract TDAI is ERC721Creator {
    constructor() ERC721Creator("Treeple Dreamers AI", "TDAI") {}
}
