// SPDX-License-Identifier: MIT OR Apache-2.0

pragma solidity ^0.7.0;

import "@openzeppelin/contracts-upgradeable/proxy/Initializable.sol";

import "./mixins/roles/AdminRole.sol";
import "./mixins/roles/OperatorRole.sol";
import "./mixins/CollateralManagement.sol";
import "./mixins/WithdrawFromEscrow.sol";

/**
 * @notice The CRNFTToken treasury which collects fees generated by the market.
 * @dev The core responsibility of this contract is collecting fees.
 */
contract CRNFTTreasury is AdminRole, OperatorRole, CollateralManagement, WithdrawFromEscrow {
    function initialize(address admin) public initializer {
        AdminRole._initializeAdminRole(admin);
    }
}