
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: NATOSHIME
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    :ccccccclllollooooddddddxxxxkkkd;';x0OOOOko,';cdkOO0KXNWMMWWNXKKKKKKKKKd'.;kXNXOdc:,'...,cokko,.:dxdc:::ll:c:,;,,'',,,,,,,,,,;clx00kdoloddol:;;;;;;;:lodkKNWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNNNNNNNNNXXXXXXXXXXXXXXKXXXXXXXXKKKKKK0KNWWMMWNXXKKK000OO000000OxdOK0OO00OOOkkkxxxxxxxdddddooooollooolllllllllollcc    //
//    :cccccllllllooddooodxdxxkkkkkkkl,'cOK0OOkl,':ldk0KXXWWMWNXXKKKKKKKKKKKk:;d00xl;''''...',:lol:'';c:::;;;:cc:;;;;,,'',,,,,,,,,,;;:oxxdolc;;:;;;;;;;;;;;;;;;lxO0KKXXXNNNNWWWWWWWNNNWWWWWNNNNNNNNNNNNNXXXXXXXXXXXXXXXKKKKKXXXXKKKKK000KXXNWWMWNXK000000000OkxxO00OOO00Okkkkkxxxxxxxxxddxxdoooddoooollllolllllccc    //
//    ccllllllllloodddodddxddxkkkkkkxl,'cO00Oko,':oxOKNWWMWNXKK000KKKK0KKKK0l:dkoc:clodl'...,:::;'.',;,;ccccokKXKK0Oxoddddxddddxdoccdkkkolc:;;;;,,;;;;;;;;;;;;;;:cclodxxkkkxkO0KNNWNNNNWNXXWNNNNNNNNNNNNXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKO0KK0KKXNWWWWNXK000000Oxk00OOOOOO0Okxkkkkkkkkkkxxxxxxdddddoddddolooollllolcc    //
//    clllllllooooodddddxxxxxkkkkkOOkl,'lO00Ol'':oOXWWMMMWWNNNNNXKKK000KKKOo;lOO0XNWNN0c...'''......'',cdkO0XWMMMMWWWWWWWWMMMWNWWWX0KK0Ododool:;;,,,,;;;;;;;;;;:d000Okk0KKKkxoccoxKNNNNNXKKNNNNNNNXXXXXXXXXXXXXXXXXXXXKKXXKKKXXKKKKKKKKKKKKK0000KXWWWWNXK00OkkO0OOOOxxkOOOkkkOOOkkkkkkxxxxxxxxdooddddoodooooooolll    //
//    lccllooooloddxdddddkkkkOOOOkkOkl,,lkkkl',lkXWMMMMWNNXXXXNNWWNXK00K0kc;dXWMWWWWNXO:.............':kXNWMMMMWWNX0kOXWMMWWN0kOXXNKkollccccc::;,,,,,,,,,,,,;;lkXWNKxllodxOkdc;,,:o0NNNNXKXNNXNNNXXXXXXXXXXXXXXXXXXXXKKKKKKKKKKKKKKKKK0KKKK00000000KNWWMWN0xx0OOOO0OkxkO0OOOkOOOkkkkkkkkxxkxxdxxxdddddoooooollllll    //
//    llloooooddooxxlcodxxxkkOOkOkxOko:,ckkl:o0NWMMMWNKOOkkkkkO0KXWWNK000kclONWWWWWWWNXkloddc'.......,oKWMMMMMWXd::;,:oO0kxoc;':doll;,,,,,,;;,,,,,,,,,,,,,,;:o0WMMN0dc:cloxko::lkKXNNNNNXXNNNXXNXXXXXXXXXXXXXXXXXXXKKXKKKKKKKKKKKKKKKKK00K0000000OO000KNWMWNXK0OOOOOOOOOOOkkkkOOOOOkkOOkkkkxxxxdoodxxddddoooooodol    //
//    olloooodolccllccdxkkkOOOOOOO0Oxl;,lOOkKWWWWWWN0xdkkkkxxxxxkk0XWWXK00kcc0XKXNXK0XNNXXOkl,;'.'...:kNMMMMMWNO:.',,;cl:,''''',;,''',,',,,,,,,,,,,,,,,,;lxOKNMMMMMWKdllcccc:lONWWNNXKKXNNXNNXXXXXXXXXXXXXXXXXXXXXKKXKKKKKKKKKKKKKK000000000000000000O000KNWMWNK0OOOOOOOOOOkkkOOOOkkOOOOkkkkkxxdodxxdddddddddddooo    //
//    loooooooooodlc:clloodddxkkkxkOko::kNWWWNXXNWXOxxdxxddddxkkkkkkKWWX00O:.;c:oo:,';lcxKKKOxc'....:kNMWWNXKOkl'...',,;;,,',,;;,,'''''''',',,,,,,,,,,,;l0NWMMMMMMMN0kdlc:,,cOWNNNNNXKKXNKXWXKXXXXXXXXKXXXXXXKKXKKKKKKKKKKKKKKKKKKKK00K000000000OOO0OOxoxO0KXWMWNX0OOOOOOOOkkOOOOOOOOOOOOkkkkxxkkxxxxxxdddddooodol    //
//    loooooddddxxkooxklcloloddddodOOkkKWWNKOOOXWN0kxkkkkxxddxk00OOOOXWNK0x,  .....',,;:lkXNXkc,...'cod0Oxoc:;;,'.',;:c:;,'..........'',;:::::;:;;;,,,:d0NWMMMMMMWXOoooc;,,:kNWNNNNNXXNWXKNNKKXXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKK0000000000000OOO0OxloO0OOO0KNWMWXKOOOOOOOkOOOOOkkOOOOOOOOkkkkxdxxkxxxxxdddddxo:    //
//    coooodooooxxdllxdoxOOkkxddddx0XWWN0kdxkOOXMNK0OkkxkkxxxxkOkkkO0XMWWXo..;:l::ldxkOOlckXXXKkxxxo;':xOOOo:;;,'.'',,,...    ...... ...,:ldxxdddoooldkXWMMMMMMMMMWX0Odc,',dXNNNNNNNNNWNNNNXKXXXXXXXXKKKKKXXKKKKKKKKKKKKKKKKK0KKKKK0KK0000000000OOOOOxkO0OOOOOOOKXWMWNK0OOOkkkOOOkxkOOOOOOOOOkkxkkkkxkxxxxxxddddl:    //
//    odolododdoxko;cdllxOOOOkxxO0KNWNOl:cok0XNWMWWNNXXK00OOOOOO00KKXWWNWWx:dKXX0OOOdc;:,.;xdxK00OxoccxKX0x:..........  ...................,:lllollloxkO0KNWWXKKNNNWWXOd;';kNNNXXXXNWWWNNXKKXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKKK0K0OO0000000000000OOOxxOOOOOOOOOOkOOKWMWNK0kkkkOOOkkOOOOOOOOOOOkkkkkkkOkxxxxxdodxdo    //
//    ddoooxddxdxx:;od:':xOOkdxKNWMWX0dccld0NWWMNOdooxxkO0KXNWWMWWMWNKO0NWXKXKKKxc;,'......,;:l;',,:cldoll,..','...   ..'''''......'',,'...  .',:lllllc::clooc:lk000KOxoc;:xKNNXXXWWWWWXXXKXXXXXXXXXKKKKKKKKKKKKKKKKKKKK00KKK000K0000000000000000OkxkOOOOOkkOOkxkkkO0XNWWNX0kkOkOOOOkOOOOOOkkOOkkkkkkkkkkkkxxxxkkx    //
//    dxxdodxdddkd:cl::;:xxdx0XWWWX0OkkxlokXWMWNx,..... ...,;clllcc:;oKWWWNX0kxc...',,'...........'''............  ...''...........',ox:.',.. .,:oOXX0xc;;;;;;cloollodxkkdcdKWNNWWWWWNXXXXXXXXXXXXKKKKKKKKKKKKKKKKKKKKKKKKK00000000000000OO00OkkOkxkOOOOOkxkOOOkxxkOkkOKNWMWX0OkOOOOOOOOOOOOOOOOOOkkkOOkkxxxkxxxxx    //
//    oddoddoodkkl:l::dl:ldOXWWX0OkkkkkdloONMWKo,....   ........    ,0WWNNXX0d,.  .......... .......''.........  ............'.....;:';;':o:. .lkKNXXN0Odlc;;;:ccccc::clo:ckNWNNNWNNXXXKKXXXXXXXKKKKKKKKKKKKKKKKKKKKKK00K0000000000OO000OOO00OOkxxkOOOOOOkOOOOOkxdkkkkOO0KNWMNK0OkOOOOOOOOOOOOOOOOxkOOOOkkkkxkxdxk    //
//    dddxdlodxOxclo;cxolxXWWNKkkOkkOkxooxONWOc;;,...  .............cNWNNXXKx;...       .................'....,:,,;'.   .;oolxdxOk;.'....l0x'.:0K0klcolllllccll::;;'''',;:d0KKXXNNXXK0OOOkkkxxxddddxO0000000000000KKKKKK000000000000000OOOOO00OkxkOOOOOkkOOkOOkkkkkkxkkkkkOKNWWNKOkkkkOOOOOOOOOOOOOOOOOO0K0Okkkxkk    //
//    xxdolloddxdodl,;dk0NWNKkddkkkOOkddxx0WKc.''........  .......  ;KXkdkKK0kOk,               .....'''''';oOXXOkOxlcl:,dWMWXxo0k'......';'.;OKko:''''',::;;:;;,'''';ldk00K0KK0K0kdooddxxkOOOkdl::cloddodollddloxO00000000000000000000O000OOOOOOOkkOOOkkkkxxkxkkxdkOkkxkkxxk0NWWNKOOkOOOkkkOOOkOOkkOO0KXXX0kkkOOO    //
//    ddodxdodollolc;:OWWXkdddxdxOOOOkddddKMO;........ ...    ....  .dXl;x0KNXKx,..',,,..   ....,ldxc,',:oOXWWWWWNNNxoK0okMWNXd,::........  .;::;,''....''''''',''.'l0000000OO00OkkkOO0KKXXXXXKKOxkOkkOkOOkxxdlccloxk00000000000000000000OOOOOOOOOkkOkOOkkkOkkOkkdldkkkkkkkkkkkKNWWN0OOOkxxOOOOOOkxkOOKXKKKOxxKK00    //
//    oldxxxkxxxc:cokKWW0c,:oxkddkOOkkxddONNl.......... ..     .     .x0xox0KKKOxx0KXXKOo;,;:::o0N0c',:::;:llox0NWWWkxNWKKNXOl,.......   .......'....',;clcloodo;',l0XK000KK0KXKKXXKK0kO00KKKKKKKKKKKKKKK00KK0OkOOkdodkOO00000OOO0000OO00OOOOOOOkkkOkOOkOkkkOOOxdl:oOkkkxxkkxdxk0XWMWX0OOkkkOOkkOOOOO0XXKKKOdkXK0k    //
//    xodxxxxxkd::xXWWXkl;,,cxdooxkkxxkkONM0,   .....'.... ..    ...  .xKc,:cd0000OOKXXX0kkk0KKNNO;.,,.........;lx0XKKXX0dl:...     ...............';ldxddddddxkxdxxdddkxoxkO0OO000KKOxOkOKKKKKKKKKKKKKKKK0000000000kdodOO000O0000000OOOOOOOOOOOkkOOOkkkkxkkkkkddxddkkkkkkOOkkkkkO0XWWN0OkxkOkxkOOkkO0K00KKOxOKK0k    //
//    dodooddkkdokNWNOlcol;,:ccldxxxdxkONMWx.    ............    ..    .xx'  .......',;,,'.,:lxol;...............';:;:;'..   ................'',;:coxkxddooooodkkxddxxdl;'oKK0O000KK000000KKKKKKKKKKKKKK0000000000000OdlokOOOO0OOOOOOOOOOOOOOOOOOOOkkkkkxkOkkkkxoclloxkkxxxkkkkxkxxx0NWWX0OOkkkOOkkkOKK000OOk0KKK0    //
//    ddxdodxkkONWWKo;,;:lc;,':looddood0WMK:..  ...        ..    .      ,kl.       .   .......... ..............   .  ..................',,,:okO000Okdoddxxdddodkkdc:,.':dOXXXXKOOOOO000KKKKKK00000K0KK000000000000000OxccdkOOOOOOOOOOOOOOOkOOOOkkkkxxkkOOkkkxxdclolodxxkddxxxdxkdddx0XWMWXOkkkkkkkO0XXXK00Ok0XKK0    //
//    xkOkolx0XWWXOxo:;;;:c;',:;;cloxdd0WNo..........       ..   .      .cx;...   ........... ..............................''',;,..''..co,.,:clodxxxxxkkxxxxdol:,.....lXNXXXKKOkxOO00000KKKKK0xdk0000000KK000000000000OkocokOOOOOOOOOOOOOkkkOOkkOOkxkkkkxkkxddoodoodxdkkkkkxdxxdoddkkk0NWWNKOkkkOkOKXXXKK0kkKXXXX    //
//    ddxkdd0NMWKxoll:,;::cl:,,,,:colclOWNo.......'...       ..         .c00Okd:'',,,'..       ..  ..............',:cloo;cdO0dokdc'.'...,,..''.',:dxkkxkO0Okkxl:'.....;ONXKKKK0OkkOO000O0KKKKK0xkK0OO000000000000000O00OOkc;okOOkkkOOOOOOOOOOOOkkkkkkxdxkxxkkxoloooxdodxxxxdloxxloddkkkkOXWMWXOkkkkkxxO00OkdxKXXXX    //
//    xkOkkKWMWKxdlclc,;,.':,';;,:loolcdXWk;.....,,...              .   'xXXKXKkoodkOkdc;,;c:;;.  . .....,;cooxO0KNNWWKl:xXK0OOKOo,.'';,...;;,.',;ldkkkOOkkddol;...'cdOXXXKKK00OkkOO0000O0K0KK000000000000000O00OOOOOOOOOkl,;cloxkkkOkkkOOOOkkkxddxxkxodkkxxxxxxdoolcc;cccoolooooddxkkkkkO0NWWN0kkkOdcldxoclxxx0KK    //
//    kkO0XWW0Oxolc,';::;.';,;;;;:loodooOWNd...........       ....     .oK0xx00o,,;co:,colloxdol,',;cldk0KXNNNNNNNWWWXl:oxxl,,:ooclddoc,,lk0d:'',:clxkkxkkdodoc,...lXNK00KKK00K0OkO0000OkO00000kxkO0000OxxO00OOOO00OOOOOOOl'',,cxkOOOOOOOkkOxodOkkkkkkxxkxkxodxxxdl:::;clcllc:ldxxdxkkxddxkOKWMN0kOKXKOOkl;d0klcll    //
//    kOKWMN0dxoldl;,;;;;;::::;::;llclodx0WXo'.... ..       .....     .;OXOdxKNKl,,;:'.;:,,,oo:okddOKXNNWNXXXKKXXXNWWKc;::cc,'',lOxll;..;okko:,:oxkOOxoolclc::;'..;ONX000KK000K0OOO000Oxk0K0000OOOxlclol;,:lolllllllllllll;....;clllllllllllc';ooxkkkkxdxxddxdodxolooooool::coodxk0K0kxodkxoxKNMWXKXXXK0d,;kKXKOkx    //
//    0XWWN0dodddoc;;::::cc::;;;;::ccodold0WNx,.....       .....     .'l0Xkxk0KK0xollccccccloolkKkx0XNWWNNXXXKKXXXNWW0;.;,.....'cd;......,kX0kxkKNKKkc,,,,''.'....dXXK0O0KK00KKOkkOO00kxO000OOOO0Oxl.                                         ,lldkkkkxxxdxxxdooddddoolcol:cdl:;:kXKOddxkkxkkO0NWWWNXXKOl'cOKXXX0o    //
//    NWMXOkdooodo:;:::;:olc;,clc;,:loc:coxKWWOc''..        .        .,oO0kk00000KK00OOOkxxdodOKXOOXNXXWNXXXKKXKKXKXWXocxl.....';c:......,kNNWWXKXXOc'',;::;;,...;0NXKOOK000KK0kxkOOOOxk000OOO00000k,                                         :xkxxxxxdodxkxxxxololloc;;ccoxddocl0XKOdldkkkkkkkOXWMWNXKkc;o0KXXKk:    //
//    MWXOxolodddooxl:::;;::,',::;:;,;:ododkKWMXo'..                  ,xxoldkO00K00000OOkkkxxOKXX0KNXXXXXXKKXKKXKKKXKXXKOo,....,d0d',clld0NX000OKX0x;,;;,,;:::,..dXXK0OOOO0KKKOxxkOOOkxO0OOkO000000k,                ..                       :kkkkxxkdlodxoldxdodxxo;,:ldxdddlcxKXK0kddxxkkkkkkkKWMMNOl,,oO0XXKk;    //
//    WKxxoloodxolool;;c:;,,,,',;:c::;;cloxooONWWO:..                 'dkdodOO0KKKK0000000OkOKNNXXNNXKKXKKKKXXXKKKKKKKXNWK:...cONO;.,xXWMWWKd:,:kKKd;;;,,;;;:::';ONKKK0O0KKK00OxxkOOOkkOkkkO000OO00k;   ..... ...    ,l:...            ...    :kkkkxkxl:::codxxxkkkxocldolllodooOXKK0Odoxkkkkkkkk0NWMWKxlcdxkKKkc'    //
//    Kkxxxxxooddoolllcol:;';;'.,::;;:clodxodddONWO:..                .o0xxkxxdk0OO000000000KXNXXNNK0KKKKKKKKKKKKKKKKKXNWXl..;xO0o. .;ONKXWKdlo0XK0o;,;,,,;:::;,lKXKKK00KKK0OOkxkkkOOkkOOO000OOOOO0k:   ;occ:,..c,   c0x';,   ..':' ....,:.   ;xkxkkkdolc:cldxxxdddddodxoccloddkKXK0ko:;okxkxdkOKXXXNWMWXkokXXX0c.    //
//    kkxxxkkdodoooollc::,.';::;,,',:collllodolokNWO,                  :Oc...  ,xdoO00XXXNXXKKKXNNN00KKK00KKK0KXKKKKKKKXNNKkkKNNKo'.'lO0dxXNXNWWXKKd;,,,,;;:::;;xXK0000000K00OkxkkkOOkkO00OOO0OOOOOk:   ,;;c,;c:l,   :olod,  .::cdc,;' .'.    ,xxdxkkxdo:cdllxxxkxdoodxdlloodxxOKOxl'..,xOkkkxxOkx00x0WMW0ldXXXKoc    //
//    odkxdkxooodooc,;:,...,;:oc'';:,,,;;:llc;lodOKN0:                 ,Od..  .ckkkKXNXXXKKKKKXNNNN0OXKK00KKKKKKKKKKKKKXXNNWWNNNXOkO0NNXXXKNNNWNXKXk:,,,,;;;;;'c0K00K00000000OxxkkkOOOOOOOOOOOOOOOOO:   .. .  ...    ..'::;.   ...            'oxxxxkxollodoloodddxdooll::loddddxkdlccloxkkkxxkkdodxlcOWMXdoxddlxK    //
//    xxxxxxdodxoll;,;::'.,;;cl;;:cc;'.',;;:;;cloddkXXo.             ..;0Oc:::cdk0XNXK0KXNNNNNNNNNXOOXK00KKKKKKKKKKKKKXKKXNNNNNNXXXXKKXXKKXXXNXXXXXOc.',,,;,'.'dK000000000000kxxkkkkkOOOOOOOOOOOOOOOc.                                        .lkkxdddddddddoc:cllddccllclloooooxKXXKko:cdkkxddoddc,,:oXMMW0xd;.cK    //
//    kddddxxdxxolc;,;:;',,::;;:ll;,,,,,cc::clloooc:xXWO;        ..   .oKx:::::cxKWXO0XNNNNNNNXXXXXKKXKK0KK0O0XKKKKKXKKKKKKXXXXKKKKKKXKKXKKKKKXXKXNO:.',,,'...:OX00000000000OkxkkkkkkOOOOOOOOOOOOOOOc.                                        'oxdddooooddddllc::lddoc:ldooddolookKXX0koccoo:codxxc.lkokNWMWXOo,'l    //
//    kOkdoxkdooc::;,::'';,;;;cloo;',lllll:cooodol::dO0NXo.     ....  ;0k,,;cc,,kNOoxKNNNNNNNXKKXNXXXNXK0000kOXXXKKKKKXKKKKKKKKKKKKXXXXOo:;;:lkKXKkl,..,',lkkkOKK00000000000OkxkkkkkkOOOOOOOOOOOOOOOl.                                        .oxxkxlllcooododdl:codo::loooddoollx0XXKKOxl:,;odldl'.cklo0NWMWK0k:.    //
//    kkkxdxdoodl:;;lc,.';,;cc;,;;'.,:c;;:::clclolclolco0NO;  ........;00l:::;;x0dlxKNNNNNNXXK0KNNXXXNXK000000KXXKKKKKKKKKKK0KKKKKKXXXXKOkkxddxkl,....'''oK000OOOOO000000000OxxkkkkkkOOOOOOOOOOOOOOOl.                                        .oxddddxdoc:clcllloc:cllcloddddooldxOKXXK00Ox;;kkolc..,lc:xKXWWNOo:'    //
//    kkkdoddolll::ccc;,,;:cc::,,'..'::;cl:;:lcccllc:;cld0NXx;..      .lK0o;:xK0llOXNNNNNXXKKKXXNNXXXNXK00K00KKKKKKKKKKKXXKOxxOKKKKKKXXNNXkl:,'.......,;o00OOOOOOOOO0OOOOO0OkxxkkkkkkkOOOOkkOOOOOOOOo.                                        .okxdxxxdddxdoclcclc;':c:looodooddxxk0XXXKKKOlcxklcc,..,,;looddOOkk0    //
//    kxddoodddo:,:lccc:,,:ccc:,,...':c:::::::ccclc;.;c:ldxOKKkl'.    .'dKOkKW0ooOXXXXXXXKKKXNNNNXXXXNXKKK00K0KKKKKK00KKKK0kl:dkxxkOOOOOko;'.   ...''':x00OOOOOOOOOO0OOOOOOkxdxkkkkkkkkOOOkkkkkkkkkOo.                                        .lkkkkkkkdoodooooollc,;lloolodlodxdddkKXXXXX0ooddoool:;:ccoxloOXNNX0    //
//    dldxdolodc;;cllclc:ldoolc;'...,:c:,,,,;::;:c:,;:,':lolokKXKx:.  ..;kKKNKxkKKKKKKKKXXXXXXNNNXXXXXXXK0KK00K00KKKKKKKK00K0Okdlc::;;,'.'';......',;lk00OOOOOOOOOOOOOOOOOkdddxkkkkkkkkkOOkkkkkkkkkko.    .,   .'     ..  . .,    '.          .cxkkkkxxdllddxxxxdl;:llclccoxdoddoodxOKXXXXxcdxodocolcllldkxx0XXKOx    //
//    xxxdoddlllooddocclllllll:,....,;cl;'';:,,;,..;;,,;:ldxxodx0NXko:. .oKX0x0KOO0KXXXXNXXXXNNXXXXXXXXXXK00K000000KKXKK0000KKKK0Oxl;'...........';lxO0OOOOOkOOOOOOOOOOOOkxddxxkkkkkkkkkkkkkkkkkkkkkd'    .c;  ;o:.  .c' .; ,l.  .c.          .cxxxkkxkkxxkxxxddxdcooolccclooooodxxxxkkkxocl0OoooodxxddxddxOO0KKKK    //
//    kxxxdxdoodxddxxddol:;ccc;,,'..,:c:'','.,;;;;;l;,:cccoolcodxO0kdxl..oNKk0KOkOKXXXNNNXXNXXXXXXXXXXKXXK00000000000KKKKK0KKKKKKXKxc'..........';dO0OOOOOOOOOOOOOOOOOOOOxoodxxkkkkkkkkkkkkkkkkkkkkkd'     ,d;:l',c..:,  'c.,d.  ,o'          .ckxxkkxxxkkkkxdollllclool;,lddoodxxxkxoloooxOOolkOdodxdkOOxxkkkKXXX    //
//    kdxxdxdooddoodoolldool;,,;:,',;:;,,,,;;:cclccc;;ccclolldxxxddOxoo,;0NKKKK0KXXXXXNXXXXXXXXXXXXXXXKKKKK000000K00K00KKKKK00KKXK0o,...  .....';oO0OOOOOOOOOOkOOOOOOOkkkoloddxkkkkkkkkkkkkkkkkkkkkkd'      c0O:  ':;.   .;.'dc..:x;.          :xdxxxdodxkxddooc;:oddool:cllc:ldxxxxxdx00kxdddk0OxdxddxkdodxOKKKXX    //
//    kdodddddddxddolllodoc;,:cllccc;,',,,cc;,;cc:c:;:ll:coddoxxdxxxdol;oKXXK0KXXXXNXXNXXXXXXXXXXXXXXKXK0O000000000K00K00KK0KK00K0kl,........,;cdOOkkkOOkkOkkkOkkkkOOOOkkdloodxkkkkkkkkkkkkkkkkkkkkkx,      .;;    ..     .  .,...,,'.         ,dddkxxodxdoc:ll;:lkkxddddol:;cddddddxxxk0XXXKK0000OOkdk0OOKOlclokk    //
//    kxodxdxkxdxxxdddoolc:ooloc::;;'.';;:oc:loc,,:;;,;clodxddxodkxxxxolxKXXKXXXXXXXXXXXXXXXXXXXXXXXXXKKKOkxxkOkO0000000K00K000000Odl:,....;codkOOkkkkkkkkkOkkkkkkOkxkOOkxoooxxkkkkkkkkkkkkkkkkkkkkkx,                                         ;xkxxkdlodddooolldxddddxxddoloxxxddxkxodxk0KK0Okx0K0OddOKKXXk;ck0Ok    //
//    kkddkxdxkxdddddlooccool;,,,'.,;,:c:::cccll:;,..,:lodddxdddxxxollclk0KXXXXXXXXXXXXXXXXXXXXXXXXXXXKK0kxoooooddk000000000000000K0ko;..';lxOOOkkkkkkkkkkkkkkkkkOOkkkOkkkxodxxkkkkkkkkkkkkkkkkkkkkkx;                                         ;ddolllllllccolldddxxxddxdddddodxxxdxxdxkkkOKK0OOKXKOkO00KKKxd0XXKK    //
//    kkxxxoodddxxxxxdooooll:,;:;,.';:c:;:::::;:l:;:lc:lc:clooxxdl;;cccx0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKK0kooollclldk000000000000000Od:',lxkOkkkkkkkkkkkkkkkkkkkkkkkOOkkkkxdddxxkkxxkkkkkkkkkkkkkkkkx;           .,.     ....                  ,oxxdl:;;;::looodxoodxxddddddddxxxxxdxkxxkkkOKXKKXXXK0000KX0dxKXK0O    //
//    ;cldddxxddddolodlcllooc:;;::,,,,;;:c,;c::clc:lolldllddodxxo;,oxdkKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKK0kdollc:::clodxkO0000000OOkdc::oxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxddxxkkkxxxkkkkkkkkkkkkkkkx:          .dOO:   .::..                  ,dxkxxo:,';cldodxxddxxxdodxxdxxdodxxxxxxxxkkkOKXXK0000KXXXOc.,kK0d:    //
//    .....';coodxdooocodol:cc::;;;'''.;c;:ccccloloddooxooxdddxkd:cdxdOKXXXXXXXXXXXNXXXXXXXXXXKKXXXXXKKK0Oxdolc::;,,;;:cloddddddxdoolcokOOkkkkkkkkkkkkkkkkkkkkkkkkkkOOkkkxxddxxkkkkkkkkkkkkkkkkkkkkkk:          .dkxo.  .lo.                   ,dkxxxc',ll:coddoodlodddxxxxddxxddxxxxxxxxkkkOKK00K0kodxdl,..;k0o'     //
//    ..........',;cc:,;lolc::;;,;,';;'',,,;cccooodxdoodooxxdodkd::dxxOXXXXXXXXXXXXXXXXXXXXXX0OKXXXXKKKK0Oxdolc::;;,''.';ccc:;;::;;;cdkOOkkkkxxkkkkkkkkkkkkkkkkkkkkkkkkkkkxddxxkxxxxkkkkkkkkkkkkkkkkk:           ,;,;.   ,c'..                 'dkxxo,.lxoloxxxdo                                                     //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract GNA is ERC721Creator {
    constructor() ERC721Creator("NATOSHIME", "GNA") {}
}
