
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Billy Dinh
/// @author: manifold.xyz

import "./ERC1155Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                //
//                                                                                                                                //
//                                                                                                                                //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM$=+$8DMMNDO$I+~,$NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMD~IDMMMMMMMMMMMMMMMNNO+~MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7~7ONMMMMMMMMMMMMMMMMMMNI=:NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN~ZNMMMNNDNNNNDDDDDDNDDO?~~~:=MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMD~~?ZOOZOZ$Z$$$$$$$Z$$7+~~=?+~==MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM=~==++???7I777I7I7777?~=7$O8O=$$MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMI7=~~~==++??777777II+??$O8D$=8NOIMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM$DO7+~~~~=+??IIII?++?I7ZZ$=INMMNIMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZNND8Z?+==~===+?++???II?=ZNMMMMMZ=+OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN8NMMMNN8ZI+=~~~+++++??+7DMMMMMMMD?====7MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO8NMMMMMMMMD$=~=+=?++?ZNMMMMMMMMMNO~~==+++IMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM~~=DMMMMMMMMMMMMD+==+++8MMMMMMMMMMMMDI:~~=====$MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM=~~~+NMMMMMMMMMMMMMMMN8MMMMMMMMMMMMMMMN8::~~=====+MMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM=~~~~:INMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMD+:~~~~~==+=MMMMMMMMMMMMMMMMMMMMMMMMMMMNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMD==~~~~~7NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNO=~~~~=====+MMMMMMMMMMMMMMMMMMMMMMMMMNNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8=~~~~~~=ZNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDI+~======++MMMMMMMMMMMMMMMMMMMMMMMMMMNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM======~==OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN$?======+++NMMMMMMMMMMMMMMMMMMMNNNNNMNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM++++==++?8MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM87I+++++?++MMMMMMMMMMMMMMMMMMMMNMNNNNNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM+++++++?IDMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8Z7II+??+++MMMMMMMMMMMMMMMMMMMMMMMNNNNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM=+++++?I78MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDO$$7III??ZMMMMMMMMMMMMMMMMMMNNNNMNNNNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM=++++II7$ONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNDOZZZ7777IMMMMMMMMMMMMMMMMMMMMNMNNNNNNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM++++??I7$ODMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMND8ZZZ$77IMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM=++??I$$ODNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNDOOZZ$$$MMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM=??II7$Z8NNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMND88ZZ$$NMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMI?I77$Z8DNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNDD8OOZMMMMMMMMMMMMMMMMMMMMMMNMNNNNNNNNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMI77$Z88NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDDDDOOMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN7$ZO8DNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNDD8MMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDOO8DNMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM?+I$Z8NMMMMMMMMMMMMMMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNZ+==$8DO7$NNNMMMMMMMMMMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMD=~?ODDNZ$MNNZ7NDMMMMMMMNM$?MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN~=7OO+~=I8NOOMMM8MMMMMMMNMM.D=MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM=:~=$I:+$DDDDNMD$MMMOMMMMMMMMO.~+?DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMNNNNNNNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:==::==7888Z~~=?OMOMMD$MMMMMMM?,:?I+DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOD=I$~=?~~+$DMMMNIN8MMMMMMMMMN:,I$$I+?MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMD8OM::=?INMMMMMMMNOMMMMMMMMMM??+ZZOZ7+=?MMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO7DDDNNMMMMMMMNMMMMMMMMMMMMNNDZD88OOZ$??+=~7MMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8=~7$8MDNMMMMMMMMMMMMMMMMMMMMNNNDNND88OOZ7I$+====~?DMMMMMMMMMMMMMMMMMMNNNNNNNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMD+~~~=+=O8ONMMMMMMMMMMMMMMMMMMMMNNNMMMNDD88OZ7$O=+======~~:INMMMMMMMMMMMMMNNNNNNNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO=~~======+~$DDMMMMMMMMMMDMMMMMMMMMMN8ZZDNNNNDDOZ$ZO++====+=====~+~INNMMMMMMMMNNNNNNNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMN===========+?+IODNMMMMMMMMMMOMMMMMMMMMN8$??NNNNNND8OZO7+?++?I+++++=II?=?$MMMMMMMMNNNNNNNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMO=+++===++===+I?+8DDNNMMMMMMMMMMMMMMMMMMNOZ7??MMNNNNND8OD7??7OZZ??I?+II+$77IINMMMMMMMNNNNNNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMDOM?DIZ===++?++???IDNNNNNNNMMMMMMMMMMMMMMMMMI?+DMMMNNNND8OD7I$8M8??II???8$7ZOI?IMMMMMMMNNNNNNNNN    //
//    MMMMMMMMMMMMMMMMMMMMMMMZII?M8$N7+++???I???ID8MNNNNNNMMMMMMMMMMMMMMMMMI7MMMMMNND8OZO7$DMDII77?D8Z78O$+II?$MMMMMMNNNNNNNNN    //
//    MMMMMMMMMMMMMMMMMNMNMM7O??NI$NOD?++???7ZI7I$8M8NNNNNMMNO8DMMMMMMMMM8NMMMMMM8NN8OZ8ZZ8MNZ77$?8Z8D7+8MO$Z$ZOMMMMMMNNNNNNNN    //
//    MMMMMMMMMMMMMMMMMNMNMD$$8N+OM$ON7?IIIIZZ7$~=DM8NNNMMMMO8DDMMMMMMM8?$OOMMMMM8NN8OZDZONMDZ$$$$M8Z7DMNZI7MZ$DNMNMNMMNNNNNNN    //
//    MMMMMMMMMDMMMMMDMNMMMO$Z$OMD7ONN8ZZ$IOOOO?I7NMMMMNM8N++++8MMMDMMNI?+INMMNDDNDD88OOZDMMD$ZOZDN8DMMDI8M$$DM8OMM8MMMMNNNNNN    //
//    MMMMMMMMDMMMNMMDMNMMNOM8$$8MM8ZNM88O$O8O$??ZNNNNMMNMM$?8DMNMMMMMNI777NNMMM8NDDD88ZDMMNDZ8DDDNNMNZDM8ZMMDD8DMDMMMMMMNNNNN    //
//    MMMMMMMMNMMNMMMMMNMNMMMDNNZ8MNMMMND88ODD??ZZONDMMNMMNMDDMNDNMMNMD7$ZDMMMMNN8DD8N88MMMNNDDNMNMMN8MONMM8NNNNDNMMMMMMMMMNNN    //
//    MMMMMMMMMMMMMMMNMMMNNNMNMMDMD8MMMMNDD8DO7Z8DNN8MMMMMMNNMMMNMMMNM8ZZ8MMMMNNNDNNDDNDMMMNNNNMNNMNMNMMNNMNMMMMDMMMMMMMMMMMMM    //
//    MMMMMMMMMOOOZOOODMMMNMZZOMMMOZZZMMMNDDM77$8NMMN8ZZODNNNMZZZOMMNMDOOZOZZOZNNDNNMOZOOMMMZZOMNNM8OOOMMZOZOMNMM$OOMMMMMMMMMM    //
//    MMMMMMMMM..... ...DMMM...MMM....MMMMNNM...?MMMMN... MNM:...8MMMMDDD .......+MMM?...MNN ...MNM+...MM,...NMMN...MMMMMMMMMM    //
//    MMMMMMMMM.  .......MMM...MMM....MMMMMMM...?MMMMMO.. OMM....MMMMMNNN ....... MMM?...MMM ...DMM+...MM....NMMM...MMMMMMMMMM    //
//    MMMMMMMMM....MM~...MMM...MMM....MMMMMMM...?MMMMMM....M....MMMMMMMMM . NM.....MM?...MMM ... MM+...MM,...MMMM...MMMMMMMMMM    //
//    MMMMMMMMM....MMM...MMM...MMM....MMMMMMM...?MMMMMMM ..... ~MMMMMMMMM ..MMM,...MM?...MMM ....,M+...MM....MMMM...MMMMMMMMMM    //
//    MMMMMMMMM...,M7...,MMM...MMM....MMMMMMM...?MMMMMMM~..... MMMMMMMMMM ..MMMM...DM?...MMM .....M+...MM...........MMMMMMMMMM    //
//    MMMMMMMMM........~MMMM...MMM....MMMMMMM...?MMMMMMMM ....8MMMMMMMMMM ..MMMM...8M?...MMM . ,...+...MM,..........MMMMMMMMMM    //
//    MMMMMMMMM..........MMM...MMM....MMMMMMM...?MMMMMMMMO....MMMMMMMMMMM ..MMMM...8M?...MMM ..M...,...MM,..........MMMMMMMMMM    //
//    MMMMMMMMM....MMM...=MM...MMM....MMMMMMM...?MMMMMMMMM...8MMMMMMMMMMM ..MMMM...DM?...MMM ..M$ .....MM,...MMMM...MMMMMMMMMM    //
//    MMMMMMMMM.  .MMM...,MM...MMM....MMMMMMM...?MMMMMMMMM...8MMMMMMMMMMM ..MMM....MM?...MMM ..MM .....MM,...MMMM...MMMMMMMMMM    //
//    MMMMMMMMM....M8....:MM...MMM.........MM.........NMMM...8MMMMMMMMMMM ..,......MM?...MMM ..MMM.....MM....MMMM...MMMMMMMMMM    //
//    MMMMMMMMM..........MMM...MMM.........MM.........MMMM...8MMMMMMMMMMM ........MMM?...MMM ..MMM~....MM,...MMMM...MMMMMMMMMM    //
//    MMMMMMMMM ........?MMM...MMM.........MM.........MMMM...8MMMMMMMMMMM........MMMM?...MMM ..MMMM....MM,...MMMM...MMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                                                //
//                                                                                                                                //
//                                                                                                                                //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract BILLYD is ERC1155Creator {
    constructor() ERC1155Creator() {}
}
