
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Dubious Luxury
/// @author: manifold.xyz

import "./ERC1155Creator.sol";

////////////////////////////////////////////////////////////////////////
//                                                                    //
//                                                                    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    ARTIFACTSMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMNOdooodONMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMWO:;cddoc,:xNMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMK:,kWMMMNk,;0MMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMM0,;KMMMMM0,,0MMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMO,,OMMMMM0,,OMMMMMMMMMMMMMMMOFMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMXc,OMMMMMk''xWMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMNl;0MMMMWx''kMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMKd0NKKKx:.:KMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMWNKKOoc:,,,,:dKMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMXkdoc:::lodddoloxkkkkk0NMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMNl,o0KKXNWMWx;,''',;,'''oNMMMMMMMMMMMMMMMMM    //
//    MMMMMMMDUBIOUXMMMO;oNMMMMMMMXl',o00XXKk:.,OMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMWO;:0MMMMMMMXo;;oXMMMMMWk,.dWMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMK:'kWMMMMMMXl'o0NMMMMMMMXl.;0MMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMWk,oNMMMMMMNo';0MMMMMMMMMMk,.lXMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMKccKMMMMMMNd,'oNMMMMMMMMMMNl.,lONMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMM0:.lKXK000kl,'lXMMMMMMMMMMMM0dc''oXMMMMMMMMMMMM    //
//    MMMMMMMMMMMMXc.';c:,,,'';d0NMMMMMMMMMMMMMMNk;.:0MMMMMMMMMMMM    //
//    MMMMMMMMMMMMXkxk0K0O0OOOXWMMMMMMMMMMMWNKkoc,';kWMMLUXURYMMMM    //
//    MMMMMMMMMMN0kkkkkOOO000XXXWWNNNXKKOdoc;;;:cokXWMMMMMMMMMMMMM    //
//    MMMMMMMMMXo,cddllccc:;;;;;clc::;,,;;:lxOXNWMMMMWWMMMMMMMMMMM    //
//    MMMMMMMMM0;'dXWMWWWWNXKkolc;;:clx0XNWMMMWXX0OxolllkNMMMMMMMM    //
//    MMMMMMMMMW0o::oxOOxOKNWMWWWXXNWWMWXK0OxoldxcldkOd;'l0NMMMMMM    //
//    MMMMMMMMMMMWX0Oxo:'';:ldOKK0Oxdolc::codxOXXXWMMMW0o:;kWMMMMM    //
//    MMMMMMWWNX0kkOKKOOOOOkxdl:::codxkO0XWMMMMMMMMMMMMWXd'oNMMMMM    //
//    MMMMMMKkKWNNX00Odold0NNNXKXNNWMMMMMMMMMMMMMMMMMMMMKkcoNMMMMM    //
//    MMMMMMKkXMMMMMMMMW0xkOkxkKNNNNNWMMMMMMMMMMMMMMMMMWklxxKMMMMM    //
//    MMMMMMWXXMMMMMMMMMMMMNXKOOOkdlcld0NWMMMMMMMMMMMMMMKo;c0MMMMM    //
//    MMMMMMWKKMMMMMMMMMMMMMMMMMMWKOxdllcldOXNXNWMMMMWNkl;,dNMMMMM    //
//    MMMMMMMWXNMMMMMMWWWNWMMWNWNWMMMMMWXkolc:;:lo0WNk:,:d0WMMMMMM    //
//    MMMMMMMWXXWWWMMMXXNNWMMWNWWWMMMMMMMMMWXOdl::lxOdoONMMMMMMMMM    //
//    1983MMMMMNKXNWMMMMMMMMMMMWWNNNXXXNNWWMMMMWNKKKKXWMMMMMMMMJVK    //
//                                                                    //
//                                                                    //
////////////////////////////////////////////////////////////////////////


contract DUBLUX is ERC1155Creator {
    constructor() ERC1155Creator() {}
}
