// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @author: BLOCKS

import "./libraries/blocks/BlocksERC721LazyAllowlist.sol";

/**
 * BlocksMeebitsExtension - BlocksERC721LazyAllowlist for the Meebits community

MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx:0MMMMMMMMMMWo   lWMMMMMMMMMKcxMMMMMMMMMMMMMMMMMXcoWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx:0MMMMMMMMMMMO. .OMMMMMMMMMMKcxMMMMMMMMMMMMMMMMMXcoWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx:0MMMMMMMMMMMNc :XMMMMMMMMMMKcxMMMMMMNXKKKKKKKKKO:oWMMMMMWXKKKKKKKKKK
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx:0MMMMMMWNNWMMx'dWMWNNMMMMMMKcxMMMMMMk;'''''''''..oWMMMMM0:'''''''''.
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx:0MMMMMNl,;xWMKx0MMk,lXMMMMMKcxMMMMMMN000000000O; oWMMMMMNK00000000Oc
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx:0MMMMMX; .oWMWNWMWd.,KMMMMMKcxMMMMMMMMMMMMMMMMNc oWMMMMMMMMMMMMMMMWd
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx:0MMMMMX; .oWMMMMMWd.,KMMMMMKcxMMMMMMWWNNNNNNNNXc lWMMMMMWWNNNNNNNNNo
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx:0MMMMMX; .oWMMMMMMd.,KMMMMMKcxMMMMMMO:,,,,,,,,,. oWMMMMM0c,,,,,,,,,.
MMMMMMMMMMNKKKKXWMMMMMMMMMMMMMMMNKKKKXWMMMMMMMMMx:0MMMMMX; .oWMMMMMMd.,KMMMMMKcxMMMMMMXkkkkkkkkkkd;oWMMMMMNOkkkkkkkkkk
MMMMMMMMMNo....:KMMMMMMMMMMMMMMNo....cXMMMMMMMMMx:0MMMMMX; .oWMMMMMMd.,KMMMMMKcxMMMMMMMMMMMMMMMMMXloWMMMMMMMMMMMMMMMMM
MMMMMMMMMNc    '0MMMMMMMMMMMMMMNc    ,KMMMMMMMMMx:0MMMMMX; .oWMMMMMWd.,KMMMMMKcxMMMMMMMMMMMMMMMMMXcoWMMMMMMMMMMMMMMMMM
MMMMMMMMMNc    '0MMMMMMMMMMMMMMNc    ,KMMMMMMMMMx,cxxxxxo,..:ddollcc' .lxxxxxl';xddxxxxxxxxdxxdddo',dxdxxxxxdxdxxxxxxx
MMMMMMMMMNc    '0MMMMMMMMMMMMMMNc    ,KMMMMMMMMMx;xKKKKKKKKKKK0Oxo,.  'kKKKKKx;l0KKKKKKKKKKKKKKKKO;c0KKKKKKKKKKKKKKKKK
MMMMMMMMMNc    '0MMMMMMMMMMMMMMNc    ;KMMMMMMMMMx:0MMMMMMMMMMMMMMMNk' ,KMMMMMKcxMMMMMMMMMMMMMMMMMXcoWMMMMMMMMMMMMMMMMM
MMMMMMMMMWOllllxNMMMMMMMMMMMMMMWOllllkNMMMMMMMMMx:0MMMMMWWWWWMMMMMMWd.,KMMMMMKcdWWWWWMMMMMMMMWWWWXcoWMMMMMMWWWWWWWWWWW
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk:0MMMWx:;;;;dNMMMMMx.,KMMMMMK;.;;;;c0MMMMMWk:;;;,.oWMMMMM0c;;;;;;;;;;
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx:0MMMW0dddddOWMMMNk' ,KMMMMMK,     .kMMMMMWo      oWMMMMMXxdddddddddd
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx:0MMMMMMMMMMMMMMWO,  ,KMMMMMK,     .kMMMMMWo      oWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx:0MMMMMMMMMMMMMMMWKl.,KMMMMMK,     .kMMMMMWo      oWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx:0MMMWOlccccxNMMMMMNl:KMMMMMK,     .kMMMMMWo      .ccccccccccoKMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx:0MMMWOlllllkNMMMMMMxcKMMMMMK,     .kMMMMMWo      'cllllllllloKMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx:0MMMMMMMMMMMMMMMMMX:;KMMMMMK,     .kMMMMMWo      oWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx:0MMMMMMMMMMMMMMMNO; ,KMMMMMK,     .kMMMMMWo      oWMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx:0MMMMMMMMMMMWNKk:.  ,KMMMMMK,     .kMMMMMWo      oWMMMMMMMMMMMMMMMMM
*/

contract BlocksMeebitsExtension is BlocksERC721LazyAllowlist {

 constructor(address creator, string memory prefix, uint256 mintPrice, uint256 maxMints) BlocksERC721LazyAllowlist(creator, prefix, mintPrice, maxMints) {}

}