
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: HANDIEDAN
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                        //
//                                                                                        //
//    QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ    //
//    QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ    //
//    QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQb)······sssssp((bPGQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ    //
//    QQQQQQQQQQQQQQQQQQQQQQQQQSO)·PQQQ···)SQQQQQQQQQQQQeQpbGQQQQQQQQQQQQQQQQQQQQQQQQQ    //
//    QQQQQQQQQQQQQQQQQQQQQQbb·······)GQesQQQQQQQQQQQQQQQQQQep(GQQQQQQQQQQQQQQQQQQQQQQ    //
//    QQQQQQQQQQQQQQQQQQQQO·············)GQQQQQQQQQbC·((·(PQQQQQ·)QQQQQQQQQQQQQQQQQQQQ    //
//    QQQQQQQQQQQQQQQQQQb····seQQQSeeep····PQQQQQb··sSQQQQe·)QQQQQ·)QQQQQQQQQQQQQQQQQQ    //
//    QQQQQQQQQQQQQQQQS···eQQQQQQQQQQQQQQQe···PQQ··QQQQQQQQQ·)QQQQQc·GQQQQQQQQQQQQQQQQ    //
//    QQQQQQQQQQQQQQQb··sQQQQQQQQQQQQQQQQQQQQep··PeQQQQQQQQQb)QQQQQQQ·)QQQQQQQQQQQQQQQ    //
//    QQQQQQQQQQQQQQb··QQQQQQQQQQQQQQQQQQQQQQQQQe··(GQQQQQS·)QQQQQQQQb·)QQQQQQQQQQQQQQ    //
//    QQQQQQQQQQQQQb··SQQQQQQQQQQQQQSbbGGQQQQQQQQ··ep····(sQQQQQQQQQQQp·)QQQQQQQQQQQQQ    //
//    QQQQQQQQQQQQQ··(QQQQQQQQQQQQb)SSQQQ·)QQQQQQ··QQQQQQQQQQQQQQQQQQQQ··QQQQQQQQQQQQQ    //
//    QQQQQQQQQQQQb··QQQQQQQQQQQQb·QQQQQQb·QQQQQQ··QQQQQQQQQQQQQQQQQQQQp·)QQQQQQQQQQQQ    //
//    QQQQQQQQQQQQb·)QQQQQQQQQQQQQ·)QQQQQb·SQQQQQ··QQQQQQQQQQQQQQQQQQQQb··QQQQQQQQQQQQ    //
//    QQQQQQQQQQQQb·)QQQQQQQQQQQQQQe····Sb·········Q···()QQQQQQQQQQQQQQb··QQQQQQQQQQQQ    //
//    QQQQQQQQQQQQb·)QQQQQQQQQQQQQQQQQQQQb·SQQQQQ··QQQQQQ·SQQQQQQQQQQQQb··QQQQQQQQQQQQ    //
//    QQQQQQQQQQQQb··QQQQQQQQQQQQQQQQQQQQb·SQQQQQ··QQQQQQb)QQQQQQQQQQQQ··)QQQQQQQQQQQQ    //
//    QQQQQQQQQQQQQ··SQQQQQQQQQQQQQQQQQQQb·SQQQQQb·(GSSbbsQQQQQQQQQQQQb··QQQQQQQQQQQQQ    //
//    QQQQQQQQQQQQQQ··QQQQQQQQQQSO)····(Pb·SQQQQQQQQeeeQQQQQQQQQQQQQQS··(QQQQQQQQQQQQQ    //
//    QQQQQQQQQQQQQQb·)QQQQQQQQb)QQQQQQSp··)QQQQQQQQQQQQQQQQQQQQQQQQS··)QQQQQQQQQQQQQQ    //
//    QQQQQQQQQQQQQQQb·)QQQQQQb·QQQQQQQQQbbp·(PQQQQQQQQQQQQQQQQQQQQb··(QQQQQQQQQQQQQQQ    //
//    QQQQQQQQQQQQQQQQQ··GQQQQQ·QQQQQQQQQ··SQep·(PGQQQQQQQQQQQQQQbb··SQQQQQQQQQQQQQQQQ    //
//    QQQQQQQQQQQQQQQQQQe·)QQQQb·PQQQQSb··sQQQQQe····(DbGGGGGbC····sQQQQQQQQQQQQQQQQQQ    //
//    QQQQQQQQQQQQQQQQQQQQe·)GQQQeep··)sQQQQQQQQQQQe·············sQQQQQQQQQQQQQQQQQQQQ    //
//    QQQQQQQQQQQQQQQQQQQQQQQc·PGQQQQQQQQQQQQQQQQQS)QQQ·······)SQQQQQQQQQQQQQQQQQQQQQQ    //
//    QQQQQQQQQQQQQQQQQQQQQQQQQQep(PGQQQQQQQQQQQSC···GQQb··sQQQQQQQQQQQQQQQQQQQQQQQQQQ    //
//    QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQeeQ((·DDD·)······sQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ    //
//    QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ    //
//    QQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQQ    //
//                                                                                        //
//                                                                                        //
//                                                                                        //
//                                                                                        //
////////////////////////////////////////////////////////////////////////////////////////////


contract HAND is ERC721Creator {
    constructor() ERC721Creator("HANDIEDAN", "HAND") {}
}
