// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

import "./erc721/ERC721Core.sol";

/*

MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM#""MMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM]   .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:   JMMMMMMMMMMMMMM
MMMMMMMMMMMWMMM#MMM'   (Y`    ?TMMMMMMMH""MMM]   .MMMM@MMMMM"""?4MMMMMMM"MMMMM"!    _""MMM"`    (TMMM    MMMMMUMMMMMMMMM
MMMMMMMN.   JMD  TF   .#          MM"       .M}  .MMD` ,MMMMb    M@  WM^   .D          JF        .uM#    MM@!  MMMMMMMMM
MMMMMMMMN,            J\ .MMNx   .M`    .. .M]   ."     JMMMM[        !   .F    JMMa   .b  .gMMgMMMMF   .=     (MMMMMMMM
MMMMMMMMMM,          .F  JMMM#   .F   .MMMMMMb..      .MMMMMMN,          .M]   .MMMM'   Ux .MMMM"HMM%        .MMMMMMMMMM
MMMMMMMMMMMp   .(,.  d'   .7!    .N   .MMMD    M`      ?MMMMMMb   ...   .MMN.    77      N   7=    d:   .     TMMMMMMMMM
MMMMMMMMMMMMb .MMMMN-MN,         .M,          .D .N,    .JMMMMMp.dMMMa..MMMMMqp       .  M.       .M    dN,    .MMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMNgJJgMa.-MMN,.    ..MNgggMMMmgMMMMMMMMMMMMMMMMMMb   .MNg((NMMMMMMMNgJ(gMMMMMMMMMMMNgMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMH"MMMMMMM#"T"HM"!    ?""MMMM@^    .TMMN    MMMM3,MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM[   .M#` TM'   .F         dM@        ..MM.   dMD   ,MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx            .@  .+MNe   -#    .MMmgMMMM;   /`    .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM,          .M`  -MMMM`  .N    MMMM#WMMM]        TMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM,   .,    dN    .7"     W,    ?"!    dF    .      TMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN,.uMMMa.-MMN,        .  Ma.       .MM#    MNa. .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN&..+MMMMMMMMNg(.JgMMMMMgNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM

*/
contract WackWackWack is ERC721Core {
    /* solhint-disable no-empty-blocks */
    constructor() ERC721Core(
        "wackwackwack - Fractional musicNFT",
        "WAC",
        "https://bafybeigo2agu5gj7s4yzem4hnr3eu26pem5kyciav5znqjwi2pqmhnyxbu.ipfs.nftstorage.link/json/",
        ".json"
    ) { }
    /* solhint-enable no-empty-blocks */
}
