
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Anser Patris
/// @author: manifold.xyz

import "./ERC721Creator.sol";

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                           //
//                                                                                                                           //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWNXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMW0o,..'lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMKl. 'c;  lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMWk' ,xNM0' ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMNo..oXMMM0' ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMXl.'OWMMMMO. ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMNl.;KMMMMMMx. ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMNo.;KMMMMMMMo  cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMWx.,KMMMMMMMN:  lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMO.'OMMMMMMMMK,  dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMX:.xWMMMMMMMMO. .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMWd.cNMMMMMMMMMx. .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMM0''0MMMMMMMMMMo  ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMWl.dWMMMMMMMMMWc  ;XMMMMNKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMM0',KMMMMMMMMMMX;  :K0xoodkKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMd.oMMMMMMMMMMMK,  .,;cxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKKNMMMMM    //
//    MMMMMN:'0MMMMMMMMWKx;   ,ONMMMMMMMMMMMMMMMMMMMMWXOOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMW0dc;'...'xWMMM    //
//    MMMMMO.cWMMMMMWKd:,;;.  oMMMMMMMMMMMMMMMMMMMMMKc.  'OMMMMMMMMMMMMMMMMMMMMMMMMMNkc;,oXMMMMMMMNNMMMWKo,.      .:OWMMM    //
//    MMMMMd.dMMMMXxc;:d0WO.  dMMMMMMMMMMMMMMMMMMMWx.    .xMMMMMW0dc;c0MMMMMMMMMMMM0; .,..OMMMMMMWooWMXo.   .,cdkOXWMMMMM    //
//    MMMMWc'0MW0l:cxXWMMMO.  oMMMMMMMMMMMMMMWXXMNo. .l' .xMMW0d:..:dkXMMMMMMMMMMWk. 'kx.:XMMMMMMWc;KO,   ,dKWMMMMMMMMMMM    //
//    MMMMX;;KOlcdKWMMMMMMO.  lWMMMMMMMMMMMMMNccKo. ,00' .xMM0'  ;0WMMMMMMMMMMMMMO. ;0k',0MMMMMMMMl'l'  'kNMMMMMMMMMMMMMM    //
//    MMMMK,'ooONMMMMMMMMMO.  :NMMMMMMMMMMMMMWc.;. ;KMO. .kMMx.  oNMMMMMMMMMMMMMK, .oc,lKMMMMMMMMMd.   :KMMMMMMMMMMMMMMMM    //
//    MMMM0',OWMMMMMMMMMMMK,  ,KMMMMMMMMMMMMMWl   ,KMMk. .OMMNl.  ;xXMMMMMMMMMMWl  ,ldKWMMMMMMMMMMx.  ;KMMMMMMMMMMMMMMMMM    //
//    MMMMO'oMMMMMMMMMMMMMN:  .kMMMMMMMMMMMMMMo  .OMMMx. '0MMMNXk,  .cxKWMMMMMM0' ;XMMMMMMMMMMMMMMO. .xMMMMMMMMMMMMMMMMMM    //
//    MMMMk'oMMMMMMMMMMMMMWo   lWMMMMMMMMMMMMWo  oWMMMx. '0MMMMMMNkc.  .;dKWMMMk. oWMMMMMMMMMMMMMMk. ,KMMMMMMMMMMMMMMMMMM    //
//    MMMMO,oMMMMMMMMMMMMMMO.  '0MMMMMMMMMMMMK; ,KMMMMx. .kMMMMMMMMMXkc'  .lKMMk. lWMMMMMMMMMMMMMMd  cWMMMMMMMMMMMMMMMMMM    //
//    MMMM0,oMMMMMMMMMMMMMMNc   cNMMMMMMMMMMMk. cNMMMMk.  dMMMMMMMMMMMMXd.  lWMK; .xWMMMMMMMMMMMMMo  oMMMMMMMMMMMMMMMMMMM    //
//    MMMMX:cWMMMMMMMMMMMMMM0'   lNMMMMMMMMMMd  :NMMMMK,  ,KMMMMMMMMMMW0l.  oWMMO' .:xO00kxokWMMMMd  dMMMMMMMMMMMMMMMMMMM    //
//    MMMMWl:XMMMMMMMMMMMMMMMk.   :KWMMMMMMMWl  :NMMMMWx.  .lOWMWNKOdl,.   :XMMMMKc.       'kWMMMMx. oMMMMMMMMMMMMMMMMMMM    //
//    MMMMMx;OMMMMMMMMMMMMMMMWO'   .lONMMMMMWl  :NMMMMMWk'   :00o..      .oXMMMMMMWKxl:;;:oKMMMMMMX:.dMMMMMMMMMMMMMMMMMMM    //
//    MMMMMK;lWMMMMMMMMMMMMMMMMK:     'kMMMMMx. cWMMMMMMMXxcoKNKl.   .'cxXMMMMMMMMMMMMMMMMMMMMMMMMMX0NMMMMMMMMMMMMMMMMMMM    //
//    MMMMMWOOWMMMMMMMMMMMMMMMMMNk:.  'OMMMMMXl;OMMMMMMMMMMMMMMMWOoox0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxxKMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                                           //
//                                                                                                                           //
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract ANSR is ERC721Creator {
    constructor() ERC721Creator("Anser Patris", "ANSR") {}
}
