
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: DRPAW-GENESIS
/// @author: manifold.xyz

import "./ERC1155Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                            //
//                                                                                                            //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMWXOdlc:::ccokKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo;,:odkkxdl,..:k0XWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO,..cKMMMMWXXKo...'lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo...,0MN0dccxNXc....oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKdcoOX0c',dKWMNl....lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWk,.,kWMMWk,....xWMMMMMMMMMMMWK0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNx,..xWMWNk;...'lXMMMMMMMMMMMMXc:KWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0dc:::'..;kKOxc...,d0XXXKKKXWMMMMMMO':KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMXl''clc'...,::,',:::ldxxdc,':dKWMMMMNo.:XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMWx.'kOl;....'oKK0xc;lxOOd;,ckXWMMMMMWk'.lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMWMMWx.,OK0o...,.;OO:.:OXO:'':ONWMMWMMWMK:.'kWN0xkXWMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMWWNX0o,c0O;..:c'co'.cKKl'';lxolokXWWMWXo..cXMO,..dWMMWWMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMXd;';xOdl;..'clxO:.'k0c.,od:.....lXWWXo..,kWMXkoxKWMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMM0;...lXKl..:ONWMNd..c;.'do'......:KWXl..'xWMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMNk;..;:,.,oKWMWMMNOc'..o0:...;;:o0N0:..'xNWXXNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMWXOxdodkXWMMMMMMMWx..'O0;..;0NWWKd'..;OWXo,'oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo...lo,...cddc'..;dXMMXd;;dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0:'.;cool:,'',:okXWMMMMWNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNKKXWWMWNXXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMWWMMWWMMMMMWWMMMMMWWMMMMMMMMMMMWWWMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMW0kKWMMMMMWMNKK0KKNWXKK0XWNKKKKNWKO00XWMX0K0XMWX0KKXMNOOXMNOONMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMWOxXWWWMMMMMNOxxx0WWOOKO0WXO00OXW0dkO0NW0dxdOWWOOKOKMXddKMXxxXMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMWNNMMWWWMMMMMNNNNWMWNKKXWMWXKKNWWNKKKNWWNNNXNMMNXKXWMWXXWMWXXNMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMWXNMMMNXWMMMMMMMNKNMMWKXWMMMMMMN0kkkKWMMMWMMNKNMWMWWMMWN0OkOXWMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMM0cdNMNdlKMMMMMMMOckMMKlxWMMWMMNd:ldxONWMMWMM0lkMMMWWMNOodkkx0NMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMWx,;xXx;,kWMMMMMMO:kWWKcdWMMMMMWOooox0NWWMMMM0ckMMMMMM0cxWMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMXloxc:lxllXMMMMMW0cxWM0cdWMMMMMWXKKKd:kWMMMMMOckMMMMMM0cdNMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMM0lOWx:kWklKMMMMMMXxlxxooKWMMMMMNxloddlOMMMMMM0lOWMMMMMNOooxxx0WMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMNXNMWNWMNXWMMMMWMMWX00KNMMMMMMMWNKOO0XWWWMMMMWXNMMMMMMMWNKO00XWMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMWMMMMWWWMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMWMMMMMWMMMMMMMMMMMMMMMMMMMMWMMWWMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                            //
//                                                                                                            //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract PWMR is ERC1155Creator {
    constructor() ERC1155Creator() {}
}
