
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Automotive Reels
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                 ........                                                                                                                                           //
//                                                                                                                                                 ..',;cloddxxkO000KKKKKK00OOkxddolcc:;,'....                                                                                                                        //
//                                                                                                                                          .';coxO0XNWWMMMMMMWWWWWWWWWWWMMMMMMMMMMMMMMWWNNXKK0Okxdollc:;,'...                                                                                                        //
//                                                                                                                                   ..,coxOKXNXK0Okxdoolcc:::;;;;;,,,,;;::cclodxkOKXNWMMMMMMMMMMMMMMMMMWWNNXK0Okxdolc:;,'...                                                                                         //
//                                                                                                                              .':ok0K0Okdl:;'...                                 ..';cldk0XNMMMMMMMMMMMMMMMMMMMMMMMMMWWNXXK0kxoc;'.                                                                                 //
//                                                                                                                         .':ok00Oxl:'.                                                   ..,:ldk0NWMMMMMMMMMMMMMMMWNXK0Oxdoc:;,...                                                                                  //
//                                                                                                                     .;lxO0kdc,.                                                                ..;cdkKNWWNXK0Okkxdolc:;;;;;;:::::::cccccccc:::::;;;,,,'......                                                      //
//                                                                                                                 .;okOOxc,.   ....                                                     .....'',;;:cclokKWWNNXXXXXXNNNWWWWWWWMMMMMMMMMMMMMMMMMMMMMWWWWWWNNNXKK0Okxdolc,                                              //
//                                                                                                             .;okOko:'.  .,cdkKNXOc.                                ....',;;:clloodxkOO0KKXXXNNNNNXXXKKK00OOkkkxdddooooolllllccccccc::::::cccccllloooddxkkO0KXNWWMMMNo.                                             //
//                                                                                                          'cxOko:.     .lXWMMWNXKOo.             ....',,;:ccloodxkO00KKKKKKKK00Okkxddollcc::;;,''.......;:;.                                               ...',:llc'                                               //
//                                                                            ..,;:cloooddddddoooollcc:;;;ckK0d:..       .cO00Oo:;,,'',;;:cllodxkkOO000000OOOkkxdoolcc:;,,'.....                          .c0x.                                                  .'''.                                                //
//                                                                     .':ldxkkkxxdolc:::::::::ccclloodddxkkOkkkkkkkkxxxxkkOOOOOOOOOOOkkkxxdoolcc:;,,'....                                                .ox,                                                    .,;.                                                //
//                                                               .':oxkkkdoc;'..                             ......''',,,,,,''''......                                                                   'xo.                    .,:loooddddool:'.                 .,'                                                //
//                                                          .':oxOOxo:,.                                                                                                                                ;xc.                 .,codol:,'.....';:lodoc'               .'.                                               //
//                                                      .,lxkOxoc,.             .':cloooooolc;'.                                                                                                      .cx;                 .col:.                .':oo;.              ..                                              //
//                                                  .;okOOdc,....           .,loool:;,'''',;cloooc'                                                                                                  .od.                .:l;.                       .:l;.             ..                                             //
//                                              .;lk0Odc'.   ...          'col;.               .':lo:.                                                                                              'dl.                'c,                            .,'              ..                                            //
//                                           'cx00xc,.. .......         .cl,.                      .;c:.                                                                                           ;d;                  ..                                                                                            //
//                                          ;OOo;.     ......         .;c'                            ';.                                                                                        .co'                                                                                                                 //
//                                          ...                       .'                                                                                                        ..........      'lc.                                                                                                                  //
//                                                                                                                                                          .....''',,,''''...........       .,;,.                                                                                                                    //
//                                                                                                                                       ....',;;::::::::::;;;;;;,,'....                    ...                                                                                                                       //
//                                                                                                                         .;:ccloooddoooooollcc:;;,'...                                                                                                                                                              //
//                                                                                                                       .,lddolcc:,'....                                                                                                                                                                             //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                               ,xkkkkd;ckkkkkkxc.          .ckkkkkc        .lkkkkk:;xkkkkkko'    ,xkkkkkkkxc,ckkkx;       .;xOkkkl.        .ckkkkkc.   'dkkkkx;       .lkkkkx;                :kkkkkkkkkl.  'dkkkkx:     ckkkko.    .cxkc,dkkkkkxc.                                                 //
//                                               :NMMMMKcdNNNWMMMW0l.       cdl0MMMMXc       .OMMMMWdcKNNNWMMMXd'  cNMMMMMWKolOWMMMNl      ;dlkWMMMNo        .xMMMMMx.  ;0MMMMXl.     .lolKMMMM0,               oWMMMMMMMWk. .;oKMMMMNo.  .xMMMMO'  .l0WMMxc0NNWWMMW0c.                                               //
//                                               :NMMMMK;.''':0MMMMWd.     ,KNdlXMMMMK,      .OMMMMWd..'',dNMMMMO' .;:::::::dXMMMMNx.     'OWkl0MMMMX:       .xMMMMMx..lXMMMWO;       cXXooNMMMWO.              .:OMMMMMKl'  .xko0WMMMWx. .xMMMMO' .dWMMMMx..'':0MMMMWo                                               //
//                                               :NMMMMK;    .OMMMMMx.    .kMMXloNMMMMO.     .OMMMMWd     cNMMMMK,        :0WMMMW0:      .dWMNdlXMMMM0,      .xMMMMMx,oNMMMNx.       ,0MM0lxWMMMWx.               dWMMMMO.   .OWOlOWMMMWO,.dMMMMO. .kMMMMMx.   .xNNNNNo.                                              //
//                                               :NMMMMKc:xxxONMMMWO,    .dWMMMk;xWMMMWx.    .OMMMMWd.    cNMMMMK,      'xNMMMMXo.       lNMMM0;oNMMMMO'     .xMMMMMklKMMMXo.       .kWMMWd;OMMMMNo               dWMMMMO.   .OMW0oxNMMMM0coNMMMO. .kMMMMMx.    .'''''.                                               //
//                                               :NMMMMKcoKKKXWMMMNd.    cXMMMNl 'OMMMMNo    .OMMMMWd;xOOOKWMMW0:.    .lKMMMMNk,        ;KMMMWd..xWMMMWx.    .xMMMMMklKMWOoxo.     .oWMMMX: ;KMMMMX:              dWMMMMO.   .OMMMXooXMMMMXdoXMMO. .kMMMMMx.                                                          //
//                                               :NMMMMK; ...,0MMMMWd.  ,KMMMWk'..lXMMMMX:   .OMMMMWdc0XKOkxxko.     ;OWMMMW0:.        .OMMMM0,..:KMMMMNo    .xMMMMMklKNxo0WWx.    cXMMMWd...dNMMMM0,             dWMMMMO.   .OMMMMx.:KMMMMNxo0WO. .kMMMMMx.    ':::::.                                               //
//                                               :NMMMMK; ...,OMMMMMx. .kWMMMKloKKXWMMMMM0,  .OMMMMWd...cO000XO'   .dXMMMMXd;'......  .dWMMMXol0KKNMMMMMX:   .xMMMMMklxllKMMMWk.  ,0MMMMOcdKKXWMMMMMO.           'xWMMMM0;.  .OMMMMx. ,OWMMMWklOO' .xMMMMMx. ..'OMMMMWd.                                              //
//                                               :NMMMMKcl000KNMMMNx' .dWMMMNo:kKKKKXWMMMMO. .OMMMMWd   .dNMMMW0, .dWMMMNOlo0XNNNNN0, cNMMMWx:xKKKKXWMMMM0,  .xMMMMMk,. ,OWMMMWk'.kWMMMXlc0KKKKNWMMMWx.         lXWMMMMMWXd. .OMMMMx.  .xWMMMW0o:.  ,xNMMMx:x00KNMMMXd'                                               //
//                                               ;0XXXXO:oXXXXXXKx,   ;0XXXXx. .....'xXXXXKl..dXXXXKl    .dKXXXXx'.dXXXOl:xKXXXXXXXO,'kXXXXk' ......dKXXXXd. .oXXXXXo.   ,kXXXXKxd0XXXKo. .....;kXXXX0:         lKXXXXXXXXd. .dXXXXo.   .oKXXXXk;     ,xKXo:OXXXXXKx,                                                 //
//                                                ...... ........     .......        .......  ......       ......  ..... ...........  ......         ......   .......     .............         .......          ..........   ......      .......       ... .......                                                   //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                           .                                                           .                                 ..                  ..                                                                .                                                                    //
//                                                        .  ..        .   .     .    .     .        ..                 ...      .        .               ....      .   .       .      .    .           .  ..     .  ..    ..    .     ...      ..        .  ..                                                       //
//                                                        ..   ..      .   .          .     ..       ..         ..     .. ..     ..       ..             ..  ..     .   .              .    .           .. ..     .. .      .         ....      ..        .  .                                                        //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract AR is ERC721Creator {
    constructor() ERC721Creator("Automotive Reels", "AR") {}
}
