/*

EL TORO DE ORO ASCII ART & CONTRACT BY ALPHACOIN.CO
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkdodxkOKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkollllllllodxkOKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkolllllollllllllllodxkO0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWXKOkdoodxO0KNWMMMMMMMMMMMMMMMMMMMWWNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKkollllloooooooolllllllllllooxkO0KXNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0Oxdlcc:::ccccclodxO0XNNNNXXKK00OOkkxddddkXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKxololoooooooooooooollllllllllllllloodxxxkkO00KXXNWWMMMMMMMMMMMMMMWNK0Oxdolccc:::::::cc:cc::cccloddoollccccc:cclccccxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0xoooooooooooooooooooooolllllllllllllllllllllllllloodxkkO00KXXNNXKOkxdolllccc:::::::::::::::::::::ccccccc:::::::cc:,,,;xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0xoooooooooooooooooooooooooollccccclllllllllllllllllllllllllllloooolllllllccc::::::::::::::::::::::::::::::::::;,,,,;,'..,xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOxoooooooooooooooooooooooooooooolc::cccccccccccccclllllllllllllccccccccccccccc::::::::::::::::::::::::::::::::::;,,'''',,'..,kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdooooooooooooooooooooooooooooooolc:;;;;;;::::::::ccccccccccccccccccccccccccccc:::::::::::::::::::::::::::::c:;;,'''''...',;,''c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkdooooooooooooooooooddddddddddooooc:;,,,,;;::::ccccccclllllc:::::cccccccccccc::::::::::::::::::::::::::::::::::;,','...',,,:looc,.:0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0xooooooodddddddddddddddddddddddddoc:;,,,,,,,;:loolllodddddooolcccccccccccccccc:::::::::::::::::::::::::::::::;;;;,'''...,;::;clll:,,'oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWN0xooooodddddddddddddddddddddddddddol:;,,,,,,,,,,,;;:::::cldxxddooddooooooooolooolllcc:::::::::::::::::::::::::;;,,,''',;;;:c::::c::::::,;dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdooooddddddddddddddddddddddddddddol:;;;;;;;,,,,,,,;,;;:::::cldxxxdoodddoooooollooooooool:;;;;;;;;;;;;;;;;:::cc:,,,''',;:cccccc::c::::::,'';oKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX0KWMMMMMMMMMMMMWKkdoooddddddddddddddddddddddddddddddoc:;;;;;;;;;;,,;,,;;,;;;;;;::codxxxooodoooolcloolllooddoc;;;;;;;;;;;;;;;:::cc:'''..';::::::::::;;;;;;;,''',;cOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWWNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWWWWWWWWWKdcldOKNWWWWWWWN0xoooooodddddddddddddxxxxxxxxxddddddol:::;;;;;;;;;;;;;;;;;;;;;;;;;:::ldxxxdooddooollooooloodoc;;::;;;;;;;;;;;::cc:,'....,:c::::;;;;;;;;;;;;,''''',,oKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWNXK00OOkkkkkkkkkkkkkkkkkkkkxxxxxkkkkkOOOOO0000000KKKKKKKK0dcccccloxk0KKKKOlloooooddddddddddxxxxxxxxxxxxxxxddolc::::::::;;;;;;;;;;;;;;;;,;;;,;;;:lxxxxdolodooooolloooddl:;::::::::;;;:::cc:;''...';ccc::;;;;;;;;;;;;;,'....',;:dkkkkkkkkkkkkkkkkkkxxxxxxxkkxkkkkkxxxxxxxkkkO0KXNWMMMMMMMMMMMMM
MMMMMMMMMMMWXKOkxxxxxxxxdddddddddddddddddddoddddddxxxxxkkkkkkkkkOOOOOOOOxoooollllllodkOOxooooooddxxxxxxxxxxxxxxxxxxkkxxdolcccccc::cc:::::;;;;;;;;;;;;;;;;;;;;;;cloodxdlcc:::cclccclddoc::::;;;;;:::::::,'.....,:cc::;;;;;;;;;;;;;;,'......',,:ldddddddddddddddddddddodddddddddddoooodddddddddxO0XWMMMMMMMMMM
MMMMMMMMWNKOkxxxxxdoc:,'..............................................;oxdooooooodddddxxdoooooddxxxxxxxxxxxxxkkkkkkkxdl:;::ccccccccc::::::::;;;;;;;;;;;;;;;;;;;;;;:cc:;'''''',,,,,:lllc::;;;,,;;::;,,''..''',:cc::;;;;;;;;;;;;;;;;,..........',,.....................................',;cloooooodOKNMMMMMMMM
MMMMMMWNKOkkkkxoc,..                                                 .cdoolodddddddolllccclooddxxxxxxxxxxxkkkkOOkkxooolc:;;:ccccccccccc:::::::;;;;;;;;;;;;;;;;;;;;;;,,'''''.....''',;;;;;,,,''',,'''''',;::cc:::;;;;;;;;;;;;;;;;;,'...............                                       ..,cooooodkKWMMMMMM
MMMMMWXOOOkkxl,.                                                    .cdollodxxxollll::;;;;:ccldxxxxxxxxkkkkkOOkxdooooolc::;:ccccccccccccc::::::::;;;;;;;;;;;;;;;;;::cc:,'.........''';;;,'...''',;;;::ccc:::;;;;;;;;;;;;;;;;;;,,,'''..........',,,..                                         .;coooddkXWMMMM
MMMMWKOkkkxc.                                                   .';cdxdollodxxdlcc::;,,;;:::::cloxxkkkkkkkkxxdoloooooolccc:;::;;:cccccccccc:::::::::;;;;;;;::cclloodool:;'..........',;,,:::cc:;:cc:ccc:;;;;;;;;;;;;;;;;;;;;;;;,''''........';;;,,;;,..                                        .,cooooxKWMMM
MMMNKOOkko'                                                   .;cloxxddoooddxxdlcc:;;,;:ccccccc:cldkkkkxdl:::c:;:loooooolccc;;;,,:cccccccccc:::::::::ccclloodddddddoolc:::,..........',';loc::::ccc:::;;;;;;;;;;;;;;;;;;;;;;;;,,''''.......';,''';;::c:,.                                        .;loood0WMM
MMWKOkkkc.                                                   ,loolodxxdoolooddlc:,',;;::::cccccc:cdkxdlcc:;,,,,,,,:looolllcc;,;;,,:ccccccccccccllllooooodddddddddooolllc:;,',:cc;''...'',::::ccc::;;;;;;;;;;;;;;;;;;;;;;;;;;;,,''''''......,,,;:::;:ccc:;'.                                        'cooodKWM
MMXOkOkc.                                                   ,looooooodxxddoddolc;...,;:::::::::::cllc::::::::;;,,,,,:lodoolc:;,;;,;cllccclcclddxxxxdoooolllcccc:::::;:c:,'.':ol;'.'..,:::ccc:::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,..''''''....',;;;,,;:ccc:;;;;'.                                       .colokNM
MWKOOkl.                                                   ,looodxdddddxxxxkkxo:,''';;;:c:;;;,,;:::::::::::::::::::;;:ccc:;,,,,,''',;,,,;;;:ldxkkkxxdddoollc:;;;;;;;;::,.';loc;'',;::ccc:::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,'..'''''.....,,,,',;cccc:;;;;,.                                         'loldKW
MN0kkd'                                                   'llooooodxxxxxxxkkkxl;,,,;;;;;:::;;;,,:c::::::::::::::::::::::::::::::;;;;;,,,'',cooddxxxddddddoolcccc:cccc:;,,colc:::cccc:::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,'''''''''....',,,;:ccccc:;;;;'.                                           ;oloOW
MN0kkl.                                                  'clllddlcloxkkkOOkkxc,',,;;;;;;;;;:::::lolc::::::::::::;;;;;;;;;;;;;::::::ccc::::cloooodddddxxddooolllllclll::cooc::ccc:::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,''''',,,,,,,'',;,,:ccccc:;;;,.                                             'lookN
MN0Ok:                                                   ,cllccccccodxxxkkkdc'.',;;;;;;;;;;;;;:cdxdlccc::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;coooooooddxxxddollccllllllc::ll:::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,',,,;;;;;;;;;,;,,;ccccc:;;;,.                                              .cookN
MN0Ok;                                                  .;clool:::ldxxxddkxl:,',,;;;;;;;;;;;;;cdxkxxdollc::;;::;;;;;;;;;;;;;;;;;;;;;;;;;;;cooooooooddxxddoc:::ccccclc:::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,'.....;;;;;;;;;;;;;;;;;:cccc:;;;'                                                .:ookN
MN0kx;                                                   .:cllc:;;:llooccllc:::;;;;;;;;;;;;;:ldkkkxxkxxxdl:;::;;;;;;;;;;;;;;;;;;;;;;;;;;;:loooooooooddxdolc:;;;;::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,'...      .,;;;;;;;;;;;;;;;;;;:::;;,.                                                 .:ookN
MN0kx;                                                   .';;::;,,,;;;:c::cccc:;;;;;;;;;;;;:lxxxddxkkkkkxc'',,;::;;;;;;;;;;;;;;;;;;;;,,,;cooooooooooolcc:;;;;;;;;;;;;::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,'...            .;;;;;;;;;;;;;;;;;;;;;;;,'..                                               .:ookN
MNOkx;                                                  ...',,,,''',,;cc::::c:;;;;;;;;;;;;:loolc::coxxkkd;...':llllccc:::;;;;;;;;;;;;;;;;loooooooooooc;;;;;;;;;;;;;;;;:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,..               .,;;;;;;;;;;;;;;;;;;;;;;;cc;.                                              .:ookN
MNOkk;                                                  ..'.''''....';::;;;;:;;;;;;;;;;;;;::;;;;;;,,;codc'.',cooooodoooolc;;;;;;;;;;;;;;:oooooooooool:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,''..'''.                .,,;;;;;;;;;;;;;;;;;;;:cc;....                                            .:ookN
MNOkx;                                                  .,;,,''.....',;::;;;;;;;;;;;;;;;;;;;;;;;;;;;,'','.';looooooodooc:;;;;;;;;;;;;;;;coooooooooool;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::;;;;,...''..               ....';;;;;;;;;;;;;;;;c:'.......                                          .:ookN
MNOkx;                                                 .;;;:;;,'....'',::;;;;;;;;;;;;;;;;;;;::;;;;;;;;,'.':loodooooooc:;;;;;;;;;;;;;;;;:loooooooooooc;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:c:::::;;;;;,...''.                   .,;;;;;;;;;;;;;;;,........                                          .:ookN
MNOkx,                                               .';::;;;;;;;,,,,'';;;;;;;;;;;;;;,'';;;;;;;;;;;;;;;,,coodooooooc:;;;;;;;;;;;;;;;;;;coooooooooool:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:cloc,,;:looolc:;'...                     ..,;;;;;;;;;;;;;,......''.                                         .:ookN
MNOkx,                                              .,;;;::;;;,'...',;,;;;;;;;;;;;;;,..',;;;;;;;;;;;;;;:looddooooc:;;;;;;;;;;;;;;;;;;;:coooooooooooc;,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::clool;';'.;clllllc:,'.                       .,;;;;;;;;;:;;;,...';c:.                                         .cookN
MNOkx,                                             .;:;;;;;;,.      .;::;;;;;;;;;;,'...',::;;;;;;;;;;;clooddoooc:;;;;;;;,,;;;;;;;;;;;;;:loooooooooo:;;;;;;;;;;;;;;;;,,;;;;;;;;;;;,'.':cllooo;';,. ..;cccllc,.                         .,:::;;;;;;;::;;,;cdd:.                                         .:ookN
MNOkx;                                           .,;;;;;:;,.        ..';:c:;,,,''.....';ll:;;;;;;;;;:coooodooc:;;;;,,;;;;;,,;;;;;;;;;;;,;looooooool;;;;;;;;;;;;;;;;;;;;;;;;;;;,'..   .;looo:';;. ....';::;;'.                          .;:::;;:::::::::colc,                                          .:ooON
MNOkx;                                         .';:::;:;,.          ....';c:'.......';:lo:,',;;;;;;:coddoooc:;,;;;;;;;;;;;;;;;;;;;;;;;;,,;loooooooc;;;;;,;;;;;;;;;;;;;;;;;,'...       .,loc',;. .......',,,.                            '::;;::::::::::::::,                                          .:ookN
MN0kk;                                        .,::::;;,.           .''....';:,...';cllc;,'...,;;;;coddddoc:;;;;;;;;;;;;;;;;;;;;;;;;;;;;'',;loooool:;;;;;;;;;;;;;;;;;;;;,'.              ':,''.........',;;.                             .,:;:cc:::::::::;;;'                                          .:ookN
MN0kk;                                      .';:::::,.              .';,....';::;;c;,'.....',:;;:lxkkkxl:;,;;,;;;;;;;;;;;;;;;;;;;;;;;;;..',;looooc;;;;;;;;;;;;;;;;;;;;;'.               ...........',,;,,.                               .;ccc:::::::::;,,;'                                          .cookN
MNOkx,                                    ..;:::::;.                  .;:,....,:,......',;ccc::cdkkkkdc;;;;;;;;;;,;;;;;;;;;;;;;;;;;;;;;...',;loooc;;;;;;;;;;;;;;;;;,;;'.               ........',,;:c::;.                                 ,c:::::::::ccc::c,                                          .cooON
MXOxx,                                   .,::::::'.                    .'::;'.......',:ccc:;;:okkkkxo:;;;;;;;;;;;;;;;'...',,;;;;;;;;;;,....;;;col:;;;;;;;;;;;;;;;;;;;,.               ....',;:loddolc:;.                                  .,::::::clooooc;c;                                          .cooON
MXOxx,                                  ';:::::;.                        .,cc:,..';:clc::;;:lxkOkkdc;;;;;;;;;;;;;;;;'.     ................';,,cc;;;;;;;;;;;;;;;;;;;,.               ..,;cldxxkkxoc::,.                                    .;:::cloddddo;';'                                          .cooON
MNOkx;                                 .;:::::,.                           .;ccccccc:::;;;cdkOOkxl:;;;;,;;;;;;;;;;;'                  .......,,,;;;;;;;;;;;;;;;;;;;,.               'codxxxkkkxdlccc;.                                      ':cloodddddl,',.                                          .cooON
MXOkx;                                .'::::;'                              .,:cc::;;;;;:okOOOkdc;;;;;;;;;;;;;;;;,.                   .......',,,;;;;;;;;;;;;;;;;;;,.             .:xxkkkkkkkxolccc;.                                       .:oodoodddo;...                                           .cooON
MXkxd,                                .,:::;.                                 .;;;;;;;;:okOOOxl;;;;;;;;;;;;;;;;;,.                  ........',,;;;;;;;;;;;;;;;;;;;'.             .:xxxkkkkkxdl::::,.                                        .:doooooodl'...                                           .cddON
MXkxd,                               .,:::,.                                   .';;;;;;,,;:ll:;;;;;;;;;;;;;;;;;,.                   ....''',,;;;;;;;;;;;;;;;;;;;;.               :dxxxkkkkxl:;;;;'.                                         .cdooooodo:'...                                           .cddON
MXkdd,                               .,:;.                                       .,;;;;;,'.',,,;;;;;;;;;;;;;;;;,.                  ...'',,;;;;;;;;;;;;;;;;;;;;;;'               ;dxxxxkkxdc;;;;;;.                                          .cdddddddl'....                                           .lxxOW
MXkdd,                               .',.                                         .';;;;;,',;;;;;;;;;;;;;;;;;;;'                 ..'',,;;;;;,,;;;;;;;;;;;;;;;;,.               .okkkkkkkkl;;;;;;;;;'.                                       .cddddoodc'. ..                                           .lxx0W
MXxoo'                               ..                                             .',,'',,;;;;;;;;;;;;;;;;;;;.                ..,;;;;;;;;;;;;;;;;;;;;;;;;;'..                :kkkkOOkOOxl::::::::;'.                                      .coooooooc,....                                           .lxdON
MXxoo'                                                                              .....',;;;;;;;;;;;;;;;;;;;,.               .',;;;;;;;;;;;;;;;;;;;;;;;,..                  'dOkkkkkkkkkdlcccc:;,..                                      .;lllloooool:::,.                                          .lxx0W
MXxoo'                                                                              .'...,;;;;;;;;;;;;;;;;;;;;,.              .,;:::::;;;;;;;;;;;;;;;;:::'                    ckkkkkkxxdolc;;;;;,..                                       .;llllllooooooodl.                                          .lxx0W
MXxoo'                                                                             .''..'',;;;;;;;;;;;;;;;;;;;,.            .';:cc::;;;;::;;;;;;;;;;::cc:'                   .cooolc:;;,'...',,..       ..............''''''..............;llllc;,,,,,',,;;.                                          .lxx0W
MXxoo'                                                                             .'.... .';;;;;;;;;;;;;;,,,;'.          ..,cccc::;,,,;::::::;;;::::::::.                   .,,,'''.........'''''',,,;;;;;;;;;;,,,,,,,,,,,,,,,,,,,''''',clll:;'.........'..                                          .lxx0W
MXxol'                                                                               ..     .,;;;;;;;;;;;;;;;;'    .........,,,'''''''',,;::::::::::::::;.          ..........'.......'''''''',,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;:cll:;''''''''''''''''...........                              .cddOW
MXxoo'                                                                                        .,;;;;;;;;;;;,'..  .;:c:::;'....''''',;;:;'..',,,,,,,,,,,,''....''',,,,,,,,,,,'..'''',,,,,,,,,,,,,,,,,,,,',,,,,,,,,,,,,,,,;;;;;;;;;;;;::cll:;,'''',,,,,,,;;;;;,,,,,,,,,,,'''''''...........             .lxdON
MXxoo'                                                                                         .';;;;;,'..      .,;;::cl:;,,;::ccllodddol:,'''''''''''''',;;;;;;;;;,,,,,,,,,,,,;,,,,,,,,,,,,,,,,,,,,,,,'',,,''''''''''''''',,,,,,,,,,;clc::;:;;;;:::::::::::;;;;;;;;;;;,,,,,,,,,,,,,;;;;;;;;;;,'      .lxdOW
MXxdo,                                                                                           .''...     ...';;;;;:cllllllloolllccccc:;,'''''''''',,,,;:::::;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;,,,,,,,,,,,,,,'''''',,,,,,,,,,;;;,,,,,,,,,,;;;;;;;;;;;;;::::::::::;;;;::::::::::::cc:cc,      .lxxON
MXxdo,                                                                                 ..........''''''''',,,,,,,;;::cccccccc:cc::::::::;;:::ccccclllllllc::::::::::;;;;;;;;,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,'',,,,,,,,,,,,,;;;;;;;;;:::::::::::::::::::::::::::::::::'      .lxdON
MXxdo,                                                                 ..........''',,,;;;;;::::::;;;;;;;;;,,''',;::::::::::::::::::::::::::::::::::::::;;,,,,,;;;,,,,,,,,,,,,,,,,;;,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,;;;;;;::::::::::::::::::::::::::::::::::::;;;;;;;;;;;;;;.      .cddON
MXkdo'                                               ............''''','',,,,,,,,,,,,,,,;;;;;;;;;;;;;;::::;,'',;;:::::::::::::::::;;:;;,,,,,,,',',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;:::::::::::::::::::::::::::::::::::::::::::;;;;;;;;;;;;;;;,,,,,,,,,,.      .cddOW
MXkdo'                         ...........''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,'''''',,,,,,,,,,,,,,,,,,;;;;;;;;,,,;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,''''''''',,,'''',,,,,,,,,,;;;;;;;;;;;;;;;::::::::::::::::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,.      .cddON
MXkdo'         ........''',,;;;;:::::::::::::::;;;;;;;;;;;;;;;;,,;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;::::::::::::;;;::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,.      .lxx0W
MXkdo'        .',,,;;;;;::::::::::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,;;;;;;;;;;;;;,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;:::::::::::::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,''',,.      .lxxON
MXxdo'        .',,,,,,,,,,,;;;;;;:::::::::::::::::::::::;;;;;;;;;;;:::;;:::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,;;,,,,,,,,,,,,,,,,,,;;;;;;;,,,,,,,,;;,,,,,,;;;;;;;;:::::::::::::::::::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;;;,,,,,,,;;;;;::::::;,,,,,,,,,,,,,,''''''',,,,,,,,,,,,,,,,'''''''',,,,.      .lddON
MXkdo'        .',,''',,,,,,,,,,,,,,,,;;;;;;:::::::::::::::::::::::::;;;;;;::;;;:::;;;;;:;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,;;;;;;;;;;;::::::::::::::::::::::::::::::::::::::;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,;;;;:::ccccclllooooooodol:,'''''',,,,,,'''''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,.      .cddON
MXkdd,        .',,,,,,,,,,,,,,,,,,,,,,,,,,,,;::::::::::::::::::::::::;;;;;;;;;;;;:::;;;;;;;;;;;;;;;;;;;;;;;,,,;;;;;;;;;;;;;;;;;;::::::::::cccc:::::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,;;;::cclllooooddddxxxxxxxdxdddoooooolc:,,,,,,,'''''''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;.      .cddON
MXkdo,        .';,,,,,,,,,,,,,,,',,,,,,,,,,,;::::::::::::::::::::::::::;;;;;;;;;;;;::;;;;;;;;;;;;;;;;;;;;;;;;;;;;:::::::::::cccccc::::::::::::::::::;;;;;;:;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,;;;::cclloddxxxkOOO000OOOkkkkkxxxxxddddddooooollllc:,'''''''''','''',,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;:;.      .cddON
MXxdo'        .';;;;;,,,,,,,,,,,,,,,,,,,,,,,;::::::::::::::::::::::::::::::::;;;;;;;;;:::::::::::::::::::::cccccccccccc:::::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,;;;;:ccloxxkkkkOO0000KKK0000000000OOkkkkkkxxxxdddddolc:cll;'.'::,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;:::::::::::::;.      .cddON
MXkdo,         ';;;;;;;;;;;;;;;,,,,,,,,,,,,;;;;;::::::::::::::::::ccccccc::::::::::::::::::::ccccc:::::::::::::::::::::::::::::;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,;;;::::ccllloodddxkO0KXXKK0000K0000K0000000000OOOkkxdoodxxdc,''::....,;....,:,,,,,,,,,,,,,,;;;;;;;;;;;;;;;:::::::::::::;;;;;;,.      .cddON
MXkdo,         .',,,,,;;;;;;;;;;;;;;;;;;;;,,;;;;;;;;;;;;;:::::::::::::cccccccc::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,''''''',lxxxxxxxxxxxxxxxxxkO000KKK0000KKKK00000OkkOOOxl:;;lo,.'.,oxo..,..;.':..,.,,.,c;;;;;;;;;;;;;;;::::::::::::::::;;;;;;;;;;;;;;;;;,.      .lddON
MXkdo,         .'''''''',,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::::::::::ccc::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,''''''''''''''',,,,,;dOkkxxxxxxxxxxxkkOOOO000000OOOOxolclkkc,,'ckOo..;..c'.l:cdxl.'c..;..,.',.,,.,c:;::::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,.      .lxdON
MXkdd,         .'''''''''''',,,,,,,,,;;;;;;;;,,,;;;;;;;;;;;;;;;;;;;;;;;;;;::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,'''''''''''',,,,,,,,,,,,,;dOxdxkkkkkkkkkkkOOxolccoxl;,':d;.,'.:l.;l.'xOo.'l,.c'.,lxxxl.'c'.;....;;....;c:::::;;;;;;;;;;;;,,;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,.      .lxxON
MXkdd,         .'''''''''''''','''',,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,''''''''''''''''''''''''''''''';okkxddoxxl:okkkkOkl'..,ll.'l'.l;.ol.;c.:o.'dko.'l'.c'.;:;oxo..,.':.';':l;,;:lc;;;;;;;;;;;;;;;;;;;;;;;;;;,;;,,,,,,,,,,,,,,,,;;,,.      .lxx0W
MXkxd,         .'''''''''''''''''''''',,,,''''''''',,,,,,,;;;;,,;,;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,''',,,,,,,,''''',,,''''''''''''',ox:..'.'l,.:kkkkkkxo..okl.,d,.c,.;;.;:.;o.'dko..:..c,.'.,okxl;;:lolodddddddool;;;;;;;;;;,,,,,,,,,,;;;,,;,,,,,;;;,,,,,,,,,,,,,,'.      .lxx0W
MXkxd,         .''''''''''',,''''''''''''''',,''''''''',,,,,,,,;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'',,,,,,,,,,''''''''''''''''''''''',ld, ;o;cd;.:kkkkkkko..okl.,o,.c, ...oc..,.,xkd;',;lxdlloxkkkkkxxxxxxxxxxxxddol;;;,,,,;;;;;;;;;,,,,;;;;;;;;,,,,,,,,,,,,,,,,,,,,'.      .lxx0W
MXkxd,         .,,''''''''''''''''''''','''''','',,''''''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,''''''''''''''''''',,'''''''''''''''''''''''''''''''''''''''''''''''',ld, .:okx;.:xl:okkko..lkl..;..c;.::,odc;:cdkkxxxxkkkkkkkkkxxxdodxxxxxxxxdddooc;,;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,''''''.       .lxx0W
MXkxd,         .;;;,,,,,,,,,,,,,,'''''','''''''''''','''''',,''''''''''',,,'''''''''''''''''''''''''''''''''''''''''''''''''''''''',,,,,,,,''''''''''''''',,,,,;ld, .;:lo;.;l..okkkd'.lxo:,,;ldoodxdxxkkxkkkkkxxxdxdoooccc:;:;';doolloxxdddool;,,,,,;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'''''',,.       .lxx0W
MXkxd,         .:c:::::;;;;,,,,,,,,,,,,,'''''''''''',,,,'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''',,'',,,,,,,,'''''''''''',,,,,,,,,,,,,,,,,;ld, ';..l:.','cxkkkxoodxdxxxxxxxxxxxxddxxolllc:::,;;,;',c:,'''.;oolloddxdddool;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'       .lxxOW
MXOxd,         .:::::::cc:::::;;;;,,,,,,,,,,,,,,,,,,,,,''''''''''''''''''''''','''''''''''''''''''''''''''''',,,,,,'''''',,'''',,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;ldc,',;lxxddxkkkkkxxxxxxxxxxddolllcc:;;ld;,:;'.''.,,.,,';:,,:ccldxddddddddoool;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'       .lxxOW
MXkxx,         .;:::::::::::::::::::::;;;;,,,,,,,,,,,,,,,,'''''','''''''''''''''''''''''''''''''''''''''',,,,,''''''',,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;,;;;,,,;cooooddxxxxkkkkxxdooooll::;:;;;',,,;'';od;,:,,,,;,:c:lolldddxxxxxddddddddddddl;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;'       .lxx0W
MXOxd,         .;::::::::::;;;::::::::::::::;;,,,,,,,,,,,,,,,,'''''''''..''''''''''''''''''''''''''''''''',,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;,,;;;;;;;;;;;;;;;;;clolooodddxxxxxxx:,;:,.'''',,',',,',,,,cdl:cloddddxkkkkkkkkkkkkxxxxxxxxxxddddl;',,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;;;;;;;;;;:::,.      .lxx0W
MXOxd,         .;;;;;::::;;;;;;;;;;;;::::::::;;;;,,,,,,,,,,,,,,,''''''''''''''''''''''''''''''''',,,,,,,,,,,,,;,,;;;;;;;;;;;;;;;;;,,,;;,;;,,,,;;;;;;;;;;,,,,,,,;cloooooodddddoloo;'cc'..''';:::,:lcloddxkkkxxxddddkkkkkkkkkkkkkkkkkkxxxxxxdddl;,,,,,,,,;;;;;;;;;;;;;;;;::::::;;;;;::::::::::::,       .lxx0W
MXkxd,         .;;;;;;;;;;;;;;;;;;,;;;;;;;;:;;;;;;;,,,,,,,,,,,,,,,,,,'''''''''''''',,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;,,,,;;;;,,,,,,,,;;;,,,,,,,,,,,,,,,,,,,,,,,,,;coooooodddollllod:,;cc:cloodxxkkkkkxxxxdxollllcc:okkkkkkkkkkkkkkkkkkkxxxdxxddl:;;;;;;;;;;;;;::::::::::::::::::::::::::::::::::'       .lxx0W
MXkxd,         .,;;;;;;;;;,,,;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;,,;;;;;;;;;;;;,,,,,,;;,,,,,;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;cooooddddddxxxxxxdodxxxxkkkkkkkOxolooollooodddddxxkkkkkkkkkkOOkkkkxdoolcoddddo:;;::::::::::::::::::::::::::::::::::::;;;;;;;;;'       .lxx0W
MXkxd,          '''',,,;;;;;;;;;;;;;;;;;;,,;;;;,,,,,,,,;,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,cooodddddddxxxxxxxxxxxxkkkkkkkkOkdodxxxkkkOOOOOOOkkkkkkkxxddooloxl,;::::lddddoc::::::::::::::::::::::::::::;;;;;;;;;;;,,,,,,,,.       .lxx0W
MXkxd,          .''''''',,,,,,;;;;;:;;;;;;,,;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;coooddddddxxxxxxxxxxxkkkkkOOOOOOOOOOOOOOOOOOOkxxdxdodooc:lc;,;:cdocloddooddddoc::::::::::::::::::;;;;;;;;;;,,,,,,'''''''''''''.       .lxx0W
MXkxd,          ',,''''''''''',,,,;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;cooodddddxxxxxxxxkkkkkkkkkOOOOOOOOOOOOkxdxxodolc;c;;clolcoooodddxxxkxxxxxddddoc::;;;;;;;;;;;;,,,,,,,,,,,,,''''''''''''''''''''.       .lxx0W
MXkdd,          ',,,,,'''''',,,,,,,,,,,,;;;;,,,,,,,,;;;;,,,,,,,,,,,,,''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;,,,,,,,'''',cooddddxxxxkkkkkkkOOOkkkkkkxdxdododkoc:::cl:ldddoxddxxxkkkkkkkkkkxxxddolodddol:;;;;,,,,,,,,,,,,'',,,,,,,,',''''''''''''',,,,,,.       .lxxON
MXkdd,          ';;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,''',,,,,,,,''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'',,,,,,,,,,,,,;,,,,,,,,,,,''''''''''''',codddxxxxxxkkkkkxxxddddollllcc:;lodOdlododxkOOOOOOOOOOOOOOkkkkkkd:;,.',':doool:,,,,,,,,,,,,,,,,,,,,,''''''''''',,,,,,,,,,,,,,,.       .lxx0W
MXkdo,          ';;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'',,'''',,,,,,,,,,,,,,,,,,,,,,,,''''',,,,,,,,,,,,,,,,,,,,,,,,,,'''''''''''''''''''''',ldddxxxddxddolol:c::c:::ccclloooxkO0OO0000000000OOOOOOkkxxdolloxd:'..,ollooool:,,,,,,,,,,''''''''''',,,,,,,,,,,,,,,,,,,,,,,,,,.       .lxdOW
MXkdd,          ';;;;;;;;;,,,;;,,,,,,,,,',,,,,,,,,,,,,,,,,,,',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,''''''''''''''''''''''',,,'',;ldxxxdc:lc,::',:;:::oooxddkkkOOO0000000000000OOkkxddooolllllloxxkd:..'c:lddodl;,,''''''''''''',,,,,;;;,,,,,,,,,,,,,,,,,,,,,,,'.       .lxdOW
MXkxd,          ';;;;;;;;;;;;,,;;;,,,,,,,,,,'',,,,,,,,,,,,'''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,''''''''''''',,,,,,,,,,,,,,,,;lddddo:;c::cllooodxxkkkkkOOOOOO00000OOOkkxdxkdclolloodxxkkkOOOOkd:'. ..'lddddo;'''',,,,,,,,,,,,,,,,,,,,,,,,,'''''',,,,,,,,,'''.       .lxxOW
MXkdd,          .;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,''''''''','''''''''''',,,,,,,,,,,,,,,,,,,,;,;loooddoloddxxxxxkkkkkkkkOkOOkkkxxxxollllooodkxdkkOOOOOOOOOOOOOOOx:,::ccokkkxdo:,,,,,,,,,,,,,''',,,,,,'''''''''',,,,,,,,,,,,,''.       .lxxON
MXkdo,          .,;;;;;;;;;;,,,;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'''''''''''''''''''''''',,,,,,,,,,,,,,,,,,,,;;;;;;;;;::::loooodddddxxxxxxxkxxxxxdddodoolllddddxkkOO000O00OOOOOOOOOOOOOOOOOkxOOOOOOOkxxd:,,,,,''''''''''''''''''''''''''',,,''''......          .lxx0W
MXkdo,          .,;;,,,,,,,,,,,,;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,''''''''''''''''',,,,,,,,,,,,,,,,,,,;;;;;;;;;::::::::::::::looooddddddoooloxdc:cccloooxkkkOOO0000000OkkxddoxOOOOOO000000OO00OO000OOkxdolc;''''''''''''''''''''''''''''''.......                  .lxx0W
MXkdo,          .,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,'',,,,,,,,,,,,,,,,'''''',,,,,,,,'',,,,,,,,,,,,,,,,,,;;;;;;;;;;:::::::::::::::::::;;;;:loooool::c:;:;,cxdlodxkkkOOOOO00OOOkxddolccc:::cdOOOOO00000000OOkkxdollc:;,,,,,,''''''''''''''''''''.......                           .lxxON
MXkdo,          .,,,,,,,,,,,,,,,,,,,,,,;;;;;;;::::::;;;;;,,,,,,,,,,,,,,,,,'''',,,,,''''''''''',,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;::::::::::::::::;;;;;;;;;;;;;;;,,;coooooc,,;,,,;;lxkkkOOOOOOOOOkolloolc:ccloodxxkkOOOO000OOkxdolcc:;,,',,,,,,,,,,'''''''''''''.......                                   .lxx0W
MXkdo'          .,,,,,,,,'''',,,,,,''',,,,,;;;::::::::::::;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;:::::::::::::::::;;;;;;;;;;;;;,,,,,,,,,,,,;coooooc;;,.';::lkkOOOOOOOOOO0xccoodxkkkOOOOOOkkkxxddolcc:;,,'''''''''',,,,'''''''''.......                                            .lxdOW
MXxdo'          .,,,,,,,,,,,,,,,,,,,''',,,,,,,;;;;:::::::cc::::;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;::::::::::::::::::;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,cooool:;;,,,;,'ckOOOOOOOOOO00OOO000OOOOkkxdollc:;;,,'''''''''''''''''''''''.......                                                    .lddON
MXxdo,          .',,,,,,,,,,,,,,''''''',,,,,,,,,;;;;;;;::::::::::::::;;;,,,,,,,,,,,,,,,,,,,;;;;;;:::::::::::::;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,''''''',coooolc;;;;;,',lkOOOOOO0OOO000OOkxxdolc::;,,,,,,,''''''''''''''''''......                                                             .cddON
MXxdo'          .''',,,,,,,,,,,,,,,,''',,,,,,,,,,,,,;;;;;;;;;;::;:::ccc::::;;;,,;;;;;;;:::::::::::::::;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,'''''''''',,,;coooolc;:cloodxkOOOOOOOOkxxdollc:;,,,,,,,'',''''''''''''''.......                                                                     .cddON
MXkdo'          .'''''',,,,,,,,,,;;,,,,,'',,,,,,,,,,,,,;,;;;;;;;;;;:::::::cc::::::::::::::::::::;;;;;;;;;;;;;;,,;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;codxooodxxkkkkkkkxddolc::;,,,,,,,,,,,''''''',,''''......                                                                              .cddON
MXxdo'          .,,,,,,',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;;;:::::::::::::::::::;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;loooooddddoollc::;,,,,,,,,,,,,,,,,,,,''''......                                                                                       .cddON
MXxdo'          .,;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;;;;:::;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,,',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;collcc::;;,,,,,,,,,,,,,,,,,,,,,,''.....                                                                                               .cdoON
MXxdo'           .,,,;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;;;;;;,;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,,,,,,,,,,''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;,,,,,,,,,,,,,,,,,,,,,''......                                                                                                       .cdoON
MXxdo'             ...',,,;,,,,,,,,,,,,''',,,,,,,,,,,,,,,,,,,,,,,,,,;;;,,,;;;;;;,,;;,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,''.....                                                                                                                .cddON
MXkdo'                  ...'',,,,,,,,,,,,,,,,'''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,''.....                                                                                                                         .cddON
MXxdo'                       ....',,,,,,,,,,,,,,,'''''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'......                                                                                                                                 .cooON
MXxdo'                             ...',,,,,,,,,,,,,,'''''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,''''''''',,,,,,,,,,,,,,,,,,,,,,,''......                                                                                                                                          .cddOW
MXxdo'                                  ...',,,,,,,,,,,,''''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,''......                                                                                                                                                   .cddON
MXxoo'                                      ....',,,,,,,,,,,''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,'''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,'''.....                                                                                                                                                            .cddON
MXxoo,                                            ...',,,,,,,,,,''''',,,,,,,,,,,,,,,,,,,'''''''',,,,,,,,,,,,,,,,,,,,,,,,,,''.....                                                                                                                                                                     .lddON
MXxoo;                                                 ...',,,,,,,,,'''',,,,,,,,,,,,,,,,,,',,,',,,,,,,,,,,,,,,,,,'''.....                                                                                                                                                                             'oddON
MXxodl.                                                     ...'',,,,,,,',''',,,,,,,,,,'',,,,,,,,,,,,,,,,''......                                                                                                                                                                                     :ddx0W
MNOooo:.                                                         ...',,,,,,,,,,'',,,,,,,,,,,,,,,''......                                                                                                                                                                                             'oxxkKW
MWKdddo;                                                              ...'',,,,,,,,,,,,,''.....                                                                                                                                                                                                     'oxxxONM
MMNOdddd;.                                                                 ...'''......                                                                                                                                                                                                            'okkkOXWM
MMMXkddddc.                                                                                                                                                                                                                                                                                      .:dkkkOKWMM
MMMMXOddxxo:.                                                                                                                                                                                                                                                                                  .,okkkkOKWMMM
MMMMMN0xxxxxo:.                                                                                                                                                                                                                                                                              .;dkOOOO0XWMMMM
MMMMMMWXOkxxxxxl:'.                                                                                                                                                                                                                                                                      ..;lxOOOOO0XWMMMMMM
MMMMMMMMWX0kkkkkkxdl:;'..............................................................................................................................................................................................................................................................';clxkOOOOO0KXNMMMMMMMM
MMMMMMMMMMWNK0OkkkkkkkkkxxdddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddddddddddddddddddddddddddddddddddddddddddddddddddddddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxkkOO000OOO00KXNWMMMMMMMMMM
MMMMMMMMMMMMMWNXKK0OOOkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0000000OOOOOOOOOOOOOOOOOOOOOO00000000000000000000000000000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkOOOOOOOOOOOOOOOOOO0000000000000000000000000000000000000000000000000000000000000000000000000000000000000KKXNNWMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMWWNNNXXXXXXXXXXXXXXXXXXXXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNWWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
                                     
*/

// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

import "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC1155/ERC1155.sol";
import "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/access/Ownable.sol";

contract ElToroDeOro is ERC1155, Ownable {
    
  string public name;
  string public symbol;

  mapping(uint => string) public tokenURI;

  constructor() ERC1155("") {
    name = "ElToroDeOro";
    symbol = "TORO";
  }

  function mint(address _to, uint _id, uint _amount) external onlyOwner {
    _mint(_to, _id, _amount, "");
  }

  function mintBatch(address _to, uint[] memory _ids, uint[] memory _amounts) external onlyOwner {
    _mintBatch(_to, _ids, _amounts, "");
  }

  function burn(uint _id, uint _amount) external {
    _burn(msg.sender, _id, _amount);
  }

  function burnBatch(uint[] memory _ids, uint[] memory _amounts) external {
    _burnBatch(msg.sender, _ids, _amounts);
  }

  function burnForMint(address _from, uint[] memory _burnIds, uint[] memory _burnAmounts, uint[] memory _mintIds, uint[] memory _mintAmounts) external onlyOwner {
    _burnBatch(_from, _burnIds, _burnAmounts);
    _mintBatch(_from, _mintIds, _mintAmounts, "");
  }

  function setURI(uint _id, string memory _uri) external onlyOwner {
    tokenURI[_id] = _uri;
    emit URI(_uri, _id);
  }

  function uri(uint _id) public override view returns (string memory) {
    return tokenURI[_id];
  }

}