
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Snak3y NFT
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                            //
//                                                                                                            //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdcOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl'';xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0:'''',oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx;';,';,'c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo,':c,';c;';OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc';;,;,',;,;,,xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNO:'';;,;,',;,;,''lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx:,';;;;,;,',;,;;;,'c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo,''';;;;,;,',,,;;;,'';kWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c''''',,,,,,''',,,,,'''',dNMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk;'''''',,,,,''''',,,,''''''lKMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd,''''''',,,,,''''',,,,''''''':OWMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk,'''''''',,,,,'''',,,,,''''''''cXMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx,''''''',,,,,'''',,,,,'''''''c0WMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO:'''''',;,,,'''',,,,,''''''lXMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc''''',,,,,,''',,,,,'''',dNMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo,''';;;;,;,',,;:;:,'';OWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNxc;',;;;,;,',;,;;;,'c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNO:'',;,;,',;,;,',oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl';;;;,',;;;,,xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd,':c,';c;':OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMXOkkkkOOOOOOOOOOkOkkkOkkkkOOOkOkk0WMWk;';,';,'lKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMW0c''''''''''''',''',;,';,;,''''':d0WMMW0c'''',oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMWk;''''''''''''',::,,,:;,:;;;,'''lKMMMMMMMXl'';kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMNd,''''''''',,,,,',:;,,,,''';c:',dNMMMMMMMMMNxlOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMKl''''''',,,,,,,,,,,,,,',,,,;;;';kWMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMWO:'''',,,,,,,,,,,'''''',,;,,,;;'c0WMNOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkONMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMNx;',;,,,,,,,,,'''''''',,,,;:,'''oXMMMWkl;''''',,;,',;'''','''''''''''''lKMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMXo,'',::,,,,'''''''',,,,,,,,,;,',xNMMMMMWW0c'',,;;;:,;;,,,::,,'''''''''''':OWMMMMMMMMMMMMMM    //
//    MMMMMMMMKc';;,,,;,,,''''',,,,,,,,,,,'''':OWMMMMMMMMMXo',::,''',,,,;;,,,,,,,''''''''';xNMMMMMMMMMMMMM    //
//    MMMMMMWO:';;;,,,,',,,,,,,,,,,,,,'''''''cKMMMMMMMMMMMMNx,,;;;,,,,',,,,,,,,,,,,,,'''''',oXMMMMMMMMMMMM    //
//    MMMMMNx,':c;''',,,,;:,',,,,,''''''''',oXMMMMMMMMMMMMMMWO:';;,,;;,,'''''',,,,,,,,,,'''''cKMMMMMMMMMMM    //
//    MMMMXo,'',;;;:;;:;,,::,''''''''''''';xNMMMMMMMMMMMMMMMMMKc''';:;,,,,'''''''',,,,,,,,;;,':OWMMMMMMMMM    //
//    MMW0c''''',;,;',;,''',''''''''''''':OWMMMMMMMMMMMMMMMMMMMXo,';;,,,,,,,,,''''''',,,,;:;,'',xNMMMMMMMM    //
//    MMWKkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOXMMMMMMMMMMMMMMMMMMMMMMNx;'''',,,,,,,,,,,''''',,,,,,,;,'oXMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO:''''''',,,,,,,,,,,,,,',,,,;:;'c0WMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl'''''''''',,,,,';:;,,,,'',;c;';kWMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd,'''''''''''',;:;,,;:,;:;;;,'',dNMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk;''''''''''''',''',;',;,;,'''''lKMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMWNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMX000KWMMMMMMMWNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMKdc::;:::cxNMMMMMMMMMMMMMMMMMMMMMMMMMMx,''lXMMMMMW0oc::;::co0MMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMWd''';ol,..,kW0OOOK0OO0NMMWX0OOK0OOOOXWx'''lXN0OOO0c.'.:d:'''oK0OOONMN0OOONMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMWd''.:0KxxxkXXc.'';,''':0Nx,''';,''',xWx''.lKx,''c0OxxdOXo''.oKl'''dWO;'':KMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMWk,..';::clxXKc.''ok:'''xXc.''oOc''''dWx'''co,''cKMMMMOc;,'',kWO;'.c0d'',xWMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMNOxdxxo,'',kXc.',kXc.''xXc.''xNl.'''dWx''',,'',kMWNXX0kxc'''dNWd'.,l:''cXMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMWOccco0k;.',kXc.',kXc.''xXc.''d0c.'''dWx''':l,''lXXo;:;dKo'''lNMXc''''.,kMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMO;''',,'.':0Kc..'kXc.''xNd''',;,..''dWx'..l0o'.'lKd'''','.',xWMM0c,'''lNMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMWKkxxxxxxkXWNOxxxKWOxxxKMN0xxxOkxxxxKWKxxxONXkxxxKN0kxxxxxk0NMW0xo;'.:0MMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd;;;cdKWMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXXNWMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                            //
//                                                                                                            //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract SNK is ERC721Creator {
    constructor() ERC721Creator("Snak3y NFT", "SNK") {}
}
