
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Memories
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                              ...,;;::::::::::::    //
//          ...............................''''''''''''',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,''''''''''''''.................                                                                                                                                                                          ...';;;;::::::::::    //
//    ccc:cccccccccccccccccccccccccllllllllllllllllllcccccccccccccccccccccccccccccccccccccccccccccccccccccccccc:::::::::;;;;;;,,,,,,,''''''...................................                                                 ...................'''''',,,,,,,,,;;;;;;;;;;;;;;;;,,,,'''''.......'.';;;;;;::::::::    //
//    lllllllllllllllllllllllllllcccllllcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc:::::::::::::::::::::::::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::::::::ccccccccccccccllllllcccccccccccccccccccccccccccccccccccccccccccccccccccccc:;;;;;:    //
//    lllllllllllllllllllllllllllcccllccllcccccccccccccccccccccccccccccccc:,,;cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc::ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccclcccccllllllllllclccccccccccccccccccccccccccccccccccccccccccc;;;;;;    //
//    llllllllllllllllllllllllllllccllllllcccccccccccccccccccccccccccccc:;,',:ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc::cc:::::;,,,,,;;;;:ccccc::;;:cccccccccccccccccccccccccccccccccccccccccccccccccccllllllllllllllllllllllllllllllllllllllllllllllllllllcccccccccccccccccccccccccc;;;;;;    //
//    lllllllllllllllllllllllllllllllllllllllllccllllllllccccccccccccccc;,,';cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc:;,,,,'''''...''''...';cc:,''..;ccccccccccccccccccccccccccccccccccccccccccccclllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllccccccccccccccccccccccc;,,,,;    //
//    lllllllllllllllllllllllllllllllllllclllllllllllllllllllccccccccc:;,,',ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc;'''.....''......'....,;;'...,:ccccccccccccccccccccccccccccccccccccccccccllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllcccccccccccccccccccc:,,,;;    //
//    llllllllllllllllllllllllllllllllllllllllllllllllllllllllllccccc:,,,',clcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc,''...',,,,;;;;;;;,'.......';cccccccccccccccccccccccccccccccccccccccccccclllllllllllllllllllllllllllllllllllllllllllllllllllllllllllccllllllllcccccccccccccccccll:,,,;;    //
//    llllllllllllllllllllllllllllllllllllllllllllllllllllllllllcccc:,,,',clllllccccccccccccccccccccccccccccccccccccccccccccccccc:::ccc::cc,''...;cccccccccccc:'.....,:cccccccccccccccccccccccccccccccccccccccccccclllllllllllllllllllllllllllllllllllllllllllllllllllllllll:;,,clllllllllllccccccccccccllllc;,;;;    //
//    lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll:,','':lllllllcccccccccccccccccccccccccccccccccccccccccccccccccccccc::cc,...'.,ccccccccccccc:'..,:ccccccccccccccccccccccccccccccccccccccccccccllllllllllllllllllllllllllllllllllllllllllllllllllllllllc;,',;:cllllllllllllcccccccccccclllc;,;;;    //
//    llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllc;''''';;:c:clllccccccccccccccccccccccccccccccccccccccccccccccccccccc:cc:,..''',:cccccccccccccc,,ccccccccccccccccccccccccccccccccccccccccccccccclllllllllllllllllllllllllllllllllllllllllllllllllllll:,'',,,,:cllllllllllllllcccccccccccclc:;;;;    //
//    llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllc;,,,'''',,';clcclcccccccccccccccccccccccccccccccccccccccccccccc::::cccc:,..''',:ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccllcllllllllllllllllllllllllllllllllllllllllllllllc;''',,,',clllllllllllllllllllccccccccclc;''',    //
//    lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllcc::,,,,;,':clllllccccccccccccccccccccccccccccccccccccccccccccccccccccc:,..''.';cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccllllllllllllllllllllllllllllllllllllllllllllllllc;'.'''',,;cllllllllllllllllllllllccccccclc;...'    //
//    llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllc,,,',',clllllllcccccccccccccccccccccccccccccccccccccccccccccc:cccccc,..''..,cccccccccccccccccccccccccccccccccccccccccccccccccccccccccclllllllllllllllllllllc:,,:cllllllllllllllllllllllllc,'..''',',:clllllllllllllllllllllllllccccccl:'..'    //
//    llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll:,,'',';lllllllllcccccccccccccccccccccccccccccccccccccccc::::::::;;;:'..,,'',:cccccccccccclllcccccccccccccccccccccccccccccccccccccccccclllllllllllllllllll:;''',,;:lllllllllllllllllllll:,'....'''',:lllllllllllllllllllllllllllllccccl:'..'    //
//    llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll:''',',clllllllllllcccccccccccccccccccccccccccccccccccc:,'..............'',,',,;;;;::::;;;;;;:::ccccccccccccccccccccccccccccccccccccclllllllllllllllllllc,..;;'.,,';cllllllllllllllllc;'..'...''',;:clllllllllllllllllllllllllllllllcclc,..'    //
//    lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllc;''''.;lllllllllc:;:cllccccccccccccccccccccccccccc:::;'.............'',,,,;;;;;;;:c:::::::::;;;;;;;;;:::ccccccccccccccccccccccccclccclllllllllllllllll:,...',',;,'''';clllllllllllc:,.....''''',:clllllllllllllllllllllllllllllllllllllc,..'    //
//    lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll:,,''''clllllllc;'''',;:ccclccllccccccccccccc:::;,''..............'',,'',,,;,,,,,;;;:::;::::::::::::;;;;;;;;;:cccccccccccccccccclllccclllllllllllllllc,.....''';;,'.''.';clllllllc;'....',,,',;clllllllllllllllllllllllllllllllllllllllll;...    //
//    lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll:,,''.;lllllll:'........;clcccccccccccccc:::;,'....................',,''',;;;;,,,,,,,,'',,,,,,,,,,;;::::::::;;;;;;:ccccccccccccccclccllllllllllllllc,......',,:llc:;'....';cll:,'...'','',;;cllllllllllllllllllllllllllllllllllllllllllll:...    //
//    oooollllloollllllllllllllllllllllllllllllllllllllllllllllllllll;,,'.'clllllc,..'.....'..':cccccccccccc::;,'....  .......................';::::::::::;;;;;,,,,,,,,,,;;;;;;;;;:;;;;;;;;::ccccccccclllllllllllllllll:........,,:lllllll:,..'..''...',,'',;:clllllllllllllllllllllllllllllllllllllllllllllll:...    //
//    ooooooollllllllllllllllllllllllllllllllllllllllllllllllllllllll;,,'.,llllc;'.'',;:;,'.....,:clcccccc:;,'...   ...........................';;;;;;;;;;;;;;;;;;;;;;;::;:;;;;,,,,,,,;;;;;;;;;;:ccccccllllllllllllll:,...'....,,;llllllllll:'..'.'',,,,,;:cllllllllllllllllllllllllllllllllllllllllllllllllll:...    //
//    oooooooooooolllllloolllllllllllllllllllllllllllllllllllllllllll:,,'.;llc;'.'',:cllllc;,.....';cccc:,'...   ...........................,,,',;:;;;;;;;;;;;;;;;;;;,,,;;;;;:::;;;;;;,,,,,;;;;,,,,;::cclllllllllll:'...'''...'';llllllllllllc;'..''',;:clllllllllllllllllllllllllllllllllllllllllllllllllllll:...    //
//    ooooooooooooooollllllllllllllllllllllllllllllllllllllllllllllll:,,'.;c;'.''';clllllllllc;.....'::,...     ...........................,;,'',;;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,;;;;;;;;;;;;;;;;;;,,,,,;:clllllll:'...,,,'...'',clllllllllllllc::;;::cllllllllllllllllllllllllllllllllllllllllllllllllllllllll:...    //
//    ooooooooooooooooooollooolllllllllllllllllllllllllllllllllllllll:;,'',,'''',:lllllllllllllc'........    ............................',,'',,;;;;;;;;;;;;::;;;;;;;;;;;,;;;;,,,,,,;;,;;;;;;;,;;;;:;;,,;;::cllc,...',,,'...,',cllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll:...    //
//    ooooooooooooooooooooolooollllllllllllllllllllllllllllllllllllllc;,,,,'''',:lllllllllllllll:;;'...    ............................,;;,'',;;;;;;;;;;;;:::;;;;;;;;,,,,,;;;;;:;;;;;;;;,,,,,,,,,,;;;;;:::;;;;;','.',,,'...,,';lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll:...    //
//    oooooooooooooooooooooooooooollllllllllllllllllllllllllllllllllll:;,'''',;clllllllllllllllc:,...    ............................',,,'',,;;;;;,,;;;;;;;;;;;;;;;;;;;,;;;::::;;;;;;::;;;;,,,,,,,,;,,;;::::::,,,.';,;,'..,;',clllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll:...    //
//    oooooooooooooooooooooooooooooooooollllllllllllllllllllllllllllll:,'''';clllllllllllllllc:,...     ..........................',;,''',;;;;;;;,;;;;;;;;::::::;;;;;;;;;;;::::;;;:::;;;;;;;;:;;;;;;;;;;;;;:ccc:;''',;:,..:,':llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll:...    //
//    oooooooooooooooooooooooooooooooooooooollllllllllllllllllllllllllc,',;cllllllllllllllllc;....   ..........................',;;,''',;;::;::;;;;;;;;;;;:::::;;;;;:;;;::::::;;,,;;;;;;;;;;;;;,,;:;;;;;;;;;::::::;,,,,'.,c;;lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll:.      //
//    ooooooooooooooooooooooooooooooooooooooolloollllllllllllllllllllllc:cllllllllllllllllllc,....  .........................',;;,,,,,;;;;;;;;;;;;;;;:::::::::;,,,,,,,,,;;;;,,,,,,;;;;;;;;;;;;;,;;;;::::;;;;,;;;;;::c:;'',;;:lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll;.      //
//    loooooooooooooooooooooooooooooooolcccccccccllllllllllllllllllllllllllllllllllllllllllc,.............................',;:;,,,,,,;;::::::::::;;;;;;;;;;,,,,,,,,,,,;;;;;;,,,,,;;;;;;;;;;;;;;;::::::cccc:::::;;,;:ccc:;,',;cclllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll:.      //
//    looooooooooooooooooooooooooooolc:;;;,,,,,,,,;:cllllooolllloollllllllllllllllllllllllc,............................',,;,,,,;;:::c:ccc::;;;;;,,;;;;;;:::;;;:;;;;;;;;;::;;;;;:c:;;:::::;;;;;::::::::cccccccc::;;,;;::::;,,;;:clllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll:...    //
//    loooooooooooooooooooooooooool:;,,',,,;;;,,,'''',;;;:cclllooollolooollooolllllllllll:'...........................',,,,,,;::::::::;;;;,,,,;;;;::cc:::::;;:::;;::::::c:::;,;cc:;,:ccc::;;;::::::::c::::::::::;::;;;;:cc:;;;;;;cllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll:...    //
//    ooooooooooooooccc::cooooodoc;,'..,;:::;;;;;;;;,,,,'',,;;:cllloooooooooooooooolllll:.........................'',,;,,,,;;::;;;,,,,,;;;;::::;::cclc:::c:::::;::cc::ccc:c:;;ccc;;:clc:;;;;::::::::;;:::::::::::;,;;;;;;;,,;;;;::clllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllc...    //
//    ddoodddddddddoc;;;;,;clodl:'....,loooollcccc:::;,,,'''',,,;;::ccllooooooooooooloo:......................'''',,,,,,,,;;;;;;,,;;:::cc::ccc::::ccc:::::::::;;:cc::clc:::;;:c::;;:ccc:::;::cc:;:::cc:;,,;::::::;;;;;;;;;;;,;:,,::cllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllc...    //
//    ddddddddddddddolc::;;,,::,'.''',looooooooooooooollcc::;;;,,,,,,,;:cccloooooooool:......................',''',,,,;;;;;;;;;:;:cccccc:::cc:::::ccc::::c::;;::c:::ccccc;,;ccc:;:::::::::::::;;:cccccc:;,,;;:c::;::::::::;,,,,;;;,,;cllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllc...    //
//    ddddddddddddddddddolc:;,,'',,,:ododdoooooooooooooooooooolcc::;,,,,,,,cooooooool,....................'''''',,;;;;;;;;;::cc:cllccc::cc:cc:::cccc:::::c:::::cc::cc:::;,;cc::;:::::::::c:;:::::::ccc:::;;;;;;;::;:::::::;;,'',;;;,';clllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllc...    //
//    dddddddddddddddddddddolc:;;,,:odddddddddddooooooooooooooooool:,''',;cloooooooc,.....'.............,,'.',,;;;;:::::::ccccccllc:::::c:c::;:cccc::::::::cc::cc:cc:::;;:cc::;;::::::::::;::::cccc::::::cccc::;:;;;:::::::;;;,,,;;;,,,:clllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllc'..    //
//    dddddddddddddddddddddddddoc:cdddddddddddddddoooooodooooolc:;,..',:loooooooooc'....''............''''',;;;::::::::::cclc:cllc:::::cc::;:::ccc::::cc::cc:::::ccc::;;:c::;;;:::::::::::::::ccc::::::::ccc:cc::::::;;;:;;;;:;,,,;:;,;;;:llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllc'..    //
//    ddddddddddddddddddddddddddddddddddddddddddddddooddddolc;,'''',;:loooooooooo:.....,'............''',;;;:::c:cccc::ccclccccccc:::cccc:;:::ccc:;::c:::::ccc::cc::;;;:c::;;::::::;;:::ccccccc:::;:::::::::ccccccc::::;;;;,;;;;;,,;;;;;;,:clllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll'..    //
//    dddddxxxxdddddddddddddddddddddddddddddddddddddddddoc:;,'''',,:cloodoooooodc'....,'............',;;:::::::ccllc:cccclcccccccc::cccc:::::ccc::::cc:;:ccccc:cc::;;;:c:;::::c::;;;:cllcc:cc:::c::c::::;;:ccc:::::;;::;;;;;;::c:;,,,;;::;;::clllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll'..    //
//    ddxxxxxdddddddddddddddddddddddddddddddddddddddddddoc;:;,''',,,,;;:cclloodl,....''..........',;cc::::::ccllllcccccclc:ccclcc::cccc::::::cccc::cc::::clc::c:::;;::::;;:::::;;;:cccc::ccc::clc::c:::;;:cc:::::::;;;;;;;:::::;:::;,,;:cc;;;;;clllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll,..    //
//    ddxxxxdddddddddddddddddddddddddddddddddddddddddddddooc:;;,,,,,,,,,',,;;::,............''',::ccc:::::ccclllcc:cccccc:cccllc:::cc::::::::::::::c::::clc:::c:;;::::;;;::::;;;:cllc:c:::::cc::;:::::;::ccc::::::::;:::;;;:c:::ccc:;;,;:ll;,;:;:clllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll,..    //
//    ddxxdddddddddddddddddddddddddddddddddddddddddddddddodooollcc:;,,',,;,,,,'...........'''';clllc::::ccclllllc:::ccccccclllcc::c:::c::::ccc:::c:::c:ccc::c::;;:::;;::;:::;;:cccc::cc:;;::;;:;:::;;:::::::ccc::::;;:::;:::::::ccc:;;;;;:lc;,:c::cllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll,..    //
//    dddddddddddddddddddddddddddddddddddddddddddddddddddoodooooodoolc:;;;;;,,...........'''';clooc:::ccllllcllc::::::cclllllcc::c::ccc::::cc:;:c:::c:ccc:::::;;::;;::::;;;;:cllcc::::::cc::cccc::;:::;:cccccc:::::::::;;;;:;;:ccccc:::;,,;cc:,,::;:cllllllllllllllllllllllllllllllllllllllllllllllllllllllllll,..    //
//    ddddddddddxxddddddddddddddddddddddddddddddddddddddddooooodooooooooool:'...........''',:loolccccclllollllc;;:::::clllllcc::c:ccc::::cccc;;:c::::clc:::;;;:::;:::;;;,;::ccc::::;;:::c:::cc:::;;::::cccc:::::::::;;;;;::::::::c:::::c:;,:cc;,,:c:;clllllllllllllllllllllllllllllllllllllc::cllllllllllllllll,..    //
//    ddddddddddxxddddddddddddddddddddddddddddddddddddddddddddddddooooooddl,..........'''',codolclcclllllllolc:;:cc:cccllllll:;::clc::::cccc:;:::cc:clc::;;::::;:::;;;;,;clc:;;::::::c::::;:::::;:::ccccc:::;::::;;;;,;;;:;::ccc:;;:clcc::;,;:::'':cc::clllllllllllllllllllllllllllllllll:::::cllllllllllllllll;..    //
//    ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddoooooc'..........'''';codolclcclllllcclc:;;:c:ccccclllllc:::clc::::cccc:;:c:cc:cl:::;:cc::;;;;;,,,;::c::::;:c:::;;;::;;::::::::::::;;;;;;;;;;;;;;;;;:ccccc:::;;ccc:::cc:;;::;,,:ccc;:lllllllllllllllc:::llllllllllc;,;c:;clllllllllllllllll:..    //
//    ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddooooc'....''.'..'''';lodolllclllllllolc;;:cc::cccccclolc:::clc::::cccc::cccccccc:;;;:cc::;;;;;,,;;:c::::::::::::;;;;;::::::ccc::::;;,,;;;;;:::;;;;;;;:::;;;:;,,;;;::::::::cc;;,;:cll::;;:cclllllc;,''..';lllllllc;',;;,;cllllllllllllllllll:..    //
//    ddddddddddddddddddddddddddddddddddddddddddddddddddddddddddoooooooc'....''''''''',:looolllllllllllol:;;:ccc:cccccccllc:::clc:::ccccc::ccccc:cc:;,:cc::;;::;;;;;::;::;:::;;;:cc;;::::::::cc:::::::::::::::::::;;;;,;;;;;;;;:;,,;;:::::clcc:cc:;,,:cclc,,;:cll                                                     //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract MEM is ERC721Creator {
    constructor() ERC721Creator("Memories", "MEM") {}
}
