
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Gweifields
/// @author: manifold.xyz

import "./ERC721Creator.sol";

//////////////////////////////////////////////////////////////
//                                                          //
//                                                          //
//                                                          //
//                                                          //
//    BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB    //
//    BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBG    //
//    BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBG    //
//    BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBG    //
//    BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBG    //
//    BBBBBBBBBBBBBBBBBBBGBBBBBBBBBBBBBBBBBBBBBBBBBBGBBB    //
//    BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBG    //
//    BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB    //
//    BBBBBBBBBBBBBBBBBBGGGGGGGGGGGGGBBBBBBBBBBBBBBBBBBG    //
//    BBBBBBBBBBBBBBBBBBGGGGGGGGPGGGGGGBBBBBBBBBBBBBBBBG    //
//    BBBBBBBBBBBBBBBBGGGGGPPPPPPPPPGGGBBBBBBBBBBBBBBBBG    //
//    BBBBBBBBBBBBBBBBGGGGPPPPPPPPPGGGGGBBBBBBBBBBBBBBBB    //
//    BBBBBBBBBBBBBBBBBGGGPPPPPPPPPGGGGGGBBBBBBBBBBBBBBG    //
//    BBBBBBBBBBBBBBBBBGGGGPPPPGPGGGGGGGBBBBBBBBBBBBBBBG    //
//    BBBBBBBBBBBBBBBBBBBGGGGGGGGGGGGGBBBBBBBBBBBBBBBBBG    //
//    BBBBBBBBBBBBBBBBBBBGBGGGGGGGGBBBBBBBBBBBBBBBBBBBBG    //
//    BBBBBBBBBBBBBBBBBBBGBBBBBBBBBBBBBBBBBBBBBBBBBBGBBB    //
//    BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBG    //
//    BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB    //
//    BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBG    //
//    BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBG    //
//    BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBG    //
//    BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB    //
//    PPGGPPPPPPPPPPPPGPPPPPPPPPGPPGGPPPPPPPPPPPPGPPPPPP    //
//                                                          //
//                                                          //
//                                                          //
//////////////////////////////////////////////////////////////


contract gweiflds is ERC721Creator {
    constructor() ERC721Creator("Gweifields", "gweiflds") {}
}
