
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: AIA Artwork
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                //
//                                                                                                                                //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMWNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMM0:',xWMMMMMMMMMMMMMMMMMMMWOlcccccccccccccccccccoKMMMMMMMMMMMMMMMMMMMMXo''lXMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMK;   .OMMMMMMMMMMMMMMMMMMMWk;'..            ..,,c0MMMMMMMMMMMMMMMMMMMWo.  .oNMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMNl     ;KMMMMMMMMMMMMMMMMMMMMWNX0x:.       .d0XWWMMMMMMMMMMMMMMMMMMMMWk.    .xWMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWd.      cXMMMMMMMMMMMMMMMMMMMMMMMMX:       oWMMMMMMMMMMMMMMMMMMMMMMMM0'      'OMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMk.       .oWMMMMMMMMMMMMMMMMMMMMMMMNc       oWMMMMMMMMMMMMMMMMMMMMMMMX:        ;KMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMK,      '. .kWMMMMMMMMMMMMMMMMMMMMMMNc       oWMMMMMMMMMMMMMMMMMMMMMMNl  ..      lNMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMXc      :0d. ,0MMMMMMMMMMMMMMMMMMMMMMNc       oWMMMMMMMMMMMMMMMMMMMMMWx. 'Ok.     .dWMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMNo.     '0MNc  :XMMMMMMMMMMMMMMMMMMMMMNc       oWMMMMMMMMMMMMMMMMMMMMWO. .xWWd.     .OMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMWk.     .kWMMK;  lNMMMMMMMMMMMMMMMMMMMMNc       oWMMMMMMMMMMMMMMMMMMMMK;  oNMMNl      ;KMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMM0'     .oNMMMMO' .xWMMMMMMMMMMMMMMMMMMMNc       oWMMMMMMMMMMMMMMMMMMMXc  :XMMMMX:      cXMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMX:      cXMMMMMWx. 'OMMMMMMMMMMMMMMMMMMMNc       oWMMMMMMMMMMMMMMMMMMNd. ,0MMMMMM0'     .oWMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMNl      ;KMMMMMMMNl  ;KMMMMMMMMMMMMMMMMMMNc       oWMMMMMMMMMMMMMMMMMWk. .kWMMMMMMWk.     .kWMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMWx.     'OMMMMMMMMMX:  cXMMMMMMMMMMMMMMMMMNc       oWMMMMMMMMMMMMMMMMM0, .dWMMMMMMMMWo.     ,0MMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMO'     .lKXXXXXXXXXXx. .oWMMMMMMMMMMMMMMMMNc       oWMMMMMMMMMMMMMMMMX:  ;OXXXXXXXXXXO;      :XMMMMMMMMMMMM    //
//    MMMMMMMMMMMMK;       .............   .kWMMMMMMMMMMMMMMMNc       oWMMMMMMMMMMMMMMMNl   ..............       lNMMMMMMMMMMM    //
//    MMMMMMMMMMMXc      'lllllllllllllll;  ,0MMMMMMMMMMMMMMMNc       oWMMMMMMMMMMMMMMWd. .:llllllllllllllc.     .xWMMMMMMMMMM    //
//    MMMMMMMMMMWd.     ,0MMMMMMMMMMMMMMMXc  :KMMMMMMMMMMMMMMNc       oWMMMMMMMMMMMMMMO. .dWMMMMMMMMMMMMMMWx.     'OMMMMMMMMMM    //
//    MMMMMMMMMWk.     .kWMMMMMMMMMMMMMMMM0,  lNMMMMMMMMMMMMMNc       oWMMMMMMMMMMMMM0,  cNMMMMMMMMMMMMMMMMNl      ;KMMMMMMMMM    //
//    MMMMMMMMM0,     .oNMMMMMMMMMMMMMMMMMWx. .dWMMMMMMMMMMMMNc       oWMMMMMMMMMMMMX:  ,0MMMMMMMMMMMMMMMMMMK;      cNMMMMMMMM    //
//    MMMMMMMMX:      :XMMMMMMMMMMMMMMMMMMMXc  .kWMMMMMMMMMMMNc       oWMMMMMMMMMMMNl  .dWMMMMMMMMMMMMMMMMMMMO'     .dWMMMMMMM    //
//    MMMMMMMXc      '0MMMMMMMMMMMMMMMMMMMMMx.  .xNMMMMMMMMMMX:       lNMMMMMMMMMMXl.  '0MMMMMMMMMMMMMMMMMMMMWd.     .xNMMMMMM    //
//    MMWNXOo'       'xKXNWWMMMMMMMMMMWWNX0d,    .;d0XNWWWNX0l.       .ckKXNWWNKOl'    .ckKXNWWMMMMMMMMMMWWNX0l.      .;x0XWMM    //
//    MXo'.            ..';kWMMMMMMMMNo,'.          ..',,,'..            ..',,'.          ..';kWMMMMMMMMNo,'..           ..;OW    //
//    MNkoooooooooooooooood0WMMMMMMMMNkooooooooooooooooooooooooooooooooooooooooooooooooooooood0MMMMMMMMMNkoooooooooooooooood0M    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                                                //
//                                                                                                                                //
//                                                                                                                                //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract AIA is ERC721Creator {
    constructor() ERC721Creator("AIA Artwork", "AIA") {}
}
