
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Kontak
/// @author: manifold.xyz

import "./ERC721Creator.sol";

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                             //
//                                                                                                                                                             //
//                                                                                                                                                             //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJX//|!:::::::::::::::::::!|//XJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ!l:::::::::::::::::::::::::::::::::l!JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJz/:::::::::::::::::::::::::::::::::::::::::::::/zJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJnI:::::::::::::::::::::::::::::::::::::::::::::::::::InJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ)i:::::::::::::::::::::::::::::::::::::::::::::::::::::::::i)JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJvI:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::IvJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJY{;:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;{YJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ<:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::<JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ}:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::}JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ(:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::(JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJx;:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::;xJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ(:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::(JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJYl:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::lYJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJf;:::::::::::::::::::::::::::::::::::::::::::::::::::::::n/;:::::::::::::::::::::::::::::::::;fJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJf:::::::::::::::::::::::::::::::::::::::::::::::::::::::IrJJ[:::::::::::::::::::::::::::::::::::fJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJ{::::::::::::::::::::::::::::::::::::::::::::::::::::::::UJJzvJ?::::::::::::::::::::::::::::::::::{JJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJf;::::::::::::::::::::::::::::::::::::::::::::::::::::::-UJJJJJJ?::::::::::::::::::::::::::::::::::;fJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJX::::::::::::::::::::::::::::::::::::::::::::::::::::::fJJJJJJJJJI::::::::::::::::::::::::::::::::::::XJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJY::::::::::::::::::::::::::::::::::::::::::::::::::::::|JJJJJJJJJJ::::::::::::::::::::::::::::::::::::::YJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJ_:::::::::::::::::::::::::::::::::::::::::::::::::::::>JJJJJJJJJJ(::::::::::::::::::::::::::::::::::::::_JJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJf:::::::::::::::::::::::::::::::::::::::::::::::::::::{JJJJJJJJJJJz:::::::::::::::::::::::::::::::::::::::fJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJI::::::::::::::::::::::::::::::::::::::::::::::::::?JJJJJJJJJJJJJJJr::::::::::::::::::::::::::::::::::::::IJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJj::::::::::::::::::::::::::::::::::::::::::::::::::::[JJJJJJJJJJJJJJr:::::::::::::::::::::::::::::::::::::::jJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJ:::::::::::::::::::::::::::::::::::::::::::::::::::::!vJJJJJJJJJJJJJu]:::::::::::::::::::::::::::::::::::::::JJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJx::::::::::::::::::::::::::::::::::::::::::::::::::;{zJJJJJJJJJJJJJJJX~:::::::::::::::::::::::::::::::::::::::xJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJ-::::::::::::::::::::::::::::::::::::::::::::::I<tJJJJJJJJJJJJJJJJJJJr::::::::::::::::::::::::::::::::::::::::-JJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJ-:::::::::::::::::::::::::::::::::::::::::::::}xJJJJJJJJJJJJJJJJJJJJJr::::::::::::::::::::::::::::::::::::::::-JJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJU_:::::::::::::::::::::::::::::::::::::::::<(JJJJJJJJJJJJJJJJJJJJJJJJJr::::::::::::::::::::::::::::::::::::::::_UJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJc>:::::::::::::::::::::::::::::::::::::::}nJJJJJJJJJJJJJJJJJJJJJJJJJJJr::::::::::::::::::::::::::::::::::::::::>cJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJc>::::::::::::::::::::::::::::::::~+(JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJr:::::::::::::::::::::::::::::::::::::::::>cJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJc>::::::::::::::::::::::::::::IxXJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJv?I::::::::::::::::::::::::::::::::::::::::>cJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJY+::::::::::::::::::::::::::+JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJc<::::::::::::::::::::::::::::::::::::::::::+YJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJ-::::::::::::::::::::::::<XJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ/;;::::::::::::::::::::::::::::::::::::::::::-JJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJ-::::::::::::::::::::::iYJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJc)I::::::::::::::::::::::::::::::::::::::::::::-JJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJt:::::::::::::::::::::>YJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJXi::::::::::::::::::::::::::::::::::::::::::::::tJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJ:::::::::::::::::::ivJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ~:::::::::::::::::::::::::::::::::::::::::::::::JJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJ{::::::::::::::::lzJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ1:::::::::::::::::::::::::::::::::::::::::::::::{JJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJ;:::::i+>>>+-?{XJJJJJJJJJJJJJJJJJJJJJJJJJJt::::}JJJJj:jJJJz>::::::::::::::::::::::::::::::::::::::::::::::;JJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJt::::::-JJJJJJJJJJJJJJJcrJJJJJJJJJJJJJJJJn!::::+XJJJu::JJJu:::::::::::::::::::::::::::::::::::::::::::::::tJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJX~:::::;1fXJJJJJJJJJY1;(JJJJJJJJJJJJJJJJJ-:::::!cJJJx::JJJu::::::::::::::::::::::::::::::::::::::::::::::~XJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJv::::::::::_-<<i!l:::vJJJJJJJJJJJJJJJJJU:::::::uJJJ!::JJJc!:::::::::::::::::::::::::::::::::::::::::::::vJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJf:::::::::::::::::JJJJJJJJJJr]JJJJJJJY::::::::uJJJ([[fJJJ{::::::::::::::::::::::::::::::::::::::::::::fJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJ|::::::::::::::::JJJJJJJJi:IYJJJJJJl:::::::::uJJJJJJJJJJxI::::::::::::::::::::::::::::::::::::::::::|JJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJ?:::::::::::::::+JJJJc<::+UJJJJc<::l{vJJJu/YJJJJJJJJJJJJJX1}}}}}}-::::::::::::::::::::::::::::::::?JJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJ[::::::::::::::<JJJzI::::tJJJU::lUJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJxI:::::::::::::::::::::::::::::[JJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJ|:::::::::::::zJJz<:Ii;:[JJJ/jJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJc>::::::::::::::::::::::::::::|JJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJu:::::::::::?JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJj::::::::::::::::::::::::::::uJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJU+:::::;?)uJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJt::::::::::::::::::::::::::+UJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ{:(JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ::::::::::::::::::::::::::{JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ::::::::::::::::::::::::_YJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ:::::::::::::::::::::::JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ(:::::::::::::::::::lnJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJx;:::::::::::::::lcJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJr!:::::::::::{JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJi:::::::IJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJi:::}fJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJijJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//    JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ    //
//                                                                                                                                                             //
//                                                                                                                                                             //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract AK is ERC721Creator {
    constructor() ERC721Creator("Kontak", "AK") {}
}
