
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Sean Higgins
/// @author: manifold.xyz

import "./ERC1155Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                //
//                                                                                                                                //
//                                                                                                                                //
//    SEAN-HIGGINS-ARTOOOOOOOOOOOOZZZZZZZZZZZZZZZZZZ$$$$$$$$$ZZZZZ$$$$$$$77777777IIIIII++++++++++++++==+=====++++++++??????III    //
//    OO888OOOOOOOOOOOOOOOOOOOOOOOOOZZZZZZZZZZZZZZZZ$$$$$$$$$ZZZZZZZZ$$$777777777IIII????++++++++++++++++++++++++++?????????II    //
//    OOO8OOOOOOOOOOOOOOOOOOOOOOOOOOZZZZZZZZZZZZZZZ$$$$$$$$$$ZZZZZZZZZ$$$77777777III?+?????+++++++++++++++++++++++??????????II    //
//    OOOZO8OOOOOOOOOOOOOOOOOOOOOOOOOZZZZZZZZZZZZZZ$$$$$$$$$$$ZZZ$$$$Z$$$777777777??????????++++++++++++++++++++???????????III    //
//    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOZZZZZZZZZZZ$$Z$$$$$$$$$$$$$$$$$$$$$$7777777I?????????????+++++++?+++++++??????????????III    //
//    OOOOOZZOOOOOOOOOOOOOOOOOOOOOOZZZZZZZZZZZZZ$$$$$$$$$$$$$$$$$$ZZ$$$$$7777I7I??????????????+++++++++++++???????????????III7    //
//    ZOOOOZZZZOOOOOOOOOOOOOOOOOOZZZZZZZZZZZZZZZ$$$$$$$$$$$$$$$$$$Z$Z$$$$7777??I??????????????+++++++++++++++?????????????IIII    //
//    OOOOZZZZZZOOOOOOOOOOOOOOOOOOOZZZZZZZZZZZZZ$$$$$$$$$$$$$$$$$$ZZ$$$$$77I????I??????????????+++++++++++????????????????III7    //
//    OZOOZZZZZZZ$OOOOOOOOOOOOOZOZZZZZZZZZZZZZZZ$Z$$$$$$$$$$$$$$$$Z$$$$$77IIIII????????????????+++++++++?????????????????IIII7    //
//    ZZZZOZZZZZZ$ZOOOOOOOOOOZZZZZZZZZZZZZZZZZZZZZ$$$$$$$$$$$$$$$$$$$$$$IIIIIIII?????????????????+++?????????????????????IIII7    //
//    OZZZOZZZZZZ$$$ZOOOOOOOOOOOZZZZZZZZZZZZZZZZZ$$$ZZ$$$$$$$$$$$$$$$$7IIIIIIIII????????????????????????????????????????IIIII7    //
//    ZZZZZZZZZZZZ$Z$OZOZZZZZZZZZZZZZZZZZZZZZZZ$$$$$$$$$$$$$$$$$$$$$$IIIIIIIIIII??????????????????????????????????I?IIIIIII777    //
//    ZOZZZZZZZZZZ$$$$$ZZZZZZZZZZZZZZZZZZZZZZZZZ$$$$$$$$$$$$$$$$$77IIIIIIIIIIIII?????????????????????????????I??IIIIIIIIIIII77    //
//    ZZZZZZZZZZZZZZ$$$$OZZZZZZZZZZZZZZZZZZZZZZ$$Z$$$$$$$$$$$77777IIIIIIIIIIIIIIII?????????????????????????IIIIIIIIIIIIIIII777    //
//    ZZZZZZZZZZZZZZZZ$$$$ZZZZZZZZZZZZZZZZZZZZZZZZZ$$$$$$$$77777IIIIIIIIIIIIIII?IIII???????IIIII???????IIIIIIIIIIIIIIIIII77777    //
//    OZZZZZZZZZZZZZZZ$$$$$$ZZZZZZZZZZZZZZZZZZZZZZZZZ$$$$$$$7$7IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII777777    //
//    ZZZZZZZZZZZZZZ$$$$$$$$$ZZZZZZZZZZZZZZZZZZZZZZZ$$$$$$NNNDNDNIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII77777777    //
//    ZZZZZZZZZZZZZZ$$$$$$$$$$7ZZZZZZZZZZZZZZZZZZZZZ$$ONMMMNNNNNNDIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII77777777777$    //
//    ZZZZZZZZZZZZZZZZZZ$$$$$$$$OOOOOZZZZZZZZZZZZZZ$NNNNNNNNNNNNNDDDIIIIIII7777777IIIIIIIIIIIIIIIIIIIIIIIII7777777777777777$$$    //
//    ZZZZZZZZZZZZZZZZZZZZZZZZZ$$$OOOOOOOOOZZONNNNNNNNNNNNNNNNNNNNNDD$IIIIIII7777777II7777777777IIIIII7I777777777777777777$$$$    //
//    ZZZZZZZZZZZZZZZZZZZZZZZZ$$7MMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNNND7IIIII777777777777777777777777777777777777777777777$$$$    //
//    ZZZZZZZZZZZZZZZZZZZZZZZZNMMMMMMMMNZ77$7$7$777777777I$777NNNNNNNNNDD$777777777777777777777777777777777777777777$77$$$$$$$    //
//    ZZZZZZZZZZZZZZZZZZZZZZZMMMMMMM777$$$77777777777777777777777DNNNNNDDDN777777777777777777777777777777777777777777$$$$$$$$$    //
//    ZZZZZZZZZZZZZZZZZZZ$MMMMMMMMMMMMM777777777777777I7III?$II7$MNNNNNDDDDD777777777777777777777777777777777777$$$$$$$$$$$$$$    //
//    ZZZZZZZZZZZZZZZZZZMMMMMMMMMMMMMMMMMMMMMMM87??IIIIZ$NMNNNNNNNNNNNNDDDNNN877777777777777777777777777777777$$$$$$$$$$$$$$$$    //
//    ZZZZZZZZZZZZZZZZMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM$$NNNNNNNNNNNNNDDNNNNZ7777777777777$$$$$$7777777$$$$$$$$$$$$$$$$$$$$$    //
//    ZZZZZZZZZZZZ$MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7$NMNNNNNNNNNNNNNNNNNZ$$$777777777$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$    //
//    ZZZZZZZZZZNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNZOMMMMMNNNNNNNNNNNNMM$$$777777$7$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$    //
//    ZZZZZZZZMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN$$MMMMNNNNNNNNNNNNNNNI$77777$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$    //
//    ZZZZZ$NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM$Z7MMMNNNNNNNNNNNNNNNN$77$7$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$    //
//    ZZZOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM7$$NMMNNNNNNNNNNNNNNNDZ$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$Z$    //
//    $MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM$$$NMNNNNNNNNNNNNNNNNM$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$Z$$    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN$$$$NNNNNNNNNNNNNNNNNND$$$$$$$$$$$$$$$$$$$$$$$$$$$ZZZ$$Z$ZZ$    //
//    NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM$$$$$NNNNNNNNNNNNMNNNMM$$$$$$$$$$$$$$$$$$$ZZ$$$Z$ZZZZZ$ZZ$$    //
//    NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZ$$$$MNMMNNNNNMMMMMMMMN$ZZZ$ZZ$Z$$$$$$$$$Z$$$$Z$ZZZZZZZZZZ    //
//    NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM8$$$$MMMMMMMMMMMMMMMMMM8ZZZZZZZZZ$ZZZZZZ$$ZZZZZZZZZZZZZZZ    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM$$$$8NNMMMMMMMMMMMMMMMM$ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM$ZZZZ$MMMMMMMMMMMMMMMMNN$ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ    //
//    NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDZZZZZZZMNMMMMMMMMMMMMMMMOZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ    //
//    NNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZZZZZZZ$NNNMMMMMMMMMMMMMMM$ZZZZZZZZZZZZZZZZZZZZZZZZZZZ    //
//    NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOOZZZZZZNMNNMMMMMMMMMMMMMMMMNDZOOZZZZZZZZZZZZZZZZZZZZZ    //
//    NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOOZZZZZZZMMMMMMMMMMMMMMMMMMMMMMNM8OOZZZZZZZZZZZZZZZZZZ    //
//    NNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZOOZOZZZZMMMMMMMMMMMMMMMMMMMMMMMMMNZZZZZZZZOZOOOOZZZZ    //
//    NNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOOOOZZOZZMMMMMMMMMMMMMMMMMMMMMMMMMNDOZZZZZOZOOOOOZZZ    //
//    NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOOOOOOOOOOMMMMMMMMMMMMMMMMMMMMMMMMMMMNDZZZOOOOOOOOOZ    //
//    NNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZOOOOOOOOOOMMMMMMMMMMMMMMMMMMMMMMMMZMMNMNMZOOOOOOOZZ    //
//    NNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOOOOOOOOOOZMMMMMMMMMMMMMMMMMMMMMMMMNN8MMNNNMDOOOOOO    //
//    NNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOOOOOOOOOOOO8NMMMMMMMMMMMMMMMMMMMMMMMMMONNNNNNDOOOZ    //
//    NNMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM$OOOOOOOOOOOOZMMMMMMMMMMMMMMMMMMMMMMMMMMMZZMNNNNNNO    //
//    NNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM$ZOOOOOOOOOOOOZMMMMMMMMMMMMMMMMMMMMMMMMMMNMOOMNNNNN    //
//    NNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZZOOOOOOOOOOOOOONMNMNNNNMMMMMMMMMMMMMMMMMNN8OO8MNN    //
//    NNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMZZZOOOOOOOOOOOOOOOMMNNNMMMMMMMMMMMMMMMMMMNNNNOOOOM    //
//    NNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOZZZOOOOOOOOOOOOOOOMMMMNNNNMMMMMMMMMMMMMMNNNN8OOO    //
//    NNNNNNNMMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMDZZZOOOOOOOOOOOOOOOONMMNNNNMMMMMMMMMMMMMMNNNNNMOO    //
//    NNNNNNNNNNNNNMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNNNNMZZZZ$OOOOOOOOOOOOOOOMMNMMMMMMMMMMMMMMMMMNNNNNNNN    //
//    NNNNNNNNNNNNNMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNZZZZZZOOOOOOOOOOOOOOOMNMMMMMMMMMMMMNNMMNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMNOOOOZOOOOOOOOOOOOOOO8ONMMMNMMMMMNMNNNNNNNNNNNNN    //
//    NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNMMNNNNNNNNMNNNNNNNNNNNNNNNNNNNNNNNNNMMOOOOOOOOOOOOOOOOOO888ONMMMMMMMMMMNMMMMMMMNNDD8    //
//                                                                                                                                //
//                                                                                                                                //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract SHIGG is ERC1155Creator {
    constructor() ERC1155Creator() {}
}
