
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: D†MATTEO
/// @author: manifold.xyz

import "./ERC1155Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                //
//                                                                                                                                //
//    D†MATTEO=GIFTOFGODMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMWKxddONWMMMMMMMMMMFEARMMMMMMMMMMMMMMMMMMMMMMOverthinkerMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMANXIETYMMMMMMMMMMM    //
//    MMMMMMMMMMMMMXkoclkXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMSOCIALANXIETYMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMWKc..:xKWMMMMMMMMMMMADHDMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNklkWMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMNl..;;cdKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO0WWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk,  .xWMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMXc,kKxc:cdKWMMMMMMMMMMMMMMMMMMMMMMMMMMMK:oNWMWWNNWMMMMMMMMMMMMMMMMMMMMMMMMMMW0:..;; .kWMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMM0;;KMWXkl:cxKWMMMMMMMMMMMMMMMMMMMMMMWNx',odxkOOKWMMMMMMMMMMMMMMMMMMMMMMMMMNx. 'kWK: ,KMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMWd.lNMMMWXxc;cdKWMMMMMMMMMMMMMMMMMWKddl.;dkXNWMMMMMMMMMMMMMWWWMMMMMMMMMMMXl. :KMMMO. cXMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMO'.OMMMMMMWKxc;:dKWMMMMMMMMMMMMMMMNXNXllKNMMMMMMMMMMMMMMMNd,:xXMMMMMMMMK: .oXMMMMWo .dWMMMMMMMMMMMMM    //
//    MMMMMMNOTALONEMMMMMMMK,.xWMMMMMMMMWKd:,:dKWMMMMMMMMMMMMMMMWxlxKMMMMMMMMMMMMMMX: ..,xNMMMMW0; 'kWMMMMMMK; '0MMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMX;.oWMMMMMMMMMMMW0d:,:dKWMMMMMMMMMMMMMKocOMMMMMMMMMMMMMMMO..xOc':0MMWO' ;0WMMMMMMMWk. oWMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMK, oWMMMMMMMMMMMMMMW0o;,:xKWMMMMMMMMMMWkckWMMMMMMMMMMMMMNl.:XMWk',ONx..cXMMMMMMMMMMNc '0MMMMMMMMMMMM    //
//    MMMM Fear MMMMMMMMMM0'.dWMMMMMMMMMMMMMMMMMNOl'.:xXWMMMMMMMMNXNWMMMMMMMMMMMMM0,.xWMMWk..;..dNMMMMMMMMMMMMk..dWMMMMMMMMMMM    //
//    MMMMMM Of MMMMMMMMMWx..kMMMMMMMMMMMMMMMMMMMMWXd'.'dXMMMMMMMMMMMMMMMMMMMMMMMWd.;KMMMMNc  ;OWMMMMMMMMMMMMMK, cXMMMMMMMMMMM    //
//    MMMMFailure MMMMMMMX: ;KMMMMMMMMMMMMMMMMMMMMMMW0,  oWMMMMMMMMMMMMMMMMMMMMMMX:.xWMMMMX:.oXMMMMMMMMMMMMMMMNl ,KMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMWx..xWMMMMMMMMMMMMMMMMMMMWNOo;.'l0WMMMMMMWNXNMMMMMMMMMMMWx'lNMMMMNxlOWMMMMMMMMMMMMMMMMMx..OMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMM0,.oNMMMMMMMMMMMMMMMMWXOdc'.'ckXWMMMMMMMWx;,lNMMMMMMMMMMK:;KMMMMMX0NMMMMMMMMMMMMMMMMMMMk..OMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMX:.:XMMMMMMMMMMMMMNKko:'.':oONWMMMMMMMMMMX;  .dWMMMMMMMMNo;OMMMMMMMMMMMMMFEARMMMMMMMMMMMO.'0MMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMXc.;KMMMMMMMMMWXOdc,..,cx0NWMMMMMMMMMMMMMMk.   ,0MMMMMMMWx:OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMO.,KMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMXc.;0MMMMMMN0xl;'',cdOKWMMMMMMMMMMMMMMMMMMNl     lNMMMMMWOo0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk.:XMMMMMMMMMMM    //
//    MMMMMMMMMMMMMW0;.lXMMWXOdc;,;cokKNMMMMMMMMMMMMMMMMMMMMMMK; D†Ma .kMMMMMN0KWMMMMMMMMYoumatterMMMMMMMMMMMMMx.oWMMMMMMMMMMM    //
//    MMMMMMMMMMMMNx''xXXOoc;;:okKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMk..:oo' :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl,OMMMMMMMMMMMM    //
//    MMMMMMMMMMW0:..cllccox0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl.xNWW0,.dWMMMMMMMMMMMMFEARINEverythingIdoMMMMMK:lNMMMMMMMMMMMM    //
//    MMMMMMMMW0l..'cox0NWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXccNMMMMO,;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx;kMMMMMMMMMMMMM    //
//    MMMMMNKkxlldx0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0cxMMMMMWx;xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXclNMMMMMMMMMMMMM    //
//    MN0kxxkOXWNx,'oKWMMMMMMMMMMMMMMMMSELFCONSCIOUSMMMMMMMMMMMOoKMMMMMMWdcKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWxl0MMMMMMMMMMMMM    //
//    WKO0XWMMMMWXx;.'oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK0WMMMMMMMXokWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKoOWMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMW0l',kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXWMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMW0c'oNMMWWNXXXNWMMMMMMMMMMMMMMMDroneviewSYNDROMEMMMMMMMMMMMMMMMMMMMMMWN0xxkk0XWMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMNd,cxlcclllc:cd0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXklclx0XNWWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMNd..cxKNNNNX0kooOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo;:dKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMN0KWMMMMMMMMMNk:oKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx;;kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKlcOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl'oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMGod so loved MMMMMMMMMMMMMMMMNd:xNMMMMMW0xookXMMMMMMMMMMMMMMMMMMMMMMMMXc.oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk:dNMMMNd',lo:c0WMMMMMMMMMMMMMMMMMMMMMNl.cNMMMMMMMMMMMMMMMM The day I stop MMMMMMMM    //
//    MMMMMMthe world that He MMMMMMMMMMMMMWO:dNMWx.;KMMXo:kWMMMMMMMMMMMMMMMMMMMWx.,0MMMMMMMM caring what others think MMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk;oNX:'kMMMMNo,xWMMMMMMMMMMMMWMMMMMK,.xWMMMMMMMMM is the day MMMMMMMMMMMMMMMMMMMM    //
//    MMMgave His one and only SonMMMMMMMMMMMWx,oO,;XMMMMMXc;OMMMMMMMMNOlcclkNMWd.:XMMMMMMMM My life begins MMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl';.:XMMMMMMK:cXMMMMMMXc'cxxc.:KXc.xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;  :XMMMMMMMO:xWMMMMNl.dWMMNd.lk',0MMMMMMMMMMMMMMM Whenthatdaycomes MMMMMMMMMM    //
//    MMMMMthat whoever believes in HimMMMMMMMMWk. :NMMMMMMMWd:0MMMM0,;KMMMMNo''.cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo.:NMMMMMMMM0;oWMMMx.oWMMMMMK; .dWMMMMMMMMMMMMMMMMMM Willitbetoolate MMMMMMMM    //
//    MMMMMMMMMshall not perishMMMMMMMMMMMMMMMMMMK,:XMMMMMMMMWo:0MMWd.xMMMMMMWd..kMMMMMMMMMMMMMMMMMMM tochasemydream? MMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo;OMMMMMMMMM0:oWMNl'kMMMMMMM0'.kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMbut have eternal lifeMMMMMMMMMMMMMK:oWMMMMMMMMWd:0MNc'OMMMMMMMNc,OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWkkNMMMMMMMMM0cdNK:,0MMMMMMMMxcKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMM9Ɩ:Ɛ NHOſMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMWdcxx;,KMMMMMMMMKd0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc':,;XMMMMMMMMWKXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx,'.;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKk; ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWx.'0MMMMMMMMMMMMJOHN 3:16 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;'0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd;OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMBlessothersMMMMM    //
//                                                                                                                                //
//                                                                                                                                //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract DIMA is ERC1155Creator {
    constructor() ERC1155Creator() {}
}
