
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Veronica Bruce Woodward
/// @author: manifold.xyz

import "./ERC721Creator.sol";

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                      //
//                                                                                                                      //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO;..lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc.   '0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk'  .  ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl. .o:  lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKNMMMMMMMMMMMMMW0;  ,O0, .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd;..;OMMMMMMMMMMMWk.  cXMx. ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMNKXWMMMMMMMMMMMMMMMMMMMMMMMNk'  .  ;XMMMMMMMMMNo. .dNMNc  lWMMMMMMMMMMMMMMMNKXWMMMMMMMMMMMMMMMMMMMMN    //
//    MMMMMMMMMNo.,OMMMMMMMMMMMMMMMMMMMMMMNl. .dk' .OMMMMMMMKk:  'OWMM0' .OMMMMMMMMMMMMMMWk,..xWMMMMMMMMMMMMMMMMMMKc    //
//    MMMMMMMMMWl  lNMMMMMMMMMMMMMMMMMMMMXc  ,OWX: .xMMMMMWO,   :KMMMWo  :NMMMMMMMMMMMMMXl.   ;XMMMMMMMMMMMMMMMMW0;     //
//    MMMMMMMMMMO. .OMMMMMMMMMMMMMMMMMMMNl  ,0MMNc  oWMMMWk.  .lXMMMMK, .xMMMMMMMMMMMMM0;     :NMMMMMMMMMMMMMMMWk'      //
//    MMMMMMMMMMNc  lWMMMMMMMMMMMMMMMMMNo. ,0MMMNc  dMMMNo. .;xNMMMMWd. ;XMMMMMMMMMMMWO'  :;  oWMMMMMMMMMMMMMMNd. .d    //
//    MMMMMMMMMMMk. '0MMMMMMMMMMMMMMMMWx. .OMMMMK; .kMMXc  'OWWMMMMMK; .xMMMMMMMMMMMWx. .oO, .kMMMMMMMMMMMMMMXl. .kW    //
//    MMMMMMMMMMMNc  oWMMMMMMMMMMMMMMM0, .dWMMMMO. '0M0;  ;KMMMMMMMMx. ,KMMMMMMMMMMNd. .xWx. ;KMMMMMMMMMMMMMK;  ,0WM    //
//    MMMMMMMMMMMMk. '0MMMMMMMMMMMMMMNl  cNMMMMWl  cXk'  cXMMMMMMMMX:  dWMMMMMMMMMNo. 'OWN:  oWMMMMMMMMMMMWO'  cKMMM    //
//    MMMMMMMMMMMMX:  dWMMMMMMMMMMMMMk. '0MMMMMO' .xx. .dNMMMWWXKXWk. '0MMMMMMMMMXl  ,OMMO. '0MMMMMMMMMMMNx. .oNMMMM    //
//    MMMMMMMMMMMMMx. ;KMMMMMMMMMMMMX;  oWMMMMNc  :c. .kNKxl:,'...:;  lWMMMMMMMMXc  ,0MMNc  lWMMMMMMMMMMNo. .xWMMMMM    //
//    MMMMMMMMMMMMMK; .xMMMMMMMMMMMWx. ,KMMMMWd. .'  'oo,.   ...     .kMMMMMMMMXc  ;KMMMk. '0MMMMMMMMMMK:  ,OWMMMMMM    //
//    MMMMMMMMMMMMMWd  :XMMMMMMMMMMX; .dWMMMWk.      ..  'cdOKKd.    ,KMMMMMMMXc  ;KMMMN:  lWMMMMMMMMW0,  ;KMMMMMMMM    //
//    MMMMMMMMMMMMMM0' .kMMMMMMMMMMx. ,KMMMMO'        'lkNMMMM0'  .  lWMMMMMMXc  ,KMMMMk. '0MMMMMMMMWk. .lXMMMMMMMMM    //
//    MMMMMMMMMMMMMMWl  lNMMMMMMMMN:  oWMMM0,      .cONMMMMMKk;  ;' .kMMMMMMNl  ,0MMMMX:  oWMMMMMMMWx. .dNMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMO. '0MMMMMMMMO. .OMMM0,     ,dKWMMMMMMXc.  :d. ,KMMMMMNl  ,0MMMMMx. ,KMMMMMMMWd. .xWMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMN:  oWMMMMMMWo  :NMWO,    .dNMMMMMMMMXc   ;Ko  cNMMMMNo. '0MMMMMX:  oWMMMMMMNd. .kWMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMx. ,KMMMMMMX: .dWWk.    'OWMMMMMMMMXc   ,0X: .dMMMMWd. 'OMMMMMMx. ,0MMMMMMNo. .kWMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMK; .xMMMMMM0' .OXl.    'OMMMMMMMMMXc  ,d0M0' .OMMMMk. .kWMMMMMX:  oWMMMMMNo. 'OWMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMWo  cNMMMMMk. ,d,     '0MMMMMMMMMX:  ;KMMMk. ,KMMM0, .oWMMMMMMk. ,0MMMMMNl. 'OWMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMO. '0MMMMMd. ..     ,0MMMMMMMMMK;  :KMMMMd  :NMMX:  lNMMMMMMX:  oWMMMMXl  ,OWMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMX: .dWMMMWo        ,0MMMMMMMMM0,  :XMMMMWc  oWMNl  :XMMMMMMMk. '0MMMMXc  ,0MMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMWd  :XMMMWl  ,:.  ;KMMMMMMMMWO'  lXMMMMMX; .xMWo. ,0MMMMMMMNc  lWMMMXc  ,0MMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMM0' .OMMMNc .l:  ;KMMMMMMMMWx. .oNMMMMMMK, .kWx. .kMMMMMMMMO' .OMMMX:  ;KMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMN:  oWMMN:  .  :KMMMMMMMMNo. .xWMMMMMMM0' '0O' .dWMMMMMMMWo  cNMMX:  ;KMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMx. ;XMMX;    ;KMMMMMMMMXc  'OWMMMMMMMMk. ;O:  lNMMMMMMMMK, .xMMK:  :KMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMM0' .kMMX;   ;KMMMMMMMMK;  ;0MMMMMMMMMMx. ;:  ;XMMMMMMMMWx. ;KMK;  :XMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMNc  lWMK,  ,0MMMMMMMWO,  cXMMMMMMMMMMMd  .. .OMMMMMMMMMNc  oW0;  cXMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMk. ,KWo.  dMMMMMMMWx. .lNMMMMMMMMMMMWl    .oWMMMMMMMMM0' .k0,  cXMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMK; .xx.  .xMMMMMMNo. .xNMMMMMMMMMMMMN:    :XMMMMMMMMMMx. ;k;  lXMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWo  ..   .xMMMMMK:  ,OWMMMMMMMMMMMMMX;   'OMMMMMMMMMMWl  ;,  cXMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMO.      .xMMMWk'  :KMMMMMMMMMMMMMMMK,  .dWMMMMMMMMMMX;  .  :XMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMN:   '' .xMMNd. .oNMMMMMMMMMMMMMMMM0'  :XMMMMMMMMMMM0'    ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMd  .dc .xMKc  'kWMMMMMMMMMMMMMMMMMk. .xMMMMMMMMMMMMO.   ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMWl  .dc  ok'  ;0WMMMMMMMMMMMMMMMMMMx. ,KMMMMMMMMMMMMk.  .kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMM0'   ;:  .. .dNMMMMMMMMMMMMMMMMMMMMK:;kWMMMMMMMMMMMMk. .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMd.   .'    ;0WMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMNxckNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMNc  .     .oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMX; .;.    ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMK,  .     .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMK,   .    .dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWx,,oOc    cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMWWMMK,   ,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMWx.  .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMX:   :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMO'  .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.  :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl  .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'  ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                                      //
//                                                                                                                      //
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract VBW is ERC721Creator {
    constructor() ERC721Creator("Veronica Bruce Woodward", "VBW") {}
}
