
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: CO2ORB GENESIS
/// @author: manifold.xyz

import "./ERC1155Creator.sol";

//////////////////////////////////////////////////////////////////////////////////
//                                                                              //
//                                                                              //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKoxNMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMWKc.'lKWMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXkKMMXl....:OWMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXlc0WXd'...,kWMMWWMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMNX0kxdooooodk0NNx,;lkXk:.,xNMWKooKWMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMWk;...........':x0o..'ckkdkNWNk:..:OWMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMM0;..............cko;'..,clol;'....,xNMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMWkccccccc:;,.....cOKx;.............,kWMMMMMMMMMMMMMMMM    //
//    MMMMMWWMMMMMMMMMMWWWWWWWWWNKkl'...oKXKo,...........,kWMMMMMMMMMMMMMMMM    //
//    MMMWKokWMMMMMMMMMMMNXNWMMMMMMNx,..;d0MWKxl;'.....,l0WMMMMMMMMMMMMMMMMM    //
//    MMW0:'dWMMMMMMMMMMM0::okKNWMMWXl..,lOMMMMWX0OxxkOXWMMMMMMMMMMMMMMMMMMM    //
//    MMNo..dWMMMMMMMMMMMKc...';codoc'..lOXMMMMMWKxooodx0XWMMMMMMMMMMMMMMMMM    //
//    MMXc..cKMMMMMMMMMMMWk,..........'lKWWMMMMNx;......';dKWMMMMMMMMMMMMMMM    //
//    MMNd...oXWMMMMMMMMMMNx,......,cdONMMMMMMNd'..........,dKWMMMMMMMMMMMMM    //
//    MMMXl...c0WMMMMMMMMMMWKxl;'..'l0NMMMMMMXo'.............;kNMMMMMMMMMMMM    //
//    MMMMXo'..,o0WMMMMMMMMMMMWNOo;..'ck0XXKk:.........'lxxo:''oXMMMMMMMMMMM    //
//    MMMMMNx;...,lONWMMMMMMMMMMMWKd,...',,'..........,kNMMWN0l,lKWMMMMMMMMM    //
//    MMMMMMWKl'...':d0NMMMMMMMMMMMWO;.....'.........,kWMMMMMMNd,:0WMMMMMMMM    //
//    MMMMMMMMWOc'....'cxKWMMMMMMMMMWx'...'oxo;'....:kWMMMMMMMMNd':0WMMMMMMM    //
//    MMMMMMMMMMNOc'.....,cx0NWMMMMMM0;....;0WN0xookXWMMMMMMMMMMXl.:KMMMMMMM    //
//    MMMMMMMMMMMMNOl,......':ox0XNNKd'.....lNMMNXWMMMMMMMMMMMMMW0;.lXMMMMMM    //
//    MMMMMMMMMMMMMMWKd:........',;;,.......;OWWkoKMMMMMMMMMMMMMMNd'.oNMMMMM    //
//    MMMMMMMMMMMMMMMMWXkl,.................'xWWk;lKMMMMMMMMMMMMMM0:.'xWMMMM    //
//    MMMMMMMMMMMMMMMMMMMWKxl,..............'xWMK:.c0WMMMMMMMMMMMMNl..:0MMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMWKkl;...........:0MMWx'.,xXWMMMMMMMMMMNd...oNMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMWXOdlc;,,;;:o0WMMMXl...:xXWMMMMMMMMKc...;OMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXXXNNWMMMMMMKc....;okKNWWWN0l.....oNMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKl......';ccc:'......:KMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd,.................,kWM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO:................'xWM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXx;...............dWM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXxc'...........,kWM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0d:'........lXMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKkoc;;;cxXMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXNWMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                              //
//                                                                              //
//////////////////////////////////////////////////////////////////////////////////


contract CO2GENESIS is ERC1155Creator {
    constructor() ERC1155Creator() {}
}
