
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: BCTESTMANIFOLD
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                            //
//                                                                                            //
//    BCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLD    //
//    BCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLD    //
//    BCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLD    //
//    BCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLD    //
//    BCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLD    //
//    BCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLD    //
//    BCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLD    //
//    BCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLD    //
//    BCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLD    //
//    BCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLD    //
//    BCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLD    //
//    BCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLD    //
//    BCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLD    //
//    BCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLD    //
//    BCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLD    //
//    BCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLD    //
//    BCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLD    //
//    BCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLD    //
//    BCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLD    //
//    BCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLD    //
//    BCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLD    //
//    BCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLD    //
//    BCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLD    //
//    BCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLD    //
//    BCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLD    //
//    BCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLD    //
//    BCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLDBCTESTMANIFOLD    //
//                                                                                            //
//                                                                                            //
////////////////////////////////////////////////////////////////////////////////////////////////


contract BCTM is ERC721Creator {
    constructor() ERC721Creator("BCTESTMANIFOLD", "BCTM") {}
}
