
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: ZU X ORI
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                //
//                                                                                                                                //
//    Sov x Undeadlu WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW Undeadlu x Sov    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWWWWWWWWWWWWWWWWWWNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKXWWWWWWWWWWWWWWWWNXXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWX0XWWWWWWWWWWWWWNXXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXOXWWWWWWWWWWMNKXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNXXXX0xKWWWWWWWWWNXXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNNNXOokNWWWWWWX0KWWWWWWWWWWWWWXNWNNWWWWNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNkxXWWWWWWWWWWWWWWWWNOxONWWWWKkKWWWWWWWWWWWWWNXWNXWWNXKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0d0WWWWWWWWWWWWWWWWWWXkdkXWW0oOWWWWWWWWWWWWWWXNNO0XKXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXKKXWWWWWWWWWWWWWWWWXXWXxod0OdkXWWWWWWWWWWWWNK00kxKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWNWWWWWWWWWWNd;:kWWWWWWWWWWWWWNNX0XWWWNOdddoxKNWWWWWWWWWNkx0XWXOXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWNNNXXXXXXNWNkxKWWNXNWWWWWWWWWNK00WWWWWWWKOd;:ONWWWWWWNXkxXWWWWKkKWWWWWWWWWWWWNNWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWNNNXKKK00kKWWWWXXWWWWWWWWWWNOONWWWWWWWWKkdcdXWWWWX0xONWWWWWW0kXWWWWWWWWWNXNWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWNXXNWWWWWWNXOdkNWWN0OKNXXXXXKK0kddOXWWWWXOk0WXxlox0XKkkNWWWWWWWWkOWWWWWWN000KXNNNNWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWNNWkcdXWWWWWWWWWN0OOxooO00NWNWWNKxolcccl0NN0dxKWWW0,.;OOxXWWWWWWWWWOxNMNKKKK0KXNNNNNWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWNXXOkXMWNNWWWWWWWXo;co0WK00XWWWKlcOKx;:xdOOxxKWWWWKc:OxkWWWWWWWNOo;oK0kOKNNNNNNWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWNKO0WWXXNWWWWWWWWKoloOWWW0ONWXOxkKKK0xl:ol;l0WWWWWXc,ckMWWWNKKXKOlck0NWWWWWWNNNWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWW0cxWNXWWWWWWWWWWWNo;oXWWWkd00O0XWWW0dlldc';kWWWWWWX:.xKxO00KNWWXloNWWWWWWWWWNNWWWWWWWWWWWWNWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWKOXXNWWWWWWWWWWWWk;lONKOdxXWWWWNXKdlkXXkdl:xNWWWWW0,,;:OXWWWWNxxNWWNNXXXKXXXNWWWWWWWWWWWNKNWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWW0d0WWWWWWWWWWWWWkkWNxc;;xNX0OOOOO0KKK0kdd:,lONWWWWl ;KWWWWN0odO00000KKXXWWWWWWWWWWWWWWWXKWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWNOcoXWWWWWWWWWWWKd0Kc;ollkkxkk0KKKK00Okocclc;cdKXdkx.cNWWKkOc;x0KNWWWWWWWWWNNWWWWWWWWWWNKNWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWNXOc,oOOkONNXWWWWWWWkd0l;lxxlxKNWWWWWWWM0o0NKKK0xxc;,'dk,.,kNd';dKWWWWWWWWWWWKkKWWWWWWWWWNNNNWWWWWWWWWWW    //
//    WWWWWWWWWNNK00000OkxxkOOklclxXWWWWWWxldc:cc:xNWWWWWWNXXXxlONNXK0KXKl'cdko';k0o':KWWWWWWWWWWXOxd0K000KKOOO0XNWNNWWWWWWWWW    //
//    WWNXX000KKKKKXNWWWWWWWWWWN0c,cdx0NWWx'lXWO:xWWWWWX0O0K0kldXWWWWNK0Od,.'xx.lOc;l0WWWWWWWWWXxcoOOc'cOXXXK00OkdoOXWWWWWWWWW    //
//    WWWWNNNWWWWWWWWWWWWWWWWWWWNdckK0xdxXk',l:,cKWWNOocoKWWWWN00NNNWWWXKxlo'',.:dxddOO0NWWWWKd;,lk0Ooco0NNWWWWWWc ;OKXXXNNNWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWKdkNWWXkoc';dl;'lK0OOxllOWWWWWWWX000NXkc;cxc.  .x0O0KXKK0xl::oOXNNNX000OO0KKNWWWO:oNWNNNNNNNW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWNXNXOKWWWWKd'l0o::';ONWWWWWWWWWWWW0oxxcllcxXKo...:XNXkkkl,..,xXWWWNWWWWWWWXK00KKXWWNNWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWNXKO0K0k0XO:','.;:oOoxNWWWWWWWWWWWWWWNXo'cxKWWWk' .oXx:;'..'lONWWWX0XWWWWWWWWWXOKNK0XWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWNNXK00kkxllok0Oddxollll;'lodKWWWWWWWWWWWNWWWWWKxkOkXWWK; .::.. .;xXWWWWXOO0K00000KKKKXN00WXKNWWWWWWWWWWW    //
//    WWWWWWWWWWWWNNXKKXXKXNNKkodkkOKWNKOOkkKK:.ckXWWWWWWWWWWWNXOkOKx;:ddxXMK; cc  .:kKKK00Od;ck00KXXNNXXK00K0OKWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWN0kd:,ck0XNXOxxo';ONWWWWWNXWWWWWN0xxxdkXNKxxXO'    ,lxO0K0o,,cld0NWWWWWWWWWWWWN0OKNWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWXKKKK0d' .,::;;:;'..;kWWKXWWKOXWWWWK0KXX000KOOk;   .:k0XXkoc:dXWX00XNWWWWWWWWWWWWNKNWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWX0000KKXNNNKkkKXKOxl'. . .lOOKWWWKxx0NNKNMWWNOoxOOc   ,xK0d;.'cONWWWWNNX0NWWWWWWWWWWWWXNWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWNNN0kO0NWWWWWNX0KNKKWWWWN0d;.   ..:kXWWO' cOkOXNWWN0d:'   ;K0l'.;xXWWWWWWWNNWK0WWWWWWWWWWWWNNWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWNNKkxKWWWWWWWWWWX00Oxk000KKKKKx:''.  'l0x..;;..'lKNWWd     :l. .;x0000KKXNWWWWNNWWWWWWWWWWWWWNWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWX0KWWWWWWWWWWWWWWNKklc:ldxk0XN0l;:l;. .,;dKx',::;;oo.  ,'   ...;kOO0KKK0OOKXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWN00NWWWWWWWWWWWWWWWWKKWWXOxlc::;;;.;xxoc'  .',...cd:'   ;:.   .;:kWMWWWWWWWXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWNXKXWWWWWWWWWWWWWWWWWX0NWWWWWWWNKOxl,..codl;.   .. .;.   .'.  'ckXXXXXXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWNNNWWWWWWWWWWWWWWWWWWNXNWWWWWWWWWWWWWN0dc.  :dc.     ..     .:kXWXO0NNX00XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXx;..;:,           lNWNk;cOXNNNXKXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNk:. ''.         c0kc:dKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNXx,          ;;.';xXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNKo.        . .oXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0:.       'OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKc      dWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMO.     oWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWM0'     :NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMx.     :NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWX0:      oWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWd'.     '0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWk.       lWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWk.       ,0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWk.       .dWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWx.        :XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNd.        .kWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNd.         lNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWx.         '0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWO'          lWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNc          .OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWO.          ,KWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWx.          .OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWd.           ,OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXkkkkkkkkkkkkk0NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//    WWWWWWWWWWWWWWWWWWWWWWWWWWW https://arweave.net/4m5U6TYjcDj6kt19-hCFneCOHRpHZlfthh_lpeWxzKU WWWWWWWWWWWWWWWWWWWWWWWWWWWW    //
//                                                                                                                                //
//                                                                                                                                //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract ZUXORI is ERC721Creator {
    constructor() ERC721Creator("ZU X ORI", "ZUXORI") {}
}
