
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Stargaze Arts
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    ;;',,,;:cc::;,,,,''......',;:::::::::::::ccccccccccccccccccclllllllloooooooooodddddddddddddxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkOOOOOOOOO0000000000KKKKKKKKKKKKKKK0000000000000OOOOOkkkkkkkxxxxxxxxxxxxxxxxo;''',,,,,,,'',,,,,,,;;;;;;;;;;;;::;;;;;;;;;;;;;;;;;;;::ccclloooooooooolllcc::;;;;;;;;;;;;;;;;:::;;;;;;;    //
//    ,,,,;;::::;,',,,''......',;;:::::::::cccccccccccccccccccclllllllllloooooooooooddddddddddddxxxxxxxxxxxxkkkkkkkkkkkkkkkkOOOOOOOOOO000000000000KKKKKKKKKKKKKKK0KK0Oxdoollllloodddxxxkkkkxxxxxxxxxxxxxxxxdc,.''',,,,,,,,;;;;;;::::::::;;;;;;;;;;;;;;;;;;;::cclloooooodddooooollccc::;;;;;;:::::::::::::::;;;;;;;    //
//    ,,;;;;:;;;,',,,''.......',;::::cccccccccccccccccccccccllllllllllloooooooooooddddddddddddxxxxxxxxxxxxkkkkkkkkkkkkkkkkOOOOOOOOO0000000000000KKKKKKKKKKKKKKKK0kl;'..           ......'',,;;;:cldxxxxxxxkkxo:'..'''''',,,,,,,;;;;;;;;;;;;;;;;;;;;;;::::cclloooooooooooooollllccc:::::::::::::::::::::::::;;;;;;;    //
//    ;;;;;;;;;,',,,''.......',;:::ccccccccccccccccccccccclllllllllllooooooooooodddddddddddddxxxxxxxxxxxkkkkkkkkkkkkkkkOOOOOOOOO0000000000000KKKKKKKKKKKKKKKKKOo,.                      ...',;:clodxxxxxxkkkkxdl:;''.''''''''''',,,,,,;;;;;;::::::cccclllloooooooooooolllllllllccccccccc:::::::::::::::::;;;;;;;;;    //
//    :;;;;;;;,,,,,,''......',;:::ccccccccccccccccccccccllllllllllloooooooooooodddddddddddddxxxxxxxxxxkkkkkkkkkkkkkkOOOOOOOOOO00000000000000KKKKKKKKKKKKKKKkoc.                ...,;:clodxkkkkkkkkkkkkkkkkkkkxxxdolc;,''',,'',,,,,,,;;;;;;:::ccccccllllooooooooooooooollllllllllllllcccccc:::::::::::::;;;;;;;;;;;    //
//    ;;;;;;;,,,,,'''......',;:::cccccccccccccccccccclllllllllllloooooooooooodddddddddddddxxxxxxxxxxkkkkkkkkkkkkkkOOOOOOOOOO00000000000000KKKKKKKKKKKKKK0x:.             .';cloxkOOOOOOOOOOOkkkkkkkkkkkkkkkkkkxxxxxddoc,''''''',,,,,;;;;::::ccccccllllllloooooooooolllloooooloollllllcccccccccccc:::::;;;;;;;;;;;;    //
//    ;;;;;;,,,,,'''.......',;::cccccccccccccccccccllllllllllllooooooooooooddddddddddddxxxxxxxxxxxkkkkkkkkkkkkkkOOOOOOOOOO0000000000000KKKKKKKKKKKKKKK0d;.            .;okO0000OOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxdo:,'''''''',,,,;;;:::ccccccclllllllllllllooooooooooooooollllllllllllllcccc:::;;;;;;;;;;;;;;    //
//    ;;;;;;,,,,,'''......',;::ccccccccccccccccccllllllllllllooooooooooooddddddddddddxxxxxxxxxxxkkkkkkkkkkkkkkOOOOOOOOOO00000000000000KKKKKKKKKKKKKK0d;.           .,lk000000OOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxddc,''''''''''',,,;;;::ccccccllllllllllllloooooooooollllllloollolllllllcc::;;;;;;;;;;;:::::    //
//    ;;,;;,,;,,,'''......';::ccccccccccccccclllllllllllllooooooooooooodddddddddddxxxxxxxxxxxxkkkkkkkkkkkkkkOOOOOOOOOO0000000000000KKKKKKKKKKKKKKK0x;.           .:x00000OOOOOOkkkkkkkkxxxxxxxxxxxxxxkkkkkkkkkkkkxxxxxxxddl;'''''....'''',,,;;:ccccllllllllllllllloolloooooooooooooooooooooolcc:;;;;;;;;;:::c:::::    //
//    ;,,;,,;,,,'''......',;:cccccccccccccllllllllllllllooooooooooooodddddddddddxxxxxxxxxxxxxkkkkkkkkkkkkkOOOOOOOOOO00000000000000KKKKKKKKKKKKKK0x;.           .ck0000OOOOOkkkkkkxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkxxxxxxddoc,''''''..''''',,,;;::cccllllllloooooooooooooooooooooddddddddoolcc:;;;;;;:::cccccccccc    //
//    ;,,,,;;,,,'''......';::ccccccccccllllllllllllllloooooooooooodddddddddddxxxxxxxxxxxxxxkkkkkkkkkkkkkOOOOOOOOOOO00000000000000KKKKKKKK0000K0k:.          .'lO0000OOOkkkkkxxxxxxddddddddddddddddxxxxxxxxxxkkkkkkkkkkxxxxxddo:,'''''..'''''',,;;;:::cccllllllooooooooooodddddddxxxxddoollc:::;;;::cccccccccllcccc    //
//    ,,,,,;,,,''''.....',;:cccccccclllllllllllllllloooooooooooodddddddddddxxxxxxxxxxxxxxkkkkkkkkkkkkkOOOOOOOOOOO00000000000000000KKKK00000K0k:.          ,okO000OOOOkkkxxxxxddddddddddddddddddddddddxxxxxxxxkkkkkkkkkkxxxxxdddoc,''''..'''''',,,;;;;:::cccclllllooooooodddddxxxddoollcc:::::::ccclllllclllllccc::    //
//    ,',,,;,,,''''.....',::cccccclllllllllllllllloooooooooooodddddddddddxxxxxxxxxxxxxxkkkkkkkkkkkkkOOOOOOOOOO00000000000000000000KKK00K0KKk:.         .;dO000OOOOkkkxxxxdddddddoooooooooooooddddddddddxxxxxkkkkkkkkkkkkxxxxdddddl;''''.....''',,,,,;;;;::::ccclllllloooooooooollccc:::::ccccllllllllllllllccc::;;    //
//    '',,,,,,',,''.....';:cccccllllllllllllllllooooooooooooddddddddddddxxxxxxxxxxxxkkkkkkkkkkkkkkOOOOOOOOOOO0000000000000000KKKKKKKKKKKKkc.         .:x00OOOOOkkkkxxxxddddddoooolcllllllloooooooddddddxxxxxkkkkkkkkkkkkxxxxxdddddl;''''......'''',,,,,,;;;;::::ccccccllllcccc::::::cccllllllllllllllllllllc::;;;;    //
//    '',,,,,,,,,''.....,;:ccclllllllllllllllooooooooooooodddddddddddxxxxxxxxxxxxxkkkkkkkkkkkkkkOOOOOOOOOOO00000000000000000KKK000KKKKKOc.         .:x00OOOkkkkkxxxxxddddoolccll;,,;:::;,::::;cllclodoodxxkkkkkkkkkkkkkkkxxxxxdddddl,'''''......''''',,,,,,,;;;;;;::::::::::::::ccclllooooooollllolllllllc::;;;;;;    //
//    '',,,,,,,,,''....',:ccclllllllllllllloooooooooooooodddddddddddxxxxxxxxxxxxxkkkkkkkkkkkkOOOOOOOOOOOO0000000000000000KK00KK00KKKKOl'.        .:x00OOOkkkkkxxxxxdoolooc;'.,;'...','..,'...'',..;cc:cxxkkkkkkkOOOOkkkkkxxxxxxddddd:'''''''''''''''''''',,,,,,,,,;;;;;;;;;::ccclllloooooooollllllllllcc::;;;;;;;;    //
//    '',,,,,,,,,'.....';:cclllllllllllllooooooooooooooddddddddddddxxxxxxxxxxxxkkkkkkkkkkkkOOOOOOOOOOOO00000000000000000000KKKKKKKKOo;......   .:x00OOOkkkkxxxxxxdoc;;,';'. ... ......... ....  .,,'',oxkkkkkkkOOOOOOkkkkkxxxxxxddddo;'''''''''''''''''''',,,,,,,,,,;;;;;:::ccclllllooooolllllllllllcc::::;;::;;,,    //
//    ',,,,,,,,;,'....',;ccclllllllllllloooooooooooooodddddddddddddxxxxxxxxxxxkkkkkkkkkkkkOOOOOOOOOOOO0000000000000000000000KKK0K0d:,,''......ck00OOOkkkxxxxxxxdoc:,......                     .....,cxkkkkkkOOOOOOOOkkkkkkxxxxxxxdddl;'''''''''''''''''',,,,,,,;;;;;:::::ccclllllllllllllllllllllcc::::::::;;,,,,    //
//    ',,,,,,,,,'.....';:cclllllllllllooooooooooooooodddddddddddddxxxxxxxxxxxkkkkkkkkkkkkOOOOOOOOOOO0000000000000KKK00000000K0K0xc:cc:;,,'.'ck00OOOkkkkxxxxxxdc:;'...          ...,,,,'....      ..;cdkkkkkOOOOOOOOOOOOkkkkkxxxxxxxxxdolc:,''''''''''''''',,,,,,;;;;:::::cccclllllccllllllllllllcc::cccc::;,,,,,,;    //
//    ',,,,,;,,,'....',;:cllllllllllloooooooooooooooodddddddddddddxxxxxxxxxxkkkkkkkkkkkOOOOOOOOOOO000000000000000KKKKKK000KKKKOolodolcc:,,ck000OOOkkkkxxxxxolc;..         ....''';d0000OOkxd:.  ..;:codxkkOOOOOOOOOOOOOOkkkkkxxxxxxxxxxxxdo;''''''''''''''',,,,,,;;;;;:::ccccccccccccccclllllccccccccc::;,,,,,;;,,    //
//    ',,,,;;,,''....';:ccllllllllloooooooooooooooooodddddddddddddxxxxxxxxxxkkkkkkkkkkOOOOOOOOOOO000000000000000KKKKKKKKKKKKKKkxOkxxdoc;cx0000OOOkkkxxxxxdl;,....        ...';:cc::xKKK00OOk;  ..,cdxkxkkOOOOOOOOOOOOOOOkkkkkkxxxxxxxxxxxxxl,''''''''''''''''',,,,;;;;;::::::::ccccccllllllcccccccc::;;;;,,,,,,,,,    //
//    ',,,,;;,,'....',;:ccllllllloooooooooooooooooooodddddddddddddxxxxxxxxxxxkkkkkkkkOOOOOOOOOO00000000000000000KKKKKKKKKKKKKKKK00Okdccx00000OOOkkkkxxxxdl:,'..    .    ...,okkOOkdx0KKK00k;   .,;ldxkkkOOOOOOO00OOOOOOOkkkkkkkxxxxxxxxxxxxd:''''''''''''''''''',,,,;;;;:::::::cccclllllccccccccc::;;;;;;;,,,,,,,,    //
//    ,,,,;;;,''....';:ccclllllllooooooooooooooooooooodddddddddddddxxxxxxxxxxkkkkkkkkOOOOOOOOO0000000000000000KKKKKKKKKKKKKKKKKKKK0xld000000OOOkkkkkxxxl:;'....  ....  ...,;lxkO0Odd0KK00x,   ...,coxkkkOOOOOO000OOOOOOOOkkkkkkkxxxxxxxxxxxxl,'''''''''''''''''',,,,,;;;;;:::::cccccccccccccc::::;;;;;;;;;,,,,,,,,    //
//    ,,,,;;,''....',;:cclllllllllooooooooooooooooooodddddddddddddddxxxxxxxxkkkkkkkkOOOOOOOOOO00000000000000KKKKKKKKKKKKKKKXXXXKKKOxOK00000OOOOkkkkxxxo;...   .,'..... ....'';:ccc:d0K0kc.   .,;:ccodxkOOOOO00000OOOOOOOOkkkkkkkkkxxxxxxxxxxo,.'',,'''''''''''''',,,;;;;;::::cccccccccccccc::::::::::;;;,,,,,,,,,,    //
//    ,,,;:;,'....',;::ccllllllllloooooooooooooooooodddddddddddddddddxxxxxxxkkkkkkkkOOOOOOOOO00000000000000KKKKKKKKKKKKKKXXXXXXXKKKKK00000OOOOkkkkkkxolc'.   'xKd'...... ....'','':k0kl.   ..;codxxkkkOOOOO00000OOOOOOOOOkkkkkkkkkxxxxxxxxxxd;.;lc;,,''''''''''''',,,;;;;::::::cc::cccccc::::::::::;;;,,,,,,,,,,;;    //
//    ,,;:;,''...',;;:cccllllllllllooooooooooooooooodddddddddddddddddxxxxxxxkkkkkkkOOOOOOOO000000000000000KKKKKKKKKKKKKXXXXXXXXXKKKK00000OOOOkkkkkkxol:'...;dkKXXO:..............cxxc'.   ..',;ldxkkkOOOO00000000OOOOOOOOOkkkkkkkkxxxxxxxxxkxlcoddoc;,''''''''''''',,,,;;;;;::::::::::::::::::;;;,,,,,,,,,,,,,,,,,    //
//    ,,;;,,'....',;::cclllllllllloooooooooooooooooodddddddddddddddddxxxxxxkkkkkkkOOOOOOOOO00000000000000KKKKKKKKKKKKKXXXXXXXXXKKKKK0000OOOOOkkkkkxddo;. .l0KKKXXXKkl,........,:lc,.    ..;:cccldkkOOOOO00000000OOOOOOOOOOOkkkkkkkxxxxxxxxkkkkxxxdddo:'''''''''''''''',,,,;;;;;;;;::::::::::;;,,,,,,,,,,,,,,,,,,,,    //
//    ,;;,,''....',;:ccclllllllllloooooooooooooooodddddddddddddddddxxxxxxxkkkkkkkOOOOOOOOO0000000000000KKKKKKKKKKKKKKKKXXXXXXKKKKK000000OOOOOkkkkkxxxdc..o000KKKKKKXX0kdollllc:,.      .,'':dxkkkkOOOO000000000OOOOOOOOOOOOOkkkkkkxxxxxxxkkkkkxxxddddc'''''''''''''''''',,,,,,,;;;;;::::;;;,,,,,,,,,;;;;,,,,,,,,,,    //
//    ;;;;,,'.....';cclllllllllllllooooooooooooooddddddddddddddddxxxxxxxkkkkkkkOOOOOOOOOO000000000000KKKKKKKKKKKKKKKKKKXXXXXKKKKK000000OOOOOkkkkkkkkkx;.oOO00000000K000Oxoc,.      ....,lolcoxkkOOOOOO00000000OOOOOOOOOOOOOOkkkkkkkxxxxxxkkkkkxxddkkOxoc,'...'''''''''''''',,,,,,,,,,,,,,,;;;;::::c::::;;;;;;;;;;;    //
//    ;;;;;;'......':llllllllllllllooooooooooooodddddddddddddddxxxxxxkkkkkkkkOOOOOOOOOOOO000000000000KKKKKKKKKKKKKKKKXXXXXKKKKKK000000OOOOOkkkkkkkkkx:'okkkkkxddolc:;,'..       ...:l;,:odkkkkOOOOOOO00000000OOOOOOOOOOOOOOOkkkkkkkkxxxxxkkkkxxxO0K0O0KKOo;...''',,''''''',,,,,,,,,,,,,;;::cclooolllllcccc::::::::    //
//    ;:;;:,........';llllllllllllloooooooooooodddddddddddddxxxxxxxkkkkkkkkkkkxxxxxxOOOOOO0000000000KKKKKKKKKKKKKKKKXXXXKKKKKK0000000OOOOOkkkkkkkkkx:'lkkxo;'..           .. .;,,.,oxdclxxkOOOOOOOOO000OO0OOOOOOOOOOOOOOOOOkkkkkkkkkxxxxxkkkxdx0XOdoc;cd0Kk:'.'',;;;;;;;;;,,;;;;;;;;;;::clooooooddddoooooollllllcc    //
//    :::::'.........';cllllllllllloooooooooooddddddddddxxxxxxxxxddooolllllcccclllodkkOOOOO000000000KKKKKKKKKKKKKKKXXXKKKKKKK000000OOOOOOkkkkkkkkkkl.;lc:;'...........,,''cl;';c:,;dkkxxkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkxxxxkxxdxKXkddo:,;;l0Xk;''',;:::cccllcccllllllcccccclloodddooooddddooooooooll    //
//    c::c;............':cllllllloooooooooooddddddddoolcc:;;;,,'''''''',,;:ccllooddxxkkkOOOOOO00000000KKKKKKKKKKKKKKKKKKKKKK0000000OOOOOOkkkkkkkkkkdc;;;:lllcccc::c:;;cc::oxdlcoocokkOOOOOOOOOOOO0OOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkxxxxxxxoxX0dooc,;;;:kXKl''',;:c:cccloollloooddoollccclllloddddddooooooooooool    //
//    c:c:'.............',:llllllooooooooddolc:;,,'....       ......'',,;;:ccllooodddddxkOOOOOOOO0000000KKKKKKKKKKKKKKKKKKK000000OOOOOOOOkkkkkkkkkkkkkkxxxxxxxddddddodddoodkkxxkkkkOOOOOO00000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkxxxxxxxokXKdl:;;:;;:xX0:''',;:ccccclodoooooooddddooollllllloooddddddddooooooo    //
//    :cc,'''.............';clooooooooooc;'..                .........'',,;;::cclllloooxkkkkkxxxxkO000000KKKKKKKKKKKKKKKKK000000OOOOOOOOOOkkOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOO00000000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkxxxxxddloOXOl,;::;;o0Xx;'''',;clcccclddoddooooodddooooooooooooooooddddddddddd    //
//    cc;,''''..............':loooooooc'.                   ...',;;:cclllooodddxxxxxxxxxkkkkkkkxddddkO000000KKKKKKKKKKKKKK00000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkOOOOOOO000000000000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkxxdddc,,ckK0xllodx0Kk:''''',;:clcccloddodddooloodddooooooooddddddddddddddddd    //
//    l:,,''''...............';looodd:.          ....',;:clodxkkkkOkkkkkkxxxxxxxxxxxxxxxxxxxkkkkkkkxddxO00000KKKKKKKKKKKKK00000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000000000000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkxxdddl,,,:lx0KKKK0ko:;,''''',:cllcccloddoddddollloddddoooooooodddddddddddddd    //
//    l:;,,'''................';odddc.    ..,:clodxkOOO0OOOOOOOkkkkkkkkxxxxxdodxddddddddxxxxxxxxkkkkkxddxO000000KKKKKKKKKK00000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO00000000000000000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkxxxxddo;',;;;:clooc:::;,,,'''';:cllcccloddoddxxdolllooddddooooooooooodddddddd    //
//    c:;,,,''.....'...........':odl... .;okOOOOOOOOOOOOOOOkkkkkkxkkxkxdxdodd::ddoddddddddddxxxxxxkkkkkkddkO000000KKKKKKKKK00000OOOOOOOOOOOOOOOOO0000000000000000000000000000000000000000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkxxxxxdo:,,,,;,,,:c:::::;,,,''',;clolccclodxddddxxddollloooooooooooooooooooool    //
//    c:;;,,''.....'............'co,....lkkkOOOOOOOOOOOkkkkkkkkkxodxxxocoo::l;'::;ccccclooddddxxxxxxxkkkkxdxO0000000KKKKKKK00000OOOOOOOOOOOOOOO000000000000000000000000000000000000000000OOOOOOOOOOOOOOOOOOOOOkkkOkkOOkkkkkkkkkkkkkkkxxxxxddl,',,;;,,;cc:::::;,,,''',:cloolcclodxxddddxxxdoollllooooooooooollllllc    //
//    lc:;,,,''....'.............,,...;okkkkkkkkkkkkkkkkkkkkkkxxxoclc::,,;'..'...','..';:cloddddxxxxxxxkkkkxxk0000000KKKKKKK00000OOOOOOOOOOOOOO000000000000000000000000000000000000000OOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxddo:,,,,;,,,cc::::::;,,,''',:clooolcclodddddddddxxddoolllloooooolllllccc    //
//    oc:;;,,''...''.................:dxxxkkkkkkkkkkkkkkkkkxxxdolc:,,'........    ..  ...',coddddxxxxxxxxkkkkxkO0000000KKKKKK00000OOOOOOOOOOOOO00000000000000000000000000000000000000OOOOOOOOOOOOOOOOkkOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxddl;,,,;;,,;lc::::;;,,,,''',;:looollccloooodddddddddddddoooolllllccccc:    //
//    ol:;;;,'''''''...'...........':ddxxxxxxxxkkkkkkkkkkxxdlc;,;;;;'...  . .. ............'codddddxxxxxxxkkkkkOO0000000KKKKK00000OOOOOOOOOOOOO0000000000000000000000000000000000000OOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxddoc;,,,;;,,:lc::::;;,,,,'''';:cooooollllllloooooooddddddddddooollcc:::    //
//    dl:;;;,''''''''.''............,lddddxxxxxxxxxkkkkxxxdl;,,'......   ... ....',;;;;clc;,,,;:coodxxxxxxxkkkkkOOO000000KKKK000000OOOOOOOOOOOOO000000000000000000000000000000000000OOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxddoc,,,,;;,,clc:c:;;;;,,,'''',::loooddooooooolllllloooooooooooollllccc    //
//    doc:;;,,'''''''.''.............':odddddxxxxxxxxxxxoc:;:,'...  .......  ...,lodxxdodkkxxdllllc:oxxxxxxxkkkkkOOO0000000KK000000OOOOOOOOOOOOOOO000000000000000000000000000000000OOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxddolc,,,,;;,;clccc:;;;;,,,,''',;:cllooddddddddddooooooooooolllllcccccc    //
//    doc:;;;,'''''''.'''.............';lddddddxxxxxxxxo:;;'''.... ,o:....  ...':dkOKK0xdxkxxxdl:,..lxdxxxxxxkkkkkkOOO00000000000000OOOOOOOOOOOOOOO000000000000000000000000000000OOOOOOOOOOOOOOOOOkkkkkkkkkkkkOkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxddol:;;;,;;;;clcclc;;;;;,,,,''',;:ccllodddddddddddddooooooollllllllll    //
//    xdc:;;;,'''''''.'''...............,coddddddxxxddl:''...    .lOKl..... ...',;:okkdllxkxl;.  .'cdddxxxxxxkkkkkkOkkO0000000000000OOOOOOOOOOOOOOOO0000000000000000000000000000OOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxddool:;;;,;;;;clcclc:;;;;;;,,,''',;;:cccllooodddddddddoooooooolllllcc    //
//    xdl:;;;,'''''''.'''................':odddddddddl;,'..     ,xKKKk;...... ....,;;;,,ldc'. ..,lddddxxxxxxxxkkkkkkkxxk0000000000000OOOOOOOOOOOOOOOO0000000000000000000000000OOOOOOOOOOOOOOOOOOOkkkkkkkkOkkOkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxdddolc;;;,,;:;;clcccc:;;;;;;;;,,'''',,;;;::::cccccccccccccccccccc::::    //
//    xxl:;;;,'''''''.'''.................';lddddddol:;;....  .:kK0KKKkc..........''..';;....':lodddxxxxxxxxxxkkkkkkkOkxk000000000000OOOOOOOOOOOOOOOOO000000000000000000000000OOOOOOOOOOOOOOOOOOOOOOkkkOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxddool:,,,,,:::;:ccccc:;;;;;;;;;;,,,''''',,,,,;;;;;;;;;;;;;;:::::::::    //
//    xxoc;;;,,''''''''''...................,cdddool:;,'..   .cO0000000Oxc,'.......'''..  .':lodddxxxxxxxxxxxxkkkkkkkkkkxkO00000000000OOOOOOOOOOOOOOOOO000000000000000000000000OOOOOOOOOOOOOOOOOOOOOOOOOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxxxxxdddolc;,,'',:cc:::c                                                     //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract STARS is ERC721Creator {
    constructor() ERC721Creator("Stargaze Arts", "STARS") {}
}
