
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: AfterGlow
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                            //
//                                                                                                            //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMWX0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMNx;.,kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMM0:'''cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMWk;',;,oXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMWk;'co;,xNMMMMMMMMMMMMMNK0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMNx;;oKOllOWMMMMMMMMMMWKdooo0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMXo;:dNNklo0WMMMMMMMMMKooKKokWMN0KWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMXo;;xNMXd;c0WMMMMMMMWx:xWXxOMW0dxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMKl'.lNMWk'.:0MMMMMMMNo,xWNKNMNkoxXMMMMMMMMMMWNWMMMMMMMMMMMMMMWWWWWMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMXd;,dNMM0;..dWMMMMMMNl'dWMMMMNl.,OMMMMMMMMNklcd0WMMMMMWNXK0kxxddxKWMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMWKOxxKMMMNd'.cKMMMMMMXl'oNMMMMNc .oXWMMMMMKc.','cKMMMW0o::cccccldkXWMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMXdclxXMMMWk,.;OWMMMMMXo'lXMMMMXc. c0XMMMMXl.:xc.:KMMXo'..,lk0KXNWMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMWOc;:kWMMMM0;.'oNMMMMMNd,lXMMMMNl..:x0XNWM0:;xd;:OWMXc..,dKWMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMNx::oKMMMMWNo..;xNMMMMWx;;dxx0WNo. .,:dKWM0;;::dKWMWk,.cKWMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMXo;;o0K0OO0Ox:',lKMMWN0l..;oxKN0c..:lxNMMM0;.cOWMMMNklxXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMM0:.'lkO0KXNWW0o:lOWWXOxl,;xNMNOxo:::ckWMW0l',kWMMMMXdoKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMWx,';OWMMMMMMMWOlcdKMWNNkcckWMMWWKo;;:kWNOdxxcdXWMMMKxOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMNo'.:0MMMMMMMMMKl,,dNMMM0lcxNMMMMNo'''oNNNWMWOooONWWXOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMXl..lNMMMMMMMMMNl. ,0MMMXxdkXMMMMNo..'oNMMMMMWXOxkOKNWWMMMMMMMN00XMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMWk:';OMMMMMMMMMMWk,..oNMMWOdkXMMMMW0c:ckWMMMMMMMMWWNWMMMMMMMMW0l,,oXMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMXo;;dNMMMMMMMMMMMNo..;0MMMN00WMMMMMWNXXWMMMMMMMMMMMMMMMMMMMMWKl,',lXMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMWklcdKMMMMMMMMMMMMMKc.,OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd,',:kWMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMM0lcdKWMMMMMMMMMMMMMMXOONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c'.,oXMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMWd,c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxc,'c0MMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMWOdOWMMMMMMMMMMMMMMMMMMMMMMMMW00NMMMMMMMMMMMMMMMMMMMMMMMMMMMNklc:ckWMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMXdlOWMMMMMMMMMMMMMMMMMMMMMMMMMMKdlddkXMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMNOdkXMMMMMMMMMMMXl,c0WMMMMMMMMMMMMMMMMMMMMMMMMNd'.,c0WMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMKo;oKWMMMMMMMMMMMK;..:KMMMMMMMMMMMMMMMMMMMMMMMWk'   ;0MMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMNd;lKMMMMMMMMMMMMM0;. .xWMMMMMMMMMMMMMMMMMMMMMMNl.  .oNMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMKocOWMMMMMMMMMMMMMXo...lXMMWXXNMMMMMWMMMMMMMMMMXc. .;0WMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWOldXMMMMMMMMMWNWMMWO;..,xWXxlloOXWM0okNMMMMMMMMXd'..cXMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMNkdONMMMMWNKOxlcOWMMXd;',dXk:clccoKWK:,dXMXkkKWMXko:,oXMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMXl'cKMMMXxl::cokXMMMWk:,,lko,:cc::OWWk;'l0d,':kNNkdod0WMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMXc 'OMMMXxc:lONMMMMMW0:..;O0:''';dXMMNx;,c:,,;;ldlllo0MMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWx..dNMMMWKd:ckNMMMMMWx'.'kWXkxxONMMMMNx;'.,ox:'',coxXMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMXc.'xNMMMW0c.:0MMMMMMWkcoKMMMMMMMMMMMMWOc,c0WKko:;lkNMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMM0:.'cdxkOo,,oXMMMMMMMMWWMMMMMMMMMMMMMMWXKXWMMMWK0KNMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMXOkl:cdO0OKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMWWNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                            //
//                                                                                                            //
//                                                                                                            //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract After is ERC721Creator {
    constructor() ERC721Creator("AfterGlow", "After") {}
}
