
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Cyber Baat 1155
/// @author: manifold.xyz

import "./ERC1155Creator.sol";

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                              //
//                                                                                                                                                              //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXKOxdolooodxk0XXXXXXXKOxxk0XXXXXXXXXKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKK00000OOOOO0KXXXXXXXXXXKKK000000KKXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXKOo:'.   ...   ..c0XXKx:'.   .oKXXO:',''';kXXXXXX0c,,,,,,,,,,,,,;:ldOKXXX0xl:;,'.............lKKdc::;;,''...''....';cx0XXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXKd,.   ,cdkOOOxo:..,ON0:        'OXXKo.     cXXXXXNk.        'lo,     .:OXKc        .o,        ;KXd.         :kk:      .xXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXx,    'xKXXXXXXXXXKO0XXk.        'OXXXKc     ;KXXX0d,        .lXXo.      ,0k.       ,OK:        ;KXO,         oXXo     .xXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXx.    .kXXXXXXXXXXXXXXXXKl        :KXXXXO'    ;KXXXo.         .lXXd.      .xc       ;0XK:        ;KK:          oXXo     ,0XXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXo     :KXXXXXXXXXXXXXXXXX0:      .xXXXXXXl    cKXXXKl.        .lXXd.      ;d.     .c0XXK:        lXXk.         oXXo      'xKXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXX0,    cXXXXXXXXXXXXXXXXXKXO,     .l0XXXXXO'   'xKXXXx.        .c00l     .ck:     .l0KKXXo......,o0XKd.         oXXo       ;0XXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXx.   ;0XXXXXXXXXXXXXXKo',xk.      .o0XXXXl     ;OXx'        ...'.     'oKO'      ..'',,,,,;;ckKXXXKo.         'c:.    .;o0XXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXO'    cKXXXXXXXXXXXXKl.  :Kd.       .o0XXO'     ;O:        ,kkkc        .c;          ....',,cOXXXXX0;       'll,       .oKXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXo.     ,oOKXXXXXXKOd,    lXXl.        .o0Xl     'OO,       :KXXd.        ,o.    .:dxkOOo'.'''';dKXKc        lXNd.       ,0XXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXk.        .';cccc:,.     'kXXKc          .oo.    cKXx.      :KXXd.       .xK:     'xXXXK:       .oXXx.       cXXd.       ,0XXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXd.                      .dXXXX0l';c'          .'o0Kk;       :KXXd.       'ONd.     .oKXK:        :KXd.       cXXd.       ,0XXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXX0o;,,,,.               .oKXXXXXXKXO'         l0KXx,.        :KXXd.       .dX0;       :0X:        ;KKl.       cXXd.       ,0XXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXX0o.       'okkxxOXXXXXXXXXXo         ;0XXXo.         :KXNo.        oXXd.       ,d;        ;KXO'       cXXd.       .kXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXO;    .c0XXXXXXXXXXXXXXXK:        .kXXXXKOoc,.     .;;;.     ..:xKXX0;        ..        cKKxc,'... .oXXk' ......,oKXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXX0d;,:xKXXXXXXXXXXXXXXXXXOooooooookXXXXXXXXXK0kdolllooooooodxOKXXXXXX0kkkkkkkkkkkkkkkkkk0XXXXXKK0OkOKXXKOkkOO00KKXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXX0kkkkkkkkOOOOO0KXXXXXXXXXXXXXXXKxlox0XXXXXXXXXXXXXXXXXXXkolclx0XXXXXXXXXXXKKXXXXXXXXXXXXKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXX0;.........'....';lOXXXXXXXXXXXNO'   .,o0XXXXXXXXXXXXXXXXl.    .;xKXXXXXk;',,,,,,',,',,,,',',',dXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXk.       ,kOl.     .oKXXXXXX0occc.      'dKXXXXXXXXXKd:;:'        ;OXXXXd.     ;,      ':.    .dXXXXXXXXKXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXO:.        :KNx.      .xXXXXXO,            .dXXXXXXXXKl              ,OXXX0;    .dl      :x.    cKXXXXKxc;,:ddooOXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXx'         :KNx.      .dXXXX0;   .col,      .kXXXXXXKo.  .cxxxl.      :KXXXd.   .dl      :x.   ;0XXXXXKc..;. ';..l0XXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXO'        :KNx.      :0XXXk,   .dXXXK:      ;0XXXX0c.   ;KXXXXx.     .oXXXk.   .dl      :x.   cXXXXXXXd. .. .',:d0XXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXx.        'od:.   .;d0XX0c.    .oXXXXk.      cKX0o.     ,0XXXXKc      .kXXo    .dl      :x.   .xXXXXXX0, 'dd' ;0XXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXd.       .',.      'cd0Xx'       :KXXXKc      .x0:       .dXXXXXk'      ;0Xd.   .xl      :k'   .oXXXXXXK; ,0Xo. cKXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXo.       ,0Xx.        ,kc        .kXXXXO'      ,o'        :KXXXXXl       cKX0xdoxKc      ;0kodxOKXXXXXXd. ;0XK;  ,xKXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXKo.      ,0Nx.        ,O0l'       :KKKKKl       :xc.      .dK0000x'      .dXXXXXXXc      ;KXXXXXXXXXXXk'   .;,.    cOXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXk.      ;0Nk.       .xXXX0,       .''''.       .oXd.      ..'''..        'OXXXXXXc      ;KXXXXXXXXXXXO:            .,;oKXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXKOo'       ,0Nx.       .xXXXx.       'od:.         .d;       .'lOx,          :KXXXXXc      ;KXXXXXXXXXXXXk.              ,0XXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXd.         ,0Nx.        cKXXk'       .kN0,          ,:.        :KXd.         .oXXXXXc      ;KXXXXXXXXXXXXx.              ;KXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXk:.        'k0o.       .oKXXXk'       cKXo.          lo.       .kN0;          'OXXXXc      ;KXXXXXXXXXXXXO'          ....lKXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXX0xl:,.....''......,:dOXXXXXXOc''''''lKX0l,'''''''',dKx:;;;;;,cOXXkc;;;;;;;;;l0XXXXk:;;;;;xXXXXXXXXXXXXXKo;;;:cclodk0000KXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXX0OOOOOOOOOO0KXXXXXXXXXXXXKKKKKXXXXXXXKKKKKKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    //
//                                                                                                                                                              //
//                                                                                                                                                              //
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract CBAAT is ERC1155Creator {
    constructor() ERC1155Creator() {}
}
