
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: PINUPS
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXXXXXXXXXXNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNXK0kkxxxddoooooll:;:::;:::;;::cloddddddddxxkkkkO0XXNNNNNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOkkxdolc:,'........                         ..     ........''',,,;;:codxxkO0KXNWWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKOxl:,....     ... .....................................................      ......',;:ccldxO00KXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKOxoc;'...  .................................................................................  .   .....';:clodxOKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKOkdoc;'..  .....................................................................................................     ...',codxOKNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0d:'..    ...................................................................................................................    ...,:cdk0KXWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKko;..    ...................................................................................................................................;;,;cldkOKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNOd:'..   ...........................................................................................................................................  ....,:ldk0XNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOo;...  ....................................................................................................................................................     ..';cok0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxc'.. ................................................................................................................................................................    ..';ldkKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKxl,..  ........................................................................................................................................................................    ..,cok0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo,..   ...............................................................................................................................................................................    ..,cdOKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0l'..  ........................................................................................................................................................................................   ..:okXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0l'.   ..............................................................................................................................................................................................   .':dOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXx,..  ....................................................................................................................................................................................................  ..'ckXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0l..  ..........................................................................................................................................................................................................  .'ckXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx;..  .......................................................................................................................................................................................',,,,'.................  .,lONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo'.  ......................................................................................................................................................................................,cdkOOOOkxoc:,'.............  ..;xKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl..  ......................................................................................................................................................................................,oOKKKKKKKKK0Okdl:,'...........   .'ckXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKl.   ...........................................................             ...............................................................................................................,dO0KKKKKKKKKKK00Okdc;'...........  ..;xXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0c..  .......................................................       ....'''''..  .............................................................................................................'ck00KKKKKKKKKKKKKKK0Odc;'...........  .,xXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKc.   .....................................................    ..;codxkOO0000Ol..........................................      .................................................................':x00KKKKKKKKKKKKKKKKK0kd:,'..........  .,dXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo.   ....................................................   .'cdO0KKKKKKKKKK0Ol..................................    ....',,,,'.. ................................................................,cdO0KKKKKKKKKKKKKKKKK0Od:'...........  .,xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk,   ...................................................   .'lk0KKKKKKKKKKKKK0Oc..............................   .';coxxkO00K00kc....................................................................';ldO0KKKKKKKKKKKXKKKK0kc'............  .c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0:.   ..................................................   .ck00KKKKKKKKKKKKKK0k;............................  .;lxOKKKKKKKKKKKKk:.......................................................................';cdk0KKKKKKKKKKKK00Oo,.............  .,xNMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo.    .................................................   'dO0KKKKKKKKKKKKKKKKKk;.......................... ..cx0KKKKKKKKXXKKKKKk;...........................................................................,;coxk0KKKKKK00Od:'...............  .c0WMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMWO;      ................................................  ,dO00KKKKKKKKKKKKKKKKKx;......................... .;x00KKKKXKXXXXXKKKKKk:...............................................................................',;clooddol:,................... .,kNMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMXo.        .............................................  .oO0KKKKKKKKKKKKKKKKKKKk;........................ .:k0KKKKXXXXXXXXXKKKKKk:................................................................................................................  .oXWMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMW0;.   ....    .........................................  .:k00KKKKKKKKKKKKKKKKKK0x;.........................,x0KKKKKXXXXXXXXXXKKKKOc.................................................................................................................. .lKWMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMNd.   ........     .....................................  'dO0KKKKKKKKKKKKKKKKKKK0x,....................... .lO0KKKKXXXXXXXXXXKKXKK0l..................................................................................................................  'xNMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMKl.  ............       ................................ .:k00KKKKKKKKKKKKKKKKKKK0x;........................'oOKKKKKXXXXXXXXXXXKKKK0o'....................................................................................................................;OWMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMW0:.  ..................       .........................  .oO0KKKKKKKKKKKKKKKKKKKKK0o;....         ..........'d0KKKKKXXXXXXXXXXXXXKK0d,.....................................................................................................................;kWMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMWO,   .........................        ................   .oO0KKKKKKKKKKKKKKKKKKKKKKK0Okxxdolcc:;;,''''''....:x0KKKXXXXXXXXXXXXXXXKKKk:......................................................................................................................,kNMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMWx.   ..................................                  .ck00KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK000000OOkkOKKXXXXXXXXXXXXXXXXXXXKK0o'......................................................................................................................;OWMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMNd.   .........................................         ...'oO00KKK0Oxdk0KKKKKKKKKKKKKXXXXXKKKKKKKKXXXXXXXXKKXXXXXXXXXXXXXXXXXXXXXXKKKx;.......................................................................................................       ....... .cKMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMWx.   ........................................       .,c:. .;xO00Od:'..:x0KKKKKKKKKKXXXXXXXKKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKOl'...................................................................................................  ......           .dXMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMWO,   .....................................       .':dxd;..'oOOkd;...,lk0KKKKKKKKKKKKXXXXXXKKXXXXXXXXXXXXXXXKXXXXXXXXXXXXXXXXXXXXXXXXKKkc..................... ............................................................................ ...............     .ckXWMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMXl.   ..................................      ..;lddol;...'clc,...,ok00KKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXXXXKKKKKKXXXXXXXXXXXXXXXXXXXXXXKK0ko:'...  ..........   ............................................................................ .................... ..'ckXWMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMW0;.   ..............................       ..',,'....   .....   .,lxO0KKKKKKKKKKKKKKKKKKXXXXXKKKKXXXXXKKKkc:oOKKKXXXXXXXXXXXXXXXXXXXXXXXKK0kdolc;,'.....................................................................................  ........................ .,dKWMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMWO,    ...........................         ..  ...',;;;;::::;'.    .;ok00Okdocclk0KKKKKXXXXXKKKKKXXXKKKK0o..;x0KKKXXKKKKOdoookKKKKXXXXXXXXXXXXXXKK00OOOOOkc.............................................................................   ......................... .'lONMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk,     ......................            .';cloddoollc:;'..        .,;;'.  .'cx0KKKKKKKKXXKKKKKKXKKKK0k:..:k0KKKKKK0kl,...,d0KKKXXXXXXXXXXXXXXXXXXXXKKKk;.............................................................................      ........................ .'oKWMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0:.      ................           ..;ldxkxdoollc:;'.               ..,:lxO0KKKKKKKKKKKKKKKOkdlc:;;,'....;:cldxxo:...,clk0KKKXXXXXXXXXXXXXXXXXXXXXKKKx,..................................................................................    ....................... .;kNMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd'        ...........     ....  .;lxkkkxdollcc:,.                 .:xO00KKKKKKKKKKKKK0koc;'.....'',,,'''..........'lO00KKKKXXXXXXXXXXXXXXXXXXXXXXXKKd'.....................................................................................     .................... .'xNMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0o,.                  .':;'. .;oxkkkxdollccc;.                   .ck00KKKKKKKKKK0ko:'....,:lodxxxddoollllcc;'.....;oxO0KKKKKXXXXXXXXXXXXXXXXXXXXKKKo'....................................................................................        ................... .'xNM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkc'.             .;oo:...;okkkkkdollccccc:'.                  .ck00KKKKKKK0kl;....,coxkOkkxxdoollllllllllc:,......,oO0KKKKKKKKXXXXXXXXXXXXXXXKK0l...    ......................................................................         .....    ....................,kN    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkl,.       .'cxkd;. 'lxkkkkxdlllccccc:;'..                 .ckO00KKK0Oo;....;lxkOOOkxddoolllllllllc:;,'...      .lxxdoc;,;oOKKXXXXXXXXXXXXKK0l.........        ...................................................           ...............  .................. .:0    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo.     .;okOOx:..'okkkkkxollccccc:,.                     .',,;:lddl,. .'cdkOOOOkxdolllllllllc:;'...            ......,:lx0KKXXXXXXXXXXXXXK0l.........................                                          ............................  .................. 'd    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0o;.   .,lxOOOOxc..'okkkkkxolcccccc:'.                     .;cc:;,'..  .'lxkOOOOkkdoolllllllc:,..                  .;cdk0KKXXXXXXXXXXXXXXXXKK0l................................................................................................. ...................:    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOc.    .:dkkxl:,'.. .cxxxkxxolcccccc:'.                     .;cllll:'.  .cxkOOOOOkxollllllllc;..                    .:k0KKKKXXXXXXXXXXXXXXXXXXK0o.....................................................................                                                     //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract PINUPS is ERC721Creator {
    constructor() ERC721Creator("PINUPS", "PINUPS") {}
}
