
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: JimmyDrs
/// @author: manifold.xyz

import "./ERC721Creator.sol";

/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                     //
//                                                                                                                                     //
//    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0000000000000000000000000000000000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0dlllllllllllllllllllllllllllllllld0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0kxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxk0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK00000000000Oocccco0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN0lcoO00KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0dlllllllllloOK000KXNNNNNNNNNNNNNNNNNNNNNNNNNNNWWWWWNK0kold0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKKKK0kxxxxxdooooodxxxxkKNNNNNNNNNNNNNNNNNNNNNNNXK0KKKKNNNWWWMMWWWKkxxxxk0KKKKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKK00OocccccxkkkkOXNNNNNNNNNNNNNNNNNNNNNNNNNNNXXKOkkkkOXXXNNNWMMMMWNNOc:o0KKKKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKK0xlldxxxxxkkkkkOKNNNNNNNNNNNNNNNNNNNNNNNNNNXOO0KXXXXKOO0XNNNNNNNNNNOc:d0KKKKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKK0d:cdkkkkkkkkkkO0KKKKKXNNNNNNNNNNNNNNNNNNNNXOxOXNNNNKkkOXNNNNNNNNNNOc:o0KKKKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKK0o;:oxxxxxxxxxxxxxxxxkKXXXXXXXXXXXXXXXXXXXXKOkOKXXXXKkkOXXXXXXXXXKKklcd0KKKKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKO;  .................'d0OOOOOOOOOOOOOOOOOOOOOkOOOOOOOkkOOOOOOOO0o'.:kO0KKKKKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKO,                   .,::::coxdlclccclccclccllcccccccclllcccclcl,  ,OKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKO,                         .;l:,.''.'''''''''''''',,,,,,,,,'''''.  'xOOKKKKKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKO,                           ..:lllllodddddddddddk0KXXXXXK0xdoll,   ..:OKKKKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKK0o:;.         .         .  . ...,,,,,,;;;;;;;;;;;:llllllllc;;,,,.     .:ccccd0KKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKKKKO,       ...................                                             ,OKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKKKKO; .;ooooc.                 ..................................,;;;;.     ,OKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKKKKO; .cxxxxdlcccccccccccccccl:.... ....  ..  ......  ...... .........':::::d0KKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKKOkx, .cxxxxkKNNNNNXXXXXXXXXXNO, .    .                               ,xOOKKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKK0c....'lxxxxkKNNNNXOkkkkkkkkkkxdoooooooooooooooooooooool:;;;;;;;;;;;;;,..:OKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKO; ..',lxxO00XNX00kl;;;;;;;;;;:oxxO00000000000000000Oxxo,'''''''''';lo;. ;OKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKO; .',;oxkKNNXXKxol'..........'cod0XXXNNNNNNNNNNNNXX0doc...........,lo:. ;OKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKO; .:ddxxkKNXOkd,..;cccccccccc:'.'okO0XNNNNNNNNNNKOko'.':cccccccccc;...  ;OKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKO; .cxxxxkKNKo;;,,;clllllllldxo:,,;;lx0NNNNNNNNNN0c;;,,;clllllllodxl;,'. ;OKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKO; .cxxxxkKNK; .;lllllc:coddkkxol:. ,lONNNNNNNNNNk' .cllllc::codxkkxll;..;OKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKO; .cxxxxkKNK; .;llllc. 'kNXxllll:. ,lONNNNNNNNNNk' .cllll;..:KN0ollll;..:OKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKK0o::'..cxxxxkKNK; .;llll:. .;lllllll:. ,lON0occccdKNk' .:llll;. .clllllll;..:OKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKO;  .',lxxxxxKNK; .:ooool,....'cooooc. ':d0d'....,x0d. 'cooooc'....,loooo:..:OKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKO; ..',lxxxxkKNK; .oOOOkkkkkkkkkOOOOd' .....',;cl:.... 'xOOOOkkkkkkkOOOOOl..;OKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKO; ..',lxxxxkKNXkooc;cOXXXXK0OOOOkc::::;'. ...':c;. .ldl:;oKXXXXK0OOOOxc:'. ;OKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKO; ..',lxxxxx0KXXNKl';x0000Oxddddo;';dOdc,.....,,,''cKWO:'ck0000Oxddddc'..  ;OKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKO; ..',lxxxxxxxkKNXXXO:..........,kXXXXKOxodddc. ,kXXNNXXXx'..........,od:. ;OKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKO; ..',lxxxxxxxkKNNNNXkddddddddddxKNNNNXKK0000OdoxKNNNNNNNKxdddddddddddxxc. ;OKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKO; ..',coodxxxxkKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKxxc. ;OKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKO; ..'',,;lxxxxkKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKxxc. ;OKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKO; ..'''',;:coxxOO0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKxxc. ;OKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKO; ..''''''',coodxx0KKXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXKKOdo:. ;OKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKK0; ..'''''''''';oxxxxkKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKkxo,,.. ;OKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKK0o;;'..''''''''''',lxxOK0OOOOOOOOOOOOOO0XNNNNNNNNNNNNNNNNNX0OOOOOOOOOO00Kx:;'. ;OKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKK0;  .''''''''''''',lxkKNX0kkkkkkkkkkkkkOKKKKKKXXNNNNXKKKKK0Okkkkkkkkkk0XNOc:,..,dxkKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKK0: ..''''''''''''',lxkKNNXNNXNNNNNNNXXNKkxxxxxkXNNNNKkxxxxOXNXNNNNNNNNNNNOc:;''...:0KKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKK0; ..''''''''''''',lxkKNNNNNNNNNNNNNNNNXKKKKKK0OOOOOO0KKKKKXNNNNNNNNNNNNNOc:;''.. ;OKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKK0; ..''''''''''';;:oxkKNNNNNNNNNNNNNNNNNNNNNNNXOkOOk0XNNNNNNNNNNNNNNNNNNNOc:;''.. ;OKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKK0; ..'''''''''',lxdxxkKNNNNNNNNNNNNNNNNNNNNNNNNNXNNNXNNNNNNNNNNNNNNNNNNNNOc:;''.. ;OKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKK0; ..'''''''''',lxxxxkKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNOc:;''.. ;OKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKK0; ..'''''''''',lxxxxkKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNOc:;''.. ;OKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKK0; ..'''''''''',lxxxxkKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNOc:;''.. ;OKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKK0; ..'''''''''',lxxxxkKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNOc:;''.. ;OKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKK0; ..'''''''''',lxxxxkKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNOc:;''.. ;OKKKKKKKKKKKKKKKKKKKKKK    //
//                                                                                                                                     //
//                                                                                                                                     //
//                                                                                                                                     //
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract JDS is ERC721Creator {
    constructor() ERC721Creator("JimmyDrs", "JDS") {}
}
