
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Aerial Creations
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                        //
//                                                                                        //
//    MMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk.  :XMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKKd.  :XMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:...   :XMMMMMM    //
//    MMMMMMMMMMMMMMMMMMWNNNNNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK,  .. .cXMMMMMM    //
//    MMMMMMMMMMMMMMMMMWk,'''''''''cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK,  'dOOKNMMMMMM    //
//    MMMMMMMMMMMMMMMMMWo          '0MMMMMMMMMMMMMMMMMMMMMMWWMWMMMMMMMK,  ,KMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMKkxd,  .cxxONMMMMMMMMMMMMMMMMMMKl;:::;cOWMMMMMNOxxONMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMNc  .kMMMMMMMMMMMMMMMMMMMMMMO.      oWMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMNkllxXMMMMMMMMMWOoldXMMMMMMMMMMMMMMMMMMMMMMXxll;.  oWMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMK;  '0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx.  oWMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMK;  '0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx.  oWMMMMMMMMMMMMMMMMWKxdx    //
//    MMMMMMK;  '0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx.  oWMMMMMMMMMMMMMMMMWl       //
//    MMMMMMXo''cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO;',kWMMMMMMMMMMMMMMMMWl       //
//    MMMMMMMWNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNWWMMMMMMMMMMMMMMMMMWl       //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl       //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl       //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo. .    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOOO    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0l:ccccl0MMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx.     .xMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMNkllxXMMMMMMMMMMMMMMMMMMMMMMx.     .xMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMX;  '0MMMMMMMMMMMMMMMMMMMMMMx.     .xMMMMMMMMMMMMMMMMMM    //
//    MMMWMMMMMMMMMMMMMMMMMW0xxo.  '0MMMMMMMMMMMMMMMMMMMMMM0l:::::l0MMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMNc      '0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMWK000000KWMMMMMNd'''.  '0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK000000XWMMMMMM    //
//    MMMMMMX:  ..  :XMMMMMMWNN0,  '0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;  .. .lNMMMMMM    //
//    MMMMMMX;      ;XMMMMMMMMMXc..;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXXO'   ...oNMMMMMM    //
//    MMMMMMX;      ;XMMMMMMMMMWXKKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl...   'kKKNWMMMMMM    //
//    MMMMMMX:      :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc      ;KMMMMMMMMMM    //
//    MMMMMMWKkkOOkOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKOkOOkk0WMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0doodKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWo   .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMW0kk0NMMMMMMMMMMMMMMMMMMMMMMMMWo   .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMX;  ,0MMMMMMMMMMMMMMMMMMMMMMMMWo   .dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMX;  .xKKXWMMMMMMMMMMMMMMMMMMMMWo   .l00KWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMX;   ...cXMMMMMMMMMMMMMMMMMMMMWo    ...,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMX:...   ;XMMWNNNWMMMMMMMMMMMMMWd. .....,0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMWX00d.  ;XMWx,.,kWMMMMMMMMMMMMMN0000000KWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMM0'  ;XMWo  .dWMMMMMMMWWWWWWMMMMMMMMMWWWWWWWMMMMMMMMWWWWMMMMMMMMWWWWWWW    //
//    MMMMMMMMMMNOxx0WMWo  .dWMMMMMXo;;:;;:kWMMMMMMXo;;::;;dNMMMMMNx;;lKMMMMMMOc;;:;;:    //
//    MMMMMMMMMMMMMMMMMWo  .dWMMMMM0'      lNMMMMMMK,      :XMMMMMX:  .OMMMMMWd.          //
//    llllllllllxXMMMMMWo   ,lldKMM0'      lWMMMMMMNkoo:.  .clo0WMX:  .;llllll,           //
//              '0MMMMMWo      .kMM0'      lNMMMMMMMMMMO.      oWMX:                      //
//    .  .  ..  ,0MMMMMWd.  .  'OMM0,  .. .oNMMMMMMMMMMO'  .. .dWMXc  ..  ..  ..  .  .    //
//                                                                                        //
//                                                                                        //
//                                                                                        //
////////////////////////////////////////////////////////////////////////////////////////////


contract SKYRON is ERC721Creator {
    constructor() ERC721Creator("Aerial Creations", "SKYRON") {}
}
