
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Uji Hahan Handoko Eko Saputro
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                        //
//                                                                                        //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXXXXXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMWX0kdodoc:okkkkkkoclldk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMN0kxkxocdOKXKdckWMMXxokOxlcoxkkk0NMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMNOxxkOXNX00OkdxXWkckNOlxXOdkOxxKNXOxxxONMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMWKxdkKWMMMWXOxloocOWNOoddOW0llddkKNWMMMWKkxxKWMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMW0ddONMMMMMMW0xxlclxXK0WMMMKK0dxdodONMMMMMWWNOdd0WMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMKdd0WNNMMMMMNOdldOOOXMXxkNWOdKW0OKOdoo0WMMMNKWMW0ddKMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMNkoOWMN0KMWXkdlok0NMWWWWWXkddd0WMMNWMXOo:lOWMWKKWMMWOokNMMMMMMMMMMMM    //
//    MMMMMMMMMMMXddXMMMWXNWKOkOXWMMMMMMWKXMMMWMMMMWWMMMMWKkx0WW0kKMMMMXddXMMMMMMMMMMM    //
//    MMMMMMMMMMKoxNMMMMMMMMMMMMMMMMMMMMW0KWMMMMMMWXXWMMMMMMMMMMNXNMMMMMNxoKMMMMMMMMMM    //
//    MMMMMMMMMKoxWMKkXMXk0KxxxxkOKWMMMMMWWMMMMMMWKOXMMMMWKOkkkk0XO0WW00WWxoKMMMMMMMMM    //
//    MMMMMMMMNodNMMXxx0KkoooodxdoolkNMMWWMMMMMMMWKKWMMKdlooddoldoo0KOdOWMNdoNMMMMMMMM    //
//    MMMMMMMWxoXMNNWMWK0x:okokO0XO:;OMMXNMMMMMMMMWWMMWl'dXN0OddxclO0XWMMMMKokWMMMMMMM    //
//    MMMMMMMKlkMN0k0NMMW0lx0kOkdc:dKWMWKKWMMMMMMMMMMMMXkl:lxOxkOldNMMMWWWMMkoKMMMMMMM    //
//    MMMMMMMklKMWXOONMMN00KXNWWMXxldKWWXXWMMMMMMMMMMMNOookNWNNXK0OXMMMMNKNWKlkMMMMMMM    //
//    MMMMMMWddWMMN0KWMWkxWMMMMMMMMXd:ckNMMMMMMMMMMMXxcckNMMMMMMMWOdKMMMWX0NWddWMMMMMM    //
//    MMMMMMNoxMMMMMMMMNOx0XXNWWWWNXXk;.,kNMMMMMMMKo''oKNWMMMMWWNKkxXMMMMWWWMxoNMMMMMM    //
//    MMMMMMNoxMMMMMMMMWXOOKK000OOkxddoookNXxdddOW0oclodxkkO000KKOkKWMMMMMMMMxoNMMMMMM    //
//    MMMMMMWddWMMMMMMMMM0xXMMMWWMMMMMMMMMXddKXkckWMMMMMMWWWWMMMNkOWMMMMMMMMWddWMMMMMM    //
//    MMMMMMMxoXMMMMWWWWWWkxNMMXXWMMMMMMMWkkWMMMkdXMMMMMMMNXWMMWkkWWWMMMMMMMXokMMMMMMM    //
//    MMMMMMM0lOMMMWKXWWWW0dKMW0ONMMMMMMMN0XMMMMNOKMMMMMMMX0XMMKd0WNNNXNWMMMOlKMMMMMMM    //
//    MMMMMMMWdoNNXWKOXWWWkoKMMNXWMMMMMMMWWMMMMMMWWMMMMMMMNKNMM0oOWX0OkKWWWNoxWMMMMMMM    //
//    MMMMMMMMKoxXKWWKkkkxlOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdl0KOx0NNKXxoXMMMMMMMM    //
//    MMMMMMMMM0lOWMWX0olxokNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOodxcl0XWXKkl0MMMMMMMMM    //
//    MMMMMMMMMMOlOWMNKKNMXxdONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOdd0WW0O0XWWOl0WMMMMMMMMM    //
//    MMMMMMMMMMM0okNMMMMMMMXkdkKWMMWWMMMMMMMMMMMMMMMMMMMWKkdx0WMMMMMMMNxo0MMMMMMMMMMM    //
//    MMMMMMMMMMMMXddKMMMMMMMMNOxxkOKXXNNWWWMMMWWNNNNNXOkxdxXMMWNNMMMMKodXMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMWOoxXMMMWNWMWNKkdxdlodxkO000OkxxxdllldOXWMMWXKNMMXxoOWMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMNkdkXMMKOXWMWXK0o;lkkkdlccokO00xclkKWMMMMWKXWXxdkNMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMNkdxOXNWMMMMMNkoxOKKO00kkOXKOkdkNMMMMMMMNOxdONMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMWKxxxOXWMMMMNxONXXNWKOKXKKN0xXMMMMWXOxxxKWMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMWKkxkkk0XWOxXMMMWKOXMMMWkONK0kkxxkKWMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMNKOkkkxlkWMMMX0XMMM0oxkkkOKWMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0d0MMMWNWMMKx0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0d0MMMMMW0x0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKxkKXXKkxKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0OOOOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                        //
//                                                                                        //
//                                                                                        //
////////////////////////////////////////////////////////////////////////////////////////////


contract UHHES is ERC721Creator {
    constructor() ERC721Creator("Uji Hahan Handoko Eko Saputro", "UHHES") {}
}
