
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Lukerz
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                            //
//                                                                                                            //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMWX000000000000000000000000000000000000000000000000000000000000000000000000000000000000KNMMMMMM    //
//    MMMMMMWx'...................................................................................lXMMMMMM    //
//    MMMMMMMNd.   '::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::,.   cXMMMMMMM    //
//    MMMMMMMMWk'  ,0WMMMMMMMMMMMMMNOocccccccccccccccclodONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc  .oNMMMMMMMM    //
//    MMMMMMMMMW0,  'kWMMMMMMWNKOxl,.                    .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK;  .xWMMMMMMMMM    //
//    MMMMMMMMMMMK:  .dNMMMMXo'.                         'OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO,  'OWMMMMMMMMMM    //
//    MMMMMMMMMMMMXl. .oXMMMNx'                          .:oood0WMMMMMMMMMMMMMMMMMMMMMMWx.  ;0MMMMMMMMMMMM    //
//    MMMMMMMMMMMMMNd.  cKMMMMK:.   .;,.                       .l0WMMMMMN0kddkXMMMMMMMNo.  cXMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMWk.  ;0WMMMNOdokXWWKl.                      ,OWMMNOl,.  .;0MMMMMMXl. .oNMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMWO,  'OWMMMMMMMMMMMNkc::'                  ,dkdc'.   ;dONMMMMMMK:  .xNMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMK:  .xWMMMMMMMMMMMMMMMK,                          ,0MMMMMMMWO,  'OWMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMXl. .oNMMMMMMMMMMMMMM0'                         .dWMMMMMMWk.  ;0WMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMNd.  cXMMMMMMMMWNKOd,                           ':d0WMMNd.  cKMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMWx.  ;0MMMMMMKl,.                                 .kWXl. .oNMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMWO,  'OWMMWk,                                    :KK:  .dNMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMK:  .xWWx.                                   .oX0,  'kWMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMXc  .oNK:                                  'xNk'  ;0WMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMNo.  cXXc        ....                    ;0Nd.  :KMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMWx.  :KXl.    .c0XX0o.        .',....,:dXXl. .lXMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMWO'  ,ONd.    .,lOWWO;     ,dKNWXKKXNWMK:  .dNMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;  .xXx.      ;KMMXkdddONMMMMMMMMMW0,  'kWMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXc  .dXk'    ,OWMMMMMMMMMMMMMMMMMWk'  ,0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo. .lXO,   lNMMMMMMMMMMMMMMMMMNx.  :KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNx.  :K0;  ,KMMMMMMMMMMMMMMMMNo. .lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO'  ,OKc  ;0WMMMMN0KWMMMMMXc  .dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0;  .kKl. .lOOxo;.lNMMMM0;  .kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKc  .dKo.        .kWMWO'  ,OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNo. .lKd.        oWWx.  :KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd.  :0k.      'ONo. .lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk'  ,OO,    .x0c  .oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0,  'kO;  'k0;  .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:  .d0xx0O'  ,OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl. .lKNx.  ;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd.  .'.  cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk.    .oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0,  .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKdoOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                            //
//                                                                                                            //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract LKRZ is ERC721Creator {
    constructor() ERC721Creator("Lukerz", "LKRZ") {}
}
