
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Twelve Sunrises
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                            //
//                                                                                                            //
//    MMMWNXXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXXNWMMM    //
//    MWNXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXNWM    //
//    WXKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKXW    //
//    XKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0OOOO0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKX    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK000KKKKKKKKKKK0OxxxxO0KKKKKKKKKKK000KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0OkkO0KKKKKKKKK0kxxxxk0KKKKKKKK00OkkO0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0kxxxkO0KKKKKK0kxxxxxxO0KKKKKK0Okxxxk0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0Oxxxxxk00KKKKOxxxxxxxxOKKKK00kxxxxxO0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK0OxxxxxxkO0KK0kxxxxxxxxk0KK0OkxxxxxxO0KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKK00OO000KKKKKKK0kxxxxxxxkO0OxxxxxxxxxxO00kxxxxxxxk00KKKKKK000OO00KKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKK0kxxxkkO00KKKK0kxxxxxxxxxkkxxxxxxxxxxkkxxxxxxxxxk0KKK000Okkxxxk0KKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKK0OkxxxxxxkOO000kxxxxxxxkkOO0000000000OOkkxxxxxxxk000Okkxxxxxxk0KKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKK0OkxxxxxxxxkkOkxxkO00KXXNNNNNNNNNNNNNNXXK00OkxxkOkxxxxxxxxxk00KKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKK0kxxxxxxxxxxkO0XXNNNNNNNNNNNNNNNNNNNNNNNNXX0Okxxxxxxxxxxk0KKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKKKKKK0kxxxxxxxk0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0kxxxxxxxk0KKKKKKKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKK0000000KKKK00Oxxxxk0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0Oxxxxk00KKKKK000000KKKKKKKKKKK    //
//    KKKKKKKKK0OkkkkkkkkOOOOOOkxk0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0kxkOOOOOOOkkkkkkkO0KKKKKKKKK    //
//    KKKKKKKKK0OkxxxxxxxxxxxxxxkKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKkxxxxxxxxxxxxxxkO0KKKKKKKKK    //
//    KKKKKKKKKK00OkxxxxxxxxxxxOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKOxxxxxxxxxxxkO00KKKKKKKKKK    //
//    KKKKKKKKKKKKK00OkxxxxxxxOKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKOxxxxxxxkO00KKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKK0OkxxxxkKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKkxxxxkO00KKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKKK0Okxx0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0xxkO00KKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKK0000OOOkkxkKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKkxxkkOOO0000KKKKKKKKKKK    //
//    KKKKKKK00OOkkkxxxxxxxxOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXOxxxxxxxxkkkOO00KKKKKKK    //
//    KKKKKK0OxxxxxxxxxxxxxxOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXOxxxxxxxxxxxxxxO0KKKKKK    //
//    KKKKKK0OOkkxxxxxxxxxxxOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXOxxxxxxxxxxkkkO00KKKKKK    //
//    KKKKKKKK0000OOOkkkxxxxkKNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKkxxxkkkOO00000KKKKKKKKK    //
//    KKKKKKKKKKKKKKKK000Okxx0NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN0xxk000KKKKKKKKKKKKKKKKK    //
//    KKKKKKKKKKKKKKKKK0OkxxxOXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXOxxxkO00KKKKKKKKKKKKKKKK    //
//    0000000000000000Okxxxxxx0XNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0xdxxxxkO0000000000000000    //
//    llllllllllllllllccccccccloooooooooooooooooooooooooooooooooooooooooooooooooolccccccccllllllllllllllll    //
//                                                                                                            //
//                                                                                                            //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract SUN12 is ERC721Creator {
    constructor() ERC721Creator("Twelve Sunrises", "SUN12") {}
}
