
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Bart Oatmeal
/// @author: manifold.xyz

import "./ERC1155Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                            //
//                                                                                                            //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKdcldxkO00KXWMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl'''''',,,;;l0WMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKo;''''''''''''dNMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl'''''''''''''':dXMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMWNNNWMMMMMMMMMMWWMMMNc ;KMMMMMMMMMMMMMMMWX0OkkO0XWMMXl,''''''''''''''',dNMMMMMMMMMM    //
//    MMMMMMMMMMMMMW0dlllc;;xNMMMWWWMXockNWk. 'kWMMMMMMMMMMMMWKxolooollld0W0:.''''''''',''.'''lXMMMMMMMMMM    //
//    MMMMMMMMMMMMWx..l:;o; ;KNOocclk0c..cKx. oXNWMMMMMMMMMMWOloxxxxxxxdocx0c....;llclooc'...'xWMMMMMMMMMM    //
//    MMMMMMMMMMMMWkcdo..:..l0l.':',xkl. ,xc. :dkNMMMMMMMMMMKolddddddddddlcxl..,c;lkxx0k:;,. .oNMMMMMMMMMM    //
//    MMMMMMMMMMMMKdll' ;k: 'o, ':..ck0o;cdkxod0NMMMMMMMMMMMKooxxxxxxxxddlcO0;.lOldKkxKOlko...:XMMMMMMMMMM    //
//    MMMMMMMMMMMWk'.'':lc:cON0dkKK0XWMWWWMMMMMMMMMMMMMMMMMMNxloddddddddoldX0,.:xOOkdoxOOkc.. .xWMMMMMMMMM    //
//    MMMMMMMMMMMMN0xkKNXKNNKKXXXNWXXXKKNWXKNNXNMMMMMMMMMMMMMNOolooddoollxXWK:.':ooc,,:ldl;....xWMMMMMMMMM    //
//    MMMMMMMMMMMMNOkkOOxdk0kdOOdxxdkxldkOxdkOxkKNMMMMMMMMMMMMWX0kdlloxOKWMMW0c'........... .,kNMMMMMMMMMM    //
//    MMMMMMMMMMMMMWXXNXNNXNNXNNXXXXXXXXXXNNXXXXNWMMMMMMMMMMMMMMMWklllxOXWWWWWNk'. .......;oxKWMMMMMMMMMMM    //
//    MMMMMMMMMMMMMWNKKNMWWWWWWWWWWWWMMWWMMMWWMMMMMMMMMMMMMMMMMMMXdloooodxxxxddo:'''''''',cOWMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMN0kkKX0K0O0KK000KKKKKKKKKKNMMMMMMMMMMMMMMMMMMMW0xxdddxxxxdddoc:coddl:;:cokXWMMMMMMMMMMM    //
//    MMMMMMMMMMMMMWKkxKNXNNNNNNNNNNWNNWWWWWWWMMMMMMMMMMMMMMMMMMMMMWNX0Okxdddol::cccccc::oxxddONMMMMMMMMMM    //
//    MMMMMMMMMMMMMWx;:0X000KKK0KK00KKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXk:,,,;::::;:odxxxdx0WMMMMMMMM    //
//    MMMMMMMMMMMMMWXxdOXXKKXXXXXXXXNNNNNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKo:c;;,;,,;:ccccoxxddONMMMMMMM    //
//    MMMMMMMMMMMMMWKxlo0K00KK0KK0KKXKKK00K0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo:llllllcccllll;:odxxdxXWMMMMM    //
//    MMMMMMMMMMMMMXxlldKXXXNNXXNXXNXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWkcllllllllllllol:cdodxxddkKWMMM    //
//    MMMMMMMMMMMMMXl;;l0K0KXXKKKK0KKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWk::lllllllllllll;;ldxkdooldXMMM    //
//    MMMMMMMMMMMMMMWWNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo'.',;;;;;;;;;,'.:0NWWX0O0XWMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWx'................;0MMMMMMMMMMMM    //
//                                                                                                            //
//                                                                                                            //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract BRTOAT is ERC1155Creator {
    constructor() ERC1155Creator() {}
}
