
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Darrell Thorne
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                            //
//                                                                                                            //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXOOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKkxKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKdd0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0ll0MMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMMMMMMMOccOMMMMMMMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXKWMMMMMMk:;kMMMMMMWKXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXOKMMMMMMk,,kMMMMMMKOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWxkMMMMMMx''xMMMMMMOxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkoNMMMMMx..xMMMMMNdxMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOcOMMMMMd..dMMMMMOcOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXXWMMMMMK:oWMMMWo..oWMMMWo:KMMMMMMXXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk0MMMMMNl;KMMMMd..dMMMMX:cNMMMMM0kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0o0MMMMMd'kMMMMk;;kMMMMk'dMMMMM0lOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd:0MMMMKcxMMMMKdd0MMMMxcKMMMM0:oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMN0KWMMMXccXMMMW00MMMMNXXNMMMMK0WMMMXc:XMMMWK0NMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMKllKMMMXOXMMMMWWMMMMMMMMMMMMWWMMMMXOXMMMKllKMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMXdOWMWNXK0OOOOOOkO0XWWX0OkOOOOOO0KXNWMWOdKMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdl:,',;;;,.   'oOXWWXOo'   .,:;;,',:ldOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMNOo:,;:codk0XNWK,  .kMMMMMMMMO.  ,KWNX0kdoc:;,;oONMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMNOl'..lOWMMMMMMMMMK,  .OMMMMMMMMO'  ,KMMMMMMMMMW0l..'lONMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMNx;  ,dXMMMMMMMMMMMMK,  .OMMMMMMMM0'  ,KMMMMMMMMMMMMXd,  ,xNMMMMMMMMMMMMMMMMMMMM    //
//    cccccccccccoxONMMMNx, .:kNMMMMMMMMMMMMMMK,  .OMMMMMMMM0'  ,KMMMMMMMMMMMMMMNkc. 'xNMMMN0xoccccccccccc    //
//          .,cok0XNMMM0:.'oKWMMMMMMMMMMMMMMMMK,  .OMMMMMMMM0'  ,KMMMMMMMMMMMMMMMMWKo'.;0WMWNX0kdc,.          //
//       .;d0NMMMMMMMWk..lNMMMMMMMMMMMMMMMMMMMK,  .OMMMMMMMM0'  ,KMMMMMMMMMMMMMMMMMMMNo..xWMMMMMMMWKd;.       //
//      ,OWMMMMMMMMMWd. :XMMMMMMMMMMMMMMMMMMMMK,  .OMMMMMMMM0'  ,KMMMMMMMMMMMMMMMMMMMMN: .dNMMMMMMMMMWO,      //
//      dMMMMMMMMMMWd. .OMMMMMMMMMMMMMMMMMMMMMK,  .OMMMMMMMM0'  ,KMMMMMMMMMMMMMMMMMMMMMO. .dWMMMMMMMMMMx.     //
//     .xMMMMMMMMMMO.  oWMMMMMMMMMMMMMMMMMMMMMK,  .OMMMMMMMM0'  ,KMMMMMMMMMMMMMMMMMMMMMWo  .kMMMMMMMMMMx.     //
//     .xMMMMMMMMMX:  ;XMMMMMMMMMMMMMMMMMMMMMMK,  .OMMMMMMMM0'  ,KMMMMMMMMMMMMMMMMMMMMMMX;  ;XMMMMMMMMMx.     //
//     .xMMMMMMMMMk. .kMMMMMMMMMMMMMMMMMMMMMNXK;  .OMMMMMMMM0'  ,0XNMMMMMMMMMMMMMMMMMMMMMk. .xMMMMMMMMMx.     //
//     .xMMMMMMMMWl  lNMMMMMMMMMMMMMMMMMMMMNdo0;  .OMMMMMMMM0'  ,0ooNMMMMMMMMMMMMMMMMMMMMWo  lWMMMMMMMMx.     //
//      ,ooooloool. .;ooooooolooooooooooool; :0;  .OMMMMMMMM0'  ,0c ,looooooooooooooooollo:. .coooooool,      //
//                                           :0;  .OMMMMMMMM0'  ,0c                                           //
//      ,loooooool. .:olooooooooooooooooool, :0;  .OMMMMMMMM0'  ,0c ,loooooooooooooooooooo:. .coooooool,      //
//     .xMMMMMMMMWl  lWMMMMMMMMMMMMMMMMMMMMNdo0;  .OMMMMMMMM0'  ;0ooNMMMMMMMMMMMMMMMMMMMMWo  lWMMMMMMMMx.     //
//     .xMMMMMMMMMk. .kMMMMMMMMMMMMMMMMMMMMMNXK;  .OMMMMMMMM0'  ,0XNMMMMMMMMMMMMMMMMMMMMMO. .xMMMMMMMMMx.     //
//     .xMMMMMMMMMX:  ;XMMMMMMMMMMMMMMMMMMMMMMK,  .OMMMMMMMM0'  ,KMMMMMMMMMMMMMMMMMMMMMMX:  ;XMMMMMMMMMx.     //
//     .xMMMMMMMMMMO.  oWMMMMMMMMMMMMMMMMMMMMMK,  .OMMMMMMMM0'  ,KMMMMMMMMMMMMMMMMMMMMMWo  .kMMMMMMMMMMx.     //
//      dMMMMMMMMMMWd. .OMMMMMMMMMMMMMMMMMMMMMK,  .OMMMMMMMM0'  ,KMMMMMMMMMMMMMMMMMMMMMO' .dWMMMMMMMMMMx.     //
//      ,OWMMMMMMMMMWd. :XMMMMMMMMMMMMMMMMMMMMK,  .OMMMMMMMM0'  ,KMMMMMMMMMMMMMMMMMMMMNc .dNMMMMMMMMMWO,      //
//       .;d0WMMMMMMMWk..oNMMMMMMMMMMMMMMMMMMMK,  .OMMMMMMMM0'  ,KMMMMMMMMMMMMMMMMMMMNo..xWMMMMMMMWKd;.       //
//          .,cok0XNWMM0:.'dKWMMMMMMMMMMMMMMMMK,  .OMMMMMMMM0'  ,KMMMMMMMMMMMMMMMMWKd,.;0WMMNX0koc,.          //
//    cccccccccccodONMMMNx, .cONMMMMMMMMMMMMMMK,  'OMMMMMMMM0'  ,KMMMMMMMMMMMMMMNOc. 'xNMMMN0xoccccccccccc    //
//    MMMMMMMMMMMMMMMMMMMMNx;  ,xXMMMMMMMMMMMMK,  'OMMMMMMMM0'  ,KMMMMMMMMMMMMXx,  ,xNMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMNOl'..l0WMMMMMMMMMK,  .OMMMMMMMM0'  ,KMMMMMMMMMW0l..'lONMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMNOo:;::loxk0XNWK,  .kMMMMMMMMO.  ,0WNX0kxol::;:oONMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdl:,',,;;,.   'oOXWWXOo'   .,:;,,',:ldOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMXdOWMWNXK0OOOOOOOO0XWWX0OOOOOOOO0KXNWMWOdKMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMWKllKMMMXOXMMMMWWMMMMMMMMMMMMWWMMMMXOXMMMKll0WMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMN0KWMMMX:cXMMMW0KMMMMNXXNMMMM00WMMMXc:XMMMWK0NMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd:0MMMMKcxMMMMKdd0MMMMxcKMMMM0:dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0o0MMMMMd'kMMMMk;;kMMMMk'dMMMMM0oOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNk0MMMMMWl;KMMMMd..dMMMMX:cNMMMMM0kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXXWMMMMMK:oWMMMWo..oWMMMWo:KMMMMMWXXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMOcOMMMMMd..dMMMMMOcOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkoNMMMMMx..xMMMMMNdxMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWxkMMMMMMx''xMMMMMMOxWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXkKMMMMMMk,,kMMMMMMKOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXKWMMMMMMk:;kMMMMMMWKXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNMMMMMMMOccOMMMMMMMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMM0ll0MMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKdd0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKxxKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXOOXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                            //
//                                                                                                            //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract DT is ERC721Creator {
    constructor() ERC721Creator("Darrell Thorne", "DT") {}
}
