
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Chanel.Something
/// @author: manifold.xyz

import "./ERC721Creator.sol";

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                              //
//                                                                                                                                                              //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNWMMMMMMX0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO;':0MMMMNl.;KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.'xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc   oWMMMK, .kMMMMMMMMMMMWXKKNWMMMMMMMMMMMMMMMMMMMMMMMMMM0' .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc   cNMMMK, .xMMMMMMMMMMNo...,OWMMMMMMMMMMMMMMMMMMMMMMMMWd  .OMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNc   ;XMMM0' .dWMMMMMMMMNo.    ;KMMMMMMMMMMMMMNKkx0NMMMMMX:  ,KMMMMMMMMMMMMMMMMMMMKl,lXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWl   '0MMM0'  oWMMMMMMMWk. .'  .dWMMMMMMWX0Ooc,..;xNMMMMMO.  :XMMMMMMMMMMMMMMMMMMMx. .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWd.  .xMMMK,  lNMMMMMMMK; .ox.  ;KMWX0dc,....'cx0NMMMMMMWd.  cNMMMMMMMMMMMMMMMMMMWo   oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMWKOxdxOXWMWNx.   oWMMK,  cNMMMMMMWo  ;KX;  .:l:.. .,cox0NMMMMMMMMMMNc   oWMMMMMMMMMMMMMMMMMMWl   cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMKl.  .. .lxl,;.   :XMMK;  :XMMMMMM0' .dXO;     .,cx0NMMMMMMMMMMMMMMMK,  .dMMMMMMMMMMWNNXNWMMMWl   :XMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMM0,  .l0x'     ..   ,KMMX;  ,KMMMMMWo  .'.      ;0NMMMWKOkxxONMMMMMMMMO.  .xMMMWNKOxoc::ccl0WMMWl   ,KMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMX:   :XMW0:     .   .OMMX;  '0MWXOd:.    .,c,   ,KMMMWk'     cKMMMMMMWd.  .dOdc;'.',cok0XNNWMMMWo   '0MMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMWx.  .kMMMMXo.  ..   .kMMX:  .lo:.     .ckKWMk.   oWMMX:       lNMMMMMWl   .:c;:ldOXWMMMMMMMMMMMWo   .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMNc   :XMMMMMWXOk0x.  .xMW0,       .'.  lNMMMMX:   'OMM0'       .dWMMMMN:   .OWWMMMMMMMMMMWWNXXWMWo   .xMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMM0,   oWMMMMMMMMMM0'   ;l;.    .;okKk. .kMMMMMMk.   cXM0'        .OMMMMK;   '0MMMMMMWX0koc:::clOWWd    dWMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMO.  .xMMMMMMMMMMWO'           cNMMWd. ,KMMMMMMXc   .xW0'         ;KMMM0'   '0MMWKxl;...'cdOXNNWMWd.   lWMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMO.  .kMMMMMMW0xl,.    .cdk:   cNMMN:  cNMMMMMMMO.   ,0K;    .;.   cNMMO.   '0M0c.  .,oONWMMMMMMMWd.   cNMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMO.  .xMMMMMMXd;,;;.   cNMWl   :XMMK, .xMMMMMMMMNl    lK:    'xc   .oNMk.   ,0MXOxkOKWMMMMMMMMMMMMx.   ;XMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMM0'   dWMMMMMMWWWWWd   cNMWo   ;XMMO' '0MMMMMMMMM0,   .dc    ,0K;   .dNd.   ,KMMMMMMMMMMMWNX0kddkXx.   '0MMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMX:   cNMMMMMMMMMMMx.  :XMWd   ,0MM0' ;XMMMMMMMMMWd.   ,:.   cNWO'   .dl    ;KMMMWX00KOxl:,'';cokXk.   .OMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMWd.  '0MMMMMMMMWkol.  ;KMWd.  '0MMXc ;XMMMMMMMMMMXc    :olldKMMWO'   ..    :XMWO:......':okKNMMMMO.   .xMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMK;   cNMMMMMMXo.;d'  ,KMMx.  .OMMMXOONMMMMMMMMMMM0'   'OWMMMMMMW0;        oWMWKdlllok0NWMMMMMMMM0'    lWMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMM0,  .lXWWN0o,.lKX;  '0MMk.  .kMMMMMMMMMMMMMMMMMMWk.   c0NMMMMMMMNx:....'lXMMMMMMMMMMMMMMMMMMMMMX:    ;KMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMWWNNWWMMMMMMXOo:,..'cc:;:dKWMNl  '0MMO.   dWMMMMMMMMMMMMMMMMMMWd.  .:kMMMMMMMMMWXK0KNWMMMMMMMMMMMMMMMMMMMMMMMk'    cOOkxdoolloodxKWMMMMMMMMMMMM    //
//    MMMWKxl:,,,,;cd0WMX: .oXKOkkOKNWMMMMWd. '0MM0,   lNMMMMMMMMMMMMMMMMMMMNd.   cNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0o;...''',;clol;';dXMMWXOkk0NMMMM    //
//    MMKl.  .lkko'  .:Oo. .xWNKKNWMMMMMMMMO. '0MMX;   ;XMMMMMMMN0ollo0WMMMMWNx'..:KWWWWWWWWNNNNNNXXXXXXKKKK0000OOkkxookNMMMMWNXXXXNWWMWk' 'xKWW0:..',.;kWMM    //
//    M0,   ;0WMMMXc   ..  .kx'..cXMMMMMMMMK, '0MMWl   '0MMMMMW0:..,. .xWXd:;;;'..',;;;,,,,'''''...''''',,,,,;;::ccclldONMMMMMMMMMMMMMWx. 'OWMWx.  ;0Xl..xWM    //
//    X:   .OMMMMMMNc      ;o.   cNMMMMMMMMNo.:KMMMk.  .kMMMMNd. ,OK;  '0NOdoollllllllllloooodc.  .okkkdx0KXXNNNWWMMWOlcodx0NMMMMMMMMWk. .dWMMO'  .kMMNo.,0M    //
//    0,   '0MMMMMMMK,     :l    .lKWMMMMWNNNXXWMMMNo..;0MMMK:  cKMX:  .dWMMMMMMMMMMMMMMMMMMMM0'  ,KMXc.'kMMMMMMMMMMK;  '. .xWMMMMMMMK,  :XMMNc   cNMMMX:.dW    //
//    X:   .dWMMMMMMWl     cl      'xNMM0;.'cOWMMMMMWXXNMMW0;  cXMMX;   oWMMMMMMMMMMMMMMMMMMMMO'  '0MO. .dWMMMMMMMMMWOc;,;cxXMMMMMMMNl  .kMMMO.  .dWMNOd:'xW    //
//    Wk.   .kWMMMMMM0:'.,lOo   .c; .lXMO.   .oNMMMMMMMMMWO'  cXMMM0'   oKOxdxxxxkkkOOO0KXNWMM0'  '0Mk.  oWMMMMMMMMMMM0:.cKMMMMMMMMMO.  :XMMWd.  .kMNo.  .oW    //
//    MWk'   .dNMMMMMMWNNWMWo   .d0,  :KNc     :0WMMMMMMWx.  :KMMMWx.  .o0l;,'...........',;o0O'  .OMk.  cNMMMMMMMMMMWo  .kMMMMMMMMNc   dWMMWo   .kWk.    :N    //
//    MMW0;    ;OWMMMMMMMMMMd.   oWO.  cXk.     'xNMMMMNo.  :KMMMMX:   .kMMWNNXXXKKKK00OOx:',xO'  .xMk.  ;XMMMMMMMMMMWl  .kWOlclkNM0'  .kMMMWo   .xO,     :X    //
//    MMMMNd.   .lKMMMMMMMMMk.   cNWo   oK:   .   ;ONWO;   cKMMMMMk.   ,KMMMMMMMMMMMMMMMMWNXNMK,  .dWO.  '0MMMMMMMMMMNl  .k0,    lNx.  '0MMMMx.   '.      ;X    //
//    MMMMMW0c.   'xNMMMMMMMO.   ;XM0,  .kx.  ;o,  .;;.  .dNMMMMMX:    lNMNXKKKXXXNNWWMMMMMMMMK,   lW0'  .kMMMMWMMMMMNl  .kO.    .ol   '0MMMMNo.          ,K    //
//    MMMMMMMWk,    ;OWMMMMM0,   '0MNl   c0:  .kNOo:;;:lxXWMMMMMWx.   .OMNk:'......',;:codOKWMK;   cN0'  .dWKo:;:dXMMWl  .kk.     ..   .OMMMMMW0xoooko.   '0    //
//    MMMMMMMMMXd.   .cKMMMMX;   .xMMx.  'Od.  cNMMMWWMMMMMMMMMMX;    cNMMWXKOkxddolc:;,...'oXX;   ;XK,   lk'     :KMWl  .kk.          .xMMMMMMMMMMMMO.   'O    //
//    MMMMMMMMMMW0:    'xWMMNl    lNMk.  .x0,  .OMMMMMMMMMMMMMMWd.   .OMMMMMMMMMMMMMMMWWX0OOKWX:   ,KX;   ..  '.   oNWl  .kx.  ::       oWMMMMMMMMMMMO.   .O    //
//    MMMMMMMMMMMMNd.   .lXMWx.   ,KMk.   oNl   lNMMMMMMMMMMMMMO'    lNMMMMMMMMMMMMMMMMMMMMMMMN:   '0N:      ;Oc   '0Wo  .kx.  l0;      ;XMMMMMMMMMMMO.   .k    //
//    MMMMMMMMMMMMMWx.    cXM0'   .dWd.   oWO.  '0MMMMMMMMMMMMX:    ,0MMNOlc:::::::::ccllood0WNc   .ONc     .xWx.   dNo  .xx.  lW0,     .kMMMMMMMMMMMO.   .x    //
//    MMMMMMMMMMMMMMWd.   .oWWo    ,x:   .xWX:   oWMMMMMMMMMMWd.   .dWMMW0dolllcccc:::;;;;;cxNNc   .OWo     :XM0'   :Kl  .dx.  lWM0,     lNMMMMMMMMMMO.   .d    //
//    MMMMMMMMMMMMMMMX:    '0MK;    .    ,0MWd.  ;KMMMMMMMMMMO'    :XMMMMMMMMMMMMMMMMMWWWWWMMMNl   .OMx.   .kMMNc   .xc   lx.  lWMM0;    :XMMMMMMMMMMO.    o    //
//    MMMMMMMMMMMMMMMWo    .kMM0;       .xWMM0,  .OMMMMMMMMMX:    .OMMMMMMMMMMMMMMMMMMMMMMMMMMWl   ,KMXo;,:xNMMMk.   cc   cO,  oWMMMN0xxkXWMMMMMMMMMMk.    o    //
//    WNXNWMMMMMMMMMMNc    ,0MMMXkl:;;cd0WMMMWo. ,0MMMMMMMMWd.    oWMMMMMMMMMMMMMMMMMMMMMMMMMMNc   oWMMMWWWMMMMMWOl:cOO;..oX0dxXMMMMMMMMMMMMMMMMMMMMMk.    o    //
//    O;.'lKWMMMMMMMWx.   .dWMMMMMMMWWMMMMMMMMN0OKWMMMMMMMMK;    '0MMMMMMMMMMMMMMMMMMMMMMMMMMMWk;,oXMMMMMMMMMMMMMMMWMMMNXXWMMMMMMMWWWWMMMMMMMMMMMMMMMx.    o    //
//    0,   .oKWMMMMNd.   .dNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK,    lNMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWWMMMMMMMMMMMMMMMMMMMMMMMWN0xolc::::::ccodkOKXWMMMMWd.   .d    //
//    Wd.    .cx0Kx;   .c0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0olldKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkc'. .:oxkkkkxdoc:,''',:lxO0c    .k    //
//    MX:  .lc,',,..':d0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:   .oXWMMMWWNXK0OOkxxdo:'...    .cX    //
//    MMO. .OMWNXKKXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMO.   .lxxdlc:,'....  .'xWWNKOxolodONM    //
//    MMWk,'kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOo;'.....',;cloxxo:;co0WMMMMMMMMMMMM    //
//    MMMWXKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKK0KKXNWMMMMMMWWMMMMMMMMMMMMMMMM    //
//                                                                                                                                                              //
//                                                                                                                                                              //
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract CHANELS is ERC721Creator {
    constructor() ERC721Creator("Chanel.Something", "CHANELS") {}
}
