
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Skiing - by Dave Markel
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                //
//                                                                                                                                                                                                                //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMWNNMMMMNXKXWMMM0kNMMMMNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMKc.lXMMXc.'xWMM0, lNMM0;.oNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMNl. :XK; .dNMMMXl  cXO' .kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMNd. ,' .dWMX0XMNo. '. 'OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMKl::::;.   .xWMXc.cXMNd.   '::cccOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMNx;,,,,,'. 'OMK;   :KWd. .'''''''cKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0OO0NMMMMMMMMMMMMMMMMMMMKl;:xNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNd:;lKMMMMWKxolclOWMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMWWWWWWWk. 'd; .,. ,c. ;0NWWWWWNWWMMMMMMMMMMMMMMMMM0dooooOWMMMMMO'  '0MMMMMMMMMMMMMMMMMMWd   .OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkoodKMMMMMMMO.   dMMMNo.    .dMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMN0OKWMMN0OOOOkc.   .xNd.   .dOOOOOKWMMN0OKWMMMMMMMMMMMMK;     .OMMMMMO.  '0MMMMMMMMMMWMMMMMMMMXxclkNMMMMMMMMMWWWMMMMMMMMMMMMWWMMMMMMMK,  .xMMMMMMMNOlcxXMMMk.  .d00NMMMMMMWWMMMMMMMMMMMMMMMWMMMMM    //
//    MMMMMMMXc..oNMNo.         lNMX;         .dNMK:..dNMMMMMMMMMMMWo  .,.  :XMMMMO.  'OWMXd:cdxc;,;cdXMMMMKl::oXMMk::lOxc;,,:dXMMMMW0dc;,,;cxXMMMK,  .xMMMMMMMNd::l0Wk:'   .;:oKMNOoc;,,:lkNMMMOc:o0Ol;,lXMMM    //
//    MMMMMMMMXc  lXMNo. .cxxd, .xKc  :dxx:. .dNMK; .dWMMMMMMMMMMMM0'  ;0c  .dWMMMO.  '0MM0'   ....   'kWMMk.  '0MWl    ...    ;KMMXc.  .,'.  'OWM0,  .xMMMMMMMK,  .xWx,.   .,,c00:.  .,'.  ;0MMo   ..   ,0MMM    //
//    MMMMMWNNNKc  cKNXo. ;0NN0, ..  lXNNO' .dXN0, .dXNNNWMMMMMMMMNc  .dWk.  ,KMMMO.  '0MM0'  .oXN0;   ,KMMk.  '0MWl   'xKXx.  .xMXc  .oXWNk.  ,KM0,  .xMMMMMMMK,  .xMWWo   ;XWWK;  .dXWNd.  :XMo   .cdkk0NMMM    //
//    MMMMNo''''.   .''.   .'''.     .'''.  ..''.   .''''xWMMMMMMMx.  ;0NX:   lWMMO.  '0MM0'  .OMMMO.  .kMMk.  '0MWl   cWMMX;  .dMO.  .,:::;.  .OMK,  .xMMMMMMMK,  .xMMMd   :XMMx.  .;:::,.  ,KMo   :NMMMMMMMM    //
//    MMMMNxcccc;.  ,cc;.  'ccc'    .;ccc'  .:cc'  .:ccccOMMMMMMMK;   .'''.   .kMMO.  '0MM0'  .OMMMO'  .kMMk.  '0MWl   cWMMX;  .dMk.  .,;;;;;;;oXMK,  .xMMMMMMMK,  .xMMMd   :XMMd   .;;;;;;;;dNMo   :NMMMMMMMM    //
//    MMMMMMMMMX: .oNMNl. :KMM0, .,. cXMMK; .oNMK: .oNMMMMMMMMMMWo   .'''''.   :XMO.  .OMM0'  .OMMNl   ;XMMk.  '0MWl   cWMMX;  .xMK,  .xWMMMWXNMMMK,  .xMMMMMMMK,  .xMMMd   :XMMO.  'OWMMMNXNMMMo   :NMMMMMMMM    //
//    MMMMMMMMK; .dNMXc  .:lll. .kNo. ,lll:.  cXMXc .lNMMMMMMMMMO.  .kNNNNN0,  .dW0'   'dN0'   '::'   ,0MMMk.  '0MWl   cWMMX;  .dMWx.  .;llc;.cKMMK,   .;;;;;c0K,  .xMMMd   :XMMWd.  .:llc,.lXMMo   :NMMMMMMMM    //
//    MMMMMMMMx..xWMNd......    lNMK;    ......oNMXc '0MMMMMMMMNo...oWMMMMMWd...cXWk,.  :X0'   .....:xXMMMMO,..:KMWd...oWMMXc..'kMMW0l,..  ..'c0WMK:.........,OXc..'kMMMx...lNMMMWOc,..  ..'lKMMx...lNMMMMMMMM    //
//    MMMMMMMMNkOWMMWXKKKK0l.   .dKl    .xKKKKKXWMMXxOWMMMMMMMMWXKKXWMMMMMMMWXKKXWMMNK00XW0'  .dK0KNWMMMMMMWXXKXWMMNXKKNMMMWNKXXNMMMMMWX0OO0KNWMMMWXKKKKKKKKKXWWXKKXWMMMNXKKNWMMMMMMNX0O00KNMMMMNXKKNWMMMMMMMM    //
//    MMMMMMMMMMMMWXKKKKKKo. ;x: ..  co. 'kK00KKKKKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0'  .kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMXo.......  '0MXc  .oNWx.  .......cXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXd::oKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMKdooooc.   .lNMXc.oNMX:    ,ooddxKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMXl  ;:. cXMNKNMK: .:' .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMXc  lXNo. :KMMMK; .dW0, .xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMXd;dNMMNx,,xNMMK,.xWMMKc:kNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMWWMMMMWWWWMMMMXKWMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                                                                                                                                //
//                                                                                                                                                                                                                //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract SKI is ERC721Creator {
    constructor() ERC721Creator("Skiing - by Dave Markel", "SKI") {}
}
