
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: Laura Leonello
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                            //
//                                                                                                            //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWQQHNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWW#NNQqQNMQMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMQ#EN#qHNqNBM#MQMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMQMQHNmdKEddBKHBHHqKmBQBQMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMQMMWQM##NQHmKdNNHHDHHG8mHHKg8dDdOXPGmEHNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMM#qNN#QEqN#WNqXbOhhwDODbD8XDXXXGdbbDhDAmHBQBH#QMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMQMMMMMHNWWNqqOO@OO0h&YY3oaaDw&0PADDhDTaO&a@AEAKKNMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMQQHNHH#NgdEAbPkysYccocctrvucusssOhOOyofuoox0whPAmHMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMQMMMNHBNNKbdbDDy0&xfLoti?1?]7i)=71lirtczon&aTo3ccuonPhdKEQQMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMQNq#NHgdby&Tanvjcct>11]=>*|**;*||*\7>?vuvt3cjt}cvvna0DAmQQMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMQmHm8OD8XOD0Tk&Y3rjl]1*\|;:|;;::::-:::;;*]>1lil])=ilvcnnyKEHQMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMQMMMKNqHEmKKGPkTnc3v?l17=7)*\;:--------,--,--::\*++]>=*|*itvLObKHMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMQHHqXdDDTwO0oo3oojtjill>**;---,,----------------:;*||;;;|]}Y&hbE#QMMMNQMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMQMMQH#N#qHAAhaw&oasocri]7>+;---,"-:]v30Og#MM#Hdaj>;::--::;:-:;1lcY0XENWWWMNQMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMQNNHdgXGOhwTL3vr]|;::-,_~^"-)oPQMMMMMMMMMMMMMMMMQdv*:------:|lvnDPd8KNHBWQMMMMMMMMMMMMMMMMM    //
//    MMMMMQWQQHdEdAGDh&kLct?|\:---,"""-=uHMMMMMMMMMMMMMMMMMMMMMMMMQT>-----:;l3ofyOD8NQHBMMMMMQMBMMMMMMMMM    //
//    MMMMBHBHNEqgXGdPTLuii=;:::--_~_:tAMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM#):,,--/rzLoOOh@HKgH#NBMHHNNQMMMMMMM    //
//    MQMMQQq8NNqg@OOTfvrl>=+*:--~~-lGMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMI--,:|1vu0aO@gbdKbGKBKNQBMMMMMMMM    //
//    MMMNWQBqNHEdPT&cvc}?1i]\--~";TMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMA=--:+?vvoahhP@NO@NHNNBMMMMMMMMM    //
//    MMMMBQMMNKXOToLcct}?1*:-"_":sMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMc:-;=ltvayhaOOTO@@KNN#MMMMMMMM    //
//    MMMMMBEgqEEd0ofovvv}|:,_~~:DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK/:;)}lo&TYsT&TD@OGgBQMMMMMMM    //
//    MMMQQqBBdgDhkTovill*:-,^~:KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMb::)=?t3Ltt3voh@hE8qHMMMMMMM    //
//    MMMMM##EbbAhnujrl]/;:-_^-DMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMk:*++ll}]?]tzyaODmHNQMMMMMM    //
//    MMMMMMqEAXhYuctrl+|\:_^_TMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMr;/>**>****zo&OqBBMWMMMMMM    //
//    MMMMMMNAXP&L3v?r])|;:~_*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMME|:|;:;;;:)rc0PHm#MNMMMMMM    //
//    MMMMQHmbXwTYovv17=*:,^"HMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM}:::-:::-;ufYkXGmqH#HMMMM    //
//    MMMQNqED@P&vvuI]ti|-~~;MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0:--"----|cYa0OdgKmHMQMMM    //
//    MMQ#Qm@TwYs3ct1i?l*:,^+MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK:-_,--,,|cn0aOODdKqNQMMM    //
//    MQQHqNOYsnLsclttl*;-~~cMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM*-,,,,-:lioaL0hOGgqNQMMM    //
//    MMQNNHhOa&fhn}vvl;;-~_?MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM;_,^,_,/7}ousYT@OA#QMMMM    //
//    MMQWqgkTDLYaorrv>||-~~*MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\""^__:+=Iczf&TOgmWMMMMM    //
//    MM#ENXDdwnoL}vc}+||-_^:MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMq:~~~,-;1j}o3s&hX@AmMMMMM    //
//    Q#NmHdKX0TnYccr>1*\-_~-AMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMs_^_^,:=rvcIoaYTO@q8QQMMM    //
//    MNBgmX80sysTYctr}7|-_^_iMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM|^^^,:+lv}ljoTyDDK#MMMMMM    //
//    QMmgqqOaaTaYo}vrl)|-_~,-EMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMT"~~-:)]}j1ivxT&GX#MMMMMMM    //
//    QQEWMgDT&kTxvuL3z]+-,"_,)MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM/~~-:;7li1}vvhwTNmM#QMMMMM    //
//    M#NMWNEkxyhus&sIYr>:-,^_-7MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMt__":*)11>lvunTO8mNNMEMMMMM    //
//    MMQmNHDGT0ao&Lot}il;--,_~,vMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMv,_,:)11=i}csfYbDEWQqBNMQMMM    //
//    QmHKWMgKkhhyu3IIccl):::,~_-1MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMl,,--*=>=i}toL0ak8GKN#QMQMMMM    //
//    MMBQMNmK@0PTY33suut+;:::-,,,>BMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMB=,__-|*==1]tvcaTahbXN#MMMMMMMM    //
//    MMQMMQq8XO0waToLzxv?*;:::---,:nMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo:,,,;|||+)lcnLTaabKEKWQMMMMMMMM    //
//    MQMMHQKK8@&xX0Lnouctl+;:;::--,-=8MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMh*-,-:;;/\*7}}cufbdXNqNNMBMMMMMMMM    //
//    MMMNMMNKOKXKXnY0L3ozr1||+;;:::--:ihMMMMMMMMMMMMMMMMMMMMMMMMMMMMMx;--::::;;|+?roukDDEmK#Q#MMMMMMMMMMM    //
//    MMMMMMNQbEDOas&hYosx3l=*+)1;;::-:,--]0QMMMMMMMMMMMMMMMMMMMMMMmt:--:;::;;**7cc3nOObKqNBMMMMMMMMMMMMMM    //
//    MMMMMqQQBXgPOswyOxso3vt?)]i7+7+;::--:--;}kEMMMMMMMMMMMMME0i);:--:;:;/+ijirjckOPXXK#NMMMMMMMMMMMMMMMM    //
//    MMQQMWQMBEHmbTbhh0Ts&uLvtii}ljl7==;:::-----:::|*7l})**;:----:::/*=)>iltuo&aDDbXgHQQMMMMMMMMMMMMMMMMM    //
//    MMMMMMMQQNBqEbyDDPDasLucv3r3vcvr}l1=;:;;;:-:----:-:-----:::;;;+i1}t}Ivnx&PTkbDKgXNM#MMMMMMMMMMMMMMMM    //
//    MMMMMMMMBBB#mOyKhDOTT&auvuv3oLovcjIc>>>+|+)*\;::;::::-:;:;*)==l?]rcco00YsPwhP8H#MQHBQWQ#MMMMMMMMMMMM    //
//    MMMMMMMMQMQNNDKDDOGP@T@TYnuuufcuccIfcvr}l1>)?l)>?>71>*|*>>]71>?tvc3vvuakDbdg8gWBNHQQMQWMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMW@NKKydKOhgO0&nssyowoknxxLT&0&nvvr3zcc3vrvtvrvzcv3LY0oY0khhO8DbH8AdWMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMBmWqHAgbDXmX@PTak&OOhXwOhkkOO&&cucYLcuYcoo&snhhTTPOddhXAbAXEQMQ#MMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMN#KDb@bPXENHbOD@XOqh@dKKqdd@bDOf0hTssaTaTDDDb@DgHKgqQ8NHWMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMm#HdgXbbqmHHgHBH8HdEmBqHgm#NEE8@dbhdgd88HEqqNKqKEBBQQMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMNWqNNQHNNQ#HHQHNWNWQQQBQWNQBBBmqHEqKgH##MMBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMEHQQBMBMWBQEMMMMMMMMMMMMMMMMMMN#BBMMQQQMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMWQMMQWQMMQQMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMQMMMMQMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    //
//                                                                                                            //
//                                                                                                            //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract LNL is ERC721Creator {
    constructor() ERC721Creator("Laura Leonello", "LNL") {}
}
