
// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

/// @title: PSXMA
/// @author: manifold.xyz

import "./ERC721Creator.sol";

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//             ..''''....                  ...''.......                                                                            .........                     ..                                                                                                                                                   //
//           .;oOKKKKK0Okdc;'..        ..;lxO0KKK000OOkxddl;.                        ..',:ldo:'                                 ..:dO0KKK0Odc.                 'lkkl,.                 ..:oooc;'..                  .':ll:,...    ..':lc:,...                                ..,:clooooolc:;'..                       //
//          .cONWWWWWWMMWNXXK0kdl;...'cdOKXWWWMMMMMMMMWWNXOl.                   .';ldk0KKXNNNXk;.          ...                .:oOKNWWMMMMMWXOl'              ,dKWWNKko:;;,'.         .ckXNNNXK0Oxo:,..         ..;ok0XNNXK0Oxdooodk0XNNXK0Okxdl:'.                       .,lx0KXXNNNNNNNXXKK0ko:'.    ...            //
//         ,dO00kxxxk0KNNWMMMMMNx::ok0XWWXK0000KXNNWMMMMWNO:.               .,cdkO00XNWWMMMMMMN0o,.        ':,              .:dOOOkkO0KNWMMMMWXx:.          .'oXWMMMMWNXK0d,         ,d0NWWWWMMMMWNXK0kxdc'. .,cdOXNWWMMMMMMMWWNNNNWWMMMMMMMWWNk:.                      .cx0NWMMMMMMMMMMMMMMMMWNXOdc:cdd;.            //
//       .,ldo:;:ccccc:cdOXWMMMNd;lKWMMMN0xo:,.',;ckXWMMWXk:             .,ok00Odc;;;cdOXNWMMMMWN0d;..    .:o:.            .:dl:,,;:ccldOXWMMMMNOc.        ,cd0XNWWMMMMWXk:.       .:xKK0OkkO0XNNWMMMMMN0dc;lkKXNNNNXKKXWWWMMMMMWNX00KNWWMMMMMNx.                     .;dKWMMWWNNXKKKKKXNNWWMMMMMWNXXXN0;             //
//       .;:,,;::cldkkkkk0XWMMMXd:oXMMMMN0dc'     .c0NMMWXk:           .;d0NWNk:'.';clllokKNWMMMMMNKOkdddxkxo,             .;:,.;oxkkOOOKXWMMMMMN0l.      'oOOxccd0XNNXOl'         :xxl:;;:::::cokXWMMMNkooxKWMWNK00d;',cxKWMMMMWKkl;,;oOXWMMWXd.                    .:ONWWNKkoc;;,,,,,;;cok0NWMMMMMMMM0;             //
//       .''..''...,cxKNWWWMMMMXd:oXMMMMN0dc'     .:ONMMWXk:          .:kNMMMXd'....';codxxk0NWMMMMMMMWWWWXd'               .',,;;;;:lx0XNWMMMMMMW0c.    ,oxxd;. .',;;,..          :dc,,:cldxkxdoxKWMMMXxcd0NWMWX00Oc.  .:kXMMMMWKd;.  'o0WMMWXo.                   .:kNWN0o;'.',:loollc;,'',lkXWMMMMMM0;             //
//         ...       .ckXWMMMMMXd:oXMMMMN0dc'     .:ONMMWXk:         .:xXWMMMNOl'     .,coxOO00XNWMMMMMMWKd,                 ...      .,cxKNMMMMMMN0l.  'dOo:'                     ':;'.''';cxKXXXWMMMMXdcd0NWMWX00Oc.  .;xXMMMMWKx;.  'o0WMMWXd.                   ,kXWKd;.':loodxkOKKXKOxc,:d0NWMMMMM0;             //
//                 ..',lONMMMMMXd:oXMMMMN0dc'.    .:ONMMWXk:         'lONMMMMMWKx;.      .;lxOKXNNWMMMMN0l.                              .;d0NMMMMMW0c';oxd;.                      .'..      .:xXWMMMMMXdcd0NWMWX00Oc.  .;xXMMMMWKx;.  'o0WMMWXd.                   :KWXd'.,::;,'...';cd0XWX0OkkOKWMMMM0;             //
//               .:dkOO0XWMMMMMXd:oXMMMMN0dc'.    .:ONMMWXk:        ':lxKWMMMMMMNKkl;'.    .':ok0XNWMMXx:.                                 .:xXWMMMMNOk00o'.                                  .,dKWMMMMXdcd0NWMWX00Oc.  .;xXMMMMWKx;.  'o0WMMWXd.                  .cKXk:.....         .,o0NNOl;cxXMMMM0;             //
//              ':oddxOXWMMMMMMXd:oXMMMMN0dc'.    .:ONMMWXk:       .locckNWMMMMMMMWNKOxoc;,.....,cdKNKd,                                  ...;dKWMMMMWNXOc.............                   .,cloxOKWMMMMXdcd0NWMWX00Oc.  .;xXMMMMWKx;.  'o0WMMWXd.                   c0Kd,.               'oxx:..,dXMMMW0;             //
//             .,;'...'cONMMMMMXd:oXMMMMN0dc'.    .cONMMWXk:       .okdccoOXWMMMMMMMMMMWNX0Oxdolccd0Kd,.                              .;ldxxxxOXWMMMMMWNKOxxxxxxxxxdl'.                  'lxO0XNWMMMMMMXdcd0NWMWX00Oc.  .;xXMMMMWKx;.  'o0WMMWXd.                   ;kOd,               .;oc'. .,dXMMMM0;             //
//              ..     .l0NMMMMXd:oXMMMMN0kxo:;;;;cxKWMMWXk:       .lOKOo::ldOKNWMMMMMMMMMMMMMWWNNNWNOdoc:;,..                       .c0NWMMMMMMMMMMMMMMMMMMMMMMMWXk:.                   ,ll;,:o0NWMMMMXdcd0NWMWX00Oc.  .;xXMMMMWKx;.  'o0WMMWXd.                   .cxxc.             .:lc'   .,dXMMMM0;             //
//                     .;xXWMMMXd:oXMMMMN0OKKK0000KXWWMMWXk:        'lKWXOdc::cloxkOKXNWWMMMMMMMMMMMMMWWWNXKOxoc;'.                 'o0WMMMMMMMMMMMMMMMMMMMMMMMMWXx,.                    ...   .:kXMMMMXdcd0NWMWX00Oo'..'lkNMMMMWKxc'..:xKWMMWXd.                    .ckd,            .lxo;....'ckNMMMM0;             //
//                      ,dKWMMMXd:oXMMMMN00XNNNNNNNWWMMMWXk:         'o0NWWX0xoc:::clloodxxkOKXWMMMMMMMMMMMMMWWWX0xc'.             .:dkkkkkkkkkk0XWMMMMMMMWXK0Okdc'                             .c0WMMMXdcd0NWMWX00KOolldkKWMMMMWKkdolox0NWMMWXd.                     .:ll;.        .;okOxollllokKWMMMM0;             //
//                      ,dKWMMMXd:oXMMMMN00NMMMMMMMMMMMMWXk:          .;d0NWMWWNXKOkxdolccclox0XX0kkkO0XNWMMMMMMMMWXOc.           ..'..........'cOXXKNMMMMNOdc,.                                .;0WMMMXdcd0NWMWXKKXXKKKKXNWMMMMWKO0KKKXNWMMMWXd.                       .;:,..     .:kXXKKKKKKKKXNWMMMM0;             //
//                      ;dKWMMMXd:oXMMMMN0OKXKKKKKKNWMMMWXk:            .;ok0XWMMMWWWWWWWNNXKXNNXkolloodxk0XWMMMMMMMWO;.                      .;dkxcckNMMMWX0x;                                  ;0WMMMXdcd0NWMWXKKNWWMMMMMMMMMMWK0XWMMMMMMMMWXd.                         ....    .l0NWMMMMMMMMMMMMMMMM0;             //
//              ...... .,dKWMMMXd:oXMMMMN0kdl:,,,,:xKWMMWXk:               .,cokO0KNWWMMMMMMMMMMMWWWNX0kdlldOXWMMMMMW0:.                      ,xOo'..c0NMMMMWXd'                                 ;0WMMMXdcd0NWMWXKKNWMMMMMMMMMMMWK0XWMMMMMMMMWXd.                               .;dKWMMMMMMMMMMMMMMMMMM0;             //
//           .,cdO0Oxo::okXWMMMXd:oXMMMMN0dc,.    .c0NMMWXk:                   ..';coxkOO0XWWWWMMMMMMMWWNX0xokXWMMMMWO,                     .;dOd,   .cOWMMMMWKd,                                ;0WMMMXdcd0NWMWXKKXX0O00XNWMMMMWKOO000KNWMMMWXd.                              ':dkO000000000000KNWMMMM0;             //
//         .:dKNWWMWWWNNNNWMMMMXd:oXMMMMN0dc'     .lKWMMWKo,               ..',,'...   ..,oKXOxkkO0KXNWWMMWXK0KNWMMN0l.                     ;xOo,.    .l0NMMMMWXo.                      ..''... .;OWMMMXdcd0NWMWX00Oo,..,lONMMMMWKxc,.':xKWMMWXd.                ..'''..     .;ll;.............,ckNMMMM0;             //
//       .,lk000KXNWMMMMMMMMMMMNOokNMMMMN0dc'.    .oXMMWKo'.             .:d0XNXKOdc;....'l0k;. ...,:ldkKNWMWWWWMMW0c.        ..;::;'.    .;dOd'       .cOWMMMMW0o'                  .'cx0XXKko:;lKWMMMXo:o0NWMWX00Oc.  .:xXMMMMWKx;.  'o0WMMMXd.             ..:d0XXXOdc,'';lc,.              .;xXMMMW0;             //
//       ,xxc'..':lxOKXNWMMMMMMMWNWMMMMMN0xc'    .;kNWKxc.             .ckKNWMMMMWWNX0koodkko.         .'lkXWMMMMNOl.       .:d0XNNXOl'   ;xOo,.        .lKWMMMMWKo.               .'o0XWMMMMWWXKXWMWN0d,.cONWMWX00Oc.  .;xXMMMMWKd;.  'o0WMMMNd.            'lOXWWMMMWWNXKKkl,.               .;xXMMMM0;             //
//       ;dl.      ..':dOXWMMMMMMMMMMMMMWXOd:'..'lkK0x:.             .;okOOO0KXNWMMMMMWWNWN0d:...         'dXMMWNk;.      .:xKNMMMMMWXxc;:dOd'           'l0XWMMMW0o'      ..     .:xO00KKXNWMMMMMMMN0l'..cONWMWN00Oc.  .;xXMMMMWKx;.  'o0WMMMNx.          .:dO000KXNWMMMMMMN0d:'.             .cONMMMM0:.            //
//       ,oc.          .:xXWMMMMWWWMMMMMMWWNX0O000ko;.              .,dkc....':ok0XNWMMMMMMWNXKkdc,...    .lXMW0o,.      'okOO0XNMMMMMWXXKOl,             .lk0WMMMWXk:....','.   'cdd:...,cdOKNWMMMMMNKklcxKNMMWX00Oc.  .;xXMMMMWXk:.  'o0WMMMWk'   ...   .:dxc...':ok0XNWMMMWWNKxl;..         ,xXWMMMMKl.   .        //
//       ;dl.           ,dKWMMMWKOKWMMMMMMMMWNX0x:..                'col.       ..;lx0NWMMMMMMMWWNX0kdc;;cd0NXOc.       ,ldl,..;d0NWMMMMWXd'               .,:kNMMMMWXOdodl,.   .cxo'.     ..,cx0NWMMMMWNNNWMMMWX0Okc.  .;dXMMMMMW0c.  'l0WMMMW0l'.'::.  .:oo;.      .';okKXWWMMMWNX0xl;'.....;dKWMMMMMXkc'':c.       //
//       .cc;.          ,dKWMMWXxcdXMMMMMWNXOd:'.                  .,cl:.          .'cxO000XNWWMMMMMWNNXXXNX0o'        .ldc'.   .,dKWMMWKo,                  .;dKWMMMMWXOo,.    .lkl.          .'cxKNWMMMMMMMMMWX0xc'    .l0WMMMMW0:.  .;xNMMMMWXKOd:'   .cdl'.          .':dOXNWMMMMWNXK0OkkO0OO0NWMMMWNX0xo;.       //
//        ..','....     ,dKWMMWKd:oXMMMMXkc,..                      .;oo'          .;oo:'..,cdOKNNWWMMMMWN0o,.         .ldc.      .;dKNXd'                     .:kKNWNKx:.      .:dl'.            .,lkKNWMMMMWXOl,..      'dKWMMNOl.    .:kXWMMMWKx:.     ,ll;.             ..,lkKNWWMMMMMWNXOo;',o0NWMMWN0o,.        //
//                      ;dKWMMWKd:oXMMMW0c.                          .cdc,.      .'clc,.     ..';lxOKNNXOo,.           .,cc;.       .;cc,                        .:odl,.         .,cc,.              .;lkKNNKkc.           .:kKXO:.       'lOXNKkc.        'cl;.                .':dOKNNNXOd:..   .;d0XX0d;.          //
//                      ;dKWMMWXd:oXMMMW0c.                           .':llc:;;:clc:'.            ..';:,..               .cl,.                                     ..              .,;,...              .,:c;.               .,;,.         ..;:;.           .,,,'..                ..,:cc;..        .'::'.            //
//                      ,dKWMMMNxcdXMMWN0d:'.                           ...''''''..                                       .',,'....                                                  ....                                                                      ...                                                    //
//                      'o0WMMMWKO0NWXOo:'..                                                                                 ...                                                                                                                                                                                      //
//                      .,xNMMMMWNX0x:..                                                                                                                                                                                                                                                                              //
//                        ,o0NWWXOo,.                                                                                                                                                                                                                                                                                 //
//                         .,:lc;'.                                                                                                                                                                                                                                                                                   //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
//                                                                                                                                                                                                                                                                                                                    //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


contract PSXMA is ERC721Creator {
    constructor() ERC721Creator("PSXMA", "PSXMA") {}
}
